/- This file is generated by research/generate_chapter_vi_connector_factor_derivative_admissibility.py. -/
import PoincareChapterVI.ChapterVIDConnectorFactorDerivativeReference

namespace PoincareChapterVI.ChapterVIDConnectorFactorDerivativeReference

open ChapterVILeanCompCertBatch
open LeanCompCert.Ports.SignedProductClaims

set_option maxRecDepth 1000000 in
theorem shard_admissible_initial_15 :
    Admissible (batchClaims (shardOperations .initial ⟨15, by decide⟩)) := by
  refine ⟨?_, ?_, ?_⟩
  · decide +kernel
  · decide +kernel
  · decide +kernel

set_option maxRecDepth 1000000 in
theorem shard_allHold_initial_15 :
    ∀ claim ∈ batchClaims (shardOperations .initial ⟨15, by decide⟩),
      claim.Holds := by
  decide +kernel

end PoincareChapterVI.ChapterVIDConnectorFactorDerivativeReference
