/- This file is generated by research/generate_chapter_vi_connector_factor_derivative_admissibility.py. -/
import PoincareChapterVI.ChapterVIDConnectorFactorDerivativeReference

namespace PoincareChapterVI.ChapterVIDConnectorFactorDerivativeReference

open ChapterVILeanCompCertBatch
open LeanCompCert.Ports.SignedProductClaims

set_option maxRecDepth 1000000 in
theorem shard_admissible_initial_1 :
    Admissible (batchClaims (shardOperations .initial ⟨1, by decide⟩)) := by
  refine ⟨?_, ?_, ?_⟩
  · decide +kernel
  · decide +kernel
  · decide +kernel

end PoincareChapterVI.ChapterVIDConnectorFactorDerivativeReference
