#!/usr/bin/env python3
"""Generate kernel checks for the two full-circle pinching-quarter prefix tables."""

from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "PoincareChapterVI" / "PinchingArcPrefixAdmissibility"
SIDES = ("upper", "lower")
ROWS = 22


def module_text(side: str, index: int) -> str:
    return f"""/- This file is generated by
research/generate_chapter_vi_pinching_prefix_admissibility.py. -/
import PoincareChapterVI.ChapterVIDPinchingArcPrefixCompiledGrid

namespace PoincareChapterVI.ChapterVIDPinchingArcPrefixCompiledGrid

open ChapterVILeanCompCertBatch
open LeanCompCert.Ports.SignedProductClaims

set_option maxRecDepth 1000000 in
theorem shard_admissible_{side}_{index} :
    Admissible (batchClaims (shardOperations .{side} {index})) := by
  refine ⟨?_, ?_, ?_⟩
  · decide +kernel
  · decide +kernel
  · decide +kernel

set_option maxRecDepth 1000000 in
theorem shard_allHold_{side}_{index} :
    ∀ claim ∈ batchClaims (shardOperations .{side} {index}), claim.Holds := by
  decide +kernel

end PoincareChapterVI.ChapterVIDPinchingArcPrefixCompiledGrid
"""


def aggregate_text() -> str:
    imports = "\n".join(
        f"import PoincareChapterVI.PinchingArcPrefixAdmissibility.{side.capitalize()}{index}"
        for side in SIDES for index in range(ROWS)
    )
    admissible_cases = []
    all_hold_cases = []
    for side in SIDES:
        admissible_bullets = "\n".join(
            f"    · exact shard_admissible_{side}_{index}" for index in range(ROWS)
        )
        all_hold_bullets = "\n".join(
            f"    · exact shard_allHold_{side}_{index}" for index in range(ROWS)
        )
        admissible_cases.append(f"  | {side} =>\n    fin_cases i\n{admissible_bullets}")
        all_hold_cases.append(f"  | {side} =>\n    fin_cases i\n{all_hold_bullets}")
    return f"""/- This file is generated by
research/generate_chapter_vi_pinching_prefix_admissibility.py. -/
{imports}

namespace PoincareChapterVI.ChapterVIDPinchingArcPrefixCompiledGrid

open ChapterVILeanCompCertBatch
open LeanCompCert.Ports.SignedProductClaims
open scoped unitInterval

theorem shard_admissible (side : ChapterVIDPinchingArcSide) (i : Fin 22) :
    Admissible (batchClaims (shardOperations side i)) := by
  cases side with
{chr(10).join(admissible_cases)}

theorem shard_allHold (side : ChapterVIDPinchingArcSide) (i : Fin 22) :
    ∀ claim ∈ batchClaims (shardOperations side i), claim.Holds := by
  cases side with
{chr(10).join(all_hold_cases)}

/-- Unconditional verified-program verdict for all 44 pinching-prefix shards. -/
theorem referenceRunVerdict : CompiledVerdict where
  shard side i :=
    ⟨shard_admissible side i,
      ChapterVILeanCompCertIntervalBridge.returns_zero_of_allHold
        (shardArtifactName side i) (batchClaims (shardOperations side i))
        (shard_admissible side i) (shard_allHold side i)⟩

/-- The literal radicand has positive real part on both pinching quarters throughout the
certified global prefix. -/
theorem radicand_re_pos_reference
    (side : ChapterVIDPinchingArcSide) (st : I × I)
    (hprefix : (st.1 : ℝ) ≤ prefixEnd) :
    0 < (chapterVIDPinchingArcRadicand side st).re :=
  radicand_re_pos referenceRunVerdict side st hprefix

theorem radicand_ne_zero_reference
    (side : ChapterVIDPinchingArcSide) (st : I × I)
    (hprefix : (st.1 : ℝ) ≤ prefixEnd) :
    chapterVIDPinchingArcRadicand side st ≠ 0 :=
  radicand_ne_zero referenceRunVerdict side st hprefix

end PoincareChapterVI.ChapterVIDPinchingArcPrefixCompiledGrid
"""


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    for side in SIDES:
        for index in range(ROWS):
            (OUT / f"{side.capitalize()}{index}.lean").write_text(
                module_text(side, index)
            )
    aggregate = ROOT / "PoincareChapterVI" / "ChapterVIDPinchingArcPrefixAdmissibility.lean"
    aggregate.write_text(aggregate_text())


if __name__ == "__main__":
    main()
