#!/usr/bin/env python3
"""Emit the concrete LeanCompCert radial grid for Chapter VI.

All arithmetic here merely constructs proposed outward-rounded integer intervals.  The generated
Lean file asks the compiled checker to verify every multiplication and reciprocal; its output is
therefore not trusted.
"""

from fractions import Fraction
from math import isqrt

P = 20
S = 1 << P
N = 16


def floor_fraction(x: Fraction) -> int:
    return x.numerator // x.denominator


def ceil_fraction(x: Fraction) -> int:
    return -((-x.numerator) // x.denominator)


def mul(x: tuple[int, int], y: tuple[int, int]) -> tuple[int, int]:
    corners = [x[0] * y[0], x[0] * y[1], x[1] * y[0], x[1] * y[1]]
    return floor_fraction(Fraction(min(corners), S)), ceil_fraction(Fraction(max(corners), S))


def add(x: tuple[int, int], y: tuple[int, int]) -> tuple[int, int]:
    return x[0] + y[0], x[1] + y[1]


def neg(x: tuple[int, int]) -> tuple[int, int]:
    return -x[1], -x[0]


def sub(x: tuple[int, int], y: tuple[int, int]) -> tuple[int, int]:
    return add(x, neg(y))


def reciprocal(x: tuple[int, int]) -> tuple[int, int]:
    assert 0 < x[0]
    return floor_fraction(Fraction(S * S, x[1])), ceil_fraction(Fraction(S * S, x[0]))


def integer_nth_root_floor(value: int, n: int) -> int:
    lo, hi = 0, 1
    while hi**n <= value:
        hi *= 2
    while lo + 1 < hi:
        mid = (lo + hi) // 2
        if mid**n <= value:
            lo = mid
        else:
            hi = mid
    return lo


def power_trace(point: int, n: int) -> list[tuple[int, int]]:
    x = (point, point)
    square = mul(x, x)
    cube = mul(square, x)
    if n == 3:
        return [square, cube]
    assert n == 6
    sixth = mul(cube, cube)
    return [square, cube, sixth]


def root_trace(input_interval: tuple[int, int], n: int):
    # If y is represented at scale S, y^n <= x is y^n <= x*S^(n-1).
    lower_target = input_interval[0] * S ** (n - 1)
    upper_target = input_interval[1] * S ** (n - 1)
    lower = integer_nth_root_floor(lower_target, n)
    upper = integer_nth_root_floor(upper_target, n)
    if upper**n < upper_target:
        upper += 1
    while power_trace(lower, n)[-1][1] > input_interval[0]:
        lower -= 1
    while power_trace(upper, n)[-1][0] < input_interval[1]:
        upper += 1
    return (lower, upper), power_trace(lower, n), power_trace(upper, n)


ONE = (S, S)
QD = (floor_fraction(Fraction(3, 4000) * S), ceil_fraction(Fraction(11, 10000) * S))
XABS = (floor_fraction(Fraction(26, 1000) * S), ceil_fraction(Fraction(27, 1000) * S))
QD6, QD6_LO, QD6_HI = root_trace(QD, 6)
RD, RD_LO, RD_HI = root_trace(XABS, 3)
QD6_INV = reciprocal(QD6)
CORRECTION = mul(RD, QD6_INV)


def cell(i: int):
    inp = (i * (S // N), min(i + 1, N) * (S // N))
    q_product = mul(inp, sub(QD, ONE))
    q = add(ONE, q_product)
    q3, q3lo, q3hi = root_trace(q, 3)
    q6, q6lo, q6hi = root_trace(q, 6)
    correction_product = mul(inp, sub(CORRECTION, ONE))
    correction_factor = add(ONE, correction_product)
    radius = mul(q6, correction_factor)
    return {
        "input": inp,
        "q_product": q_product,
        "q3": q3,
        "q3lo": q3lo,
        "q3hi": q3hi,
        "q6": q6,
        "q6lo": q6lo,
        "q6hi": q6hi,
        "correction_product": correction_product,
        "radius": radius,
    }


CELLS = [cell(i) for i in range(N + 1)]


def iv(x: tuple[int, int]) -> str:
    return f"⟨{x[0]}, {x[1]}⟩"


def vector(name: str, values: list[tuple[int, int]]) -> str:
    rows = ",\n  ".join(iv(x) for x in values)
    return f"def {name} : Fin 17 → Interval := ![\n  {rows}]\n"


def field_values(field: str):
    return [c[field] for c in CELLS]


def power_values(field: str, operation: int):
    return [c[field][operation] for c in CELLS]


print("""/- This file is generated by research/generate_chapter_vi_radial_grid.py. -/
import PoincareChapterVI.ChapterVIDRadialTrace
import PoincareChapterVI.ChapterVIUnitSquareGrid

namespace PoincareChapterVI

open ChapterVILeanCompCertBatch
open LeanCompCert.Ports.SignedProductClaims
open scoped unitInterval

namespace ChapterVIDRadialCompiledGrid

abbrev Interval := ChapterVIDRadialTrace.Interval 20
""")

print(f"def qD : Interval := {iv(QD)}")
print(f"def qDSixthRoot : Interval := {iv(QD6)}")
print(f"def xAbs : Interval := {iv(XABS)}")
print(f"def collisionRadius : Interval := {iv(RD)}")
print(f"def qDSixthInv : Interval := {iv(QD6_INV)}")
print(f"def correction : Interval := {iv(CORRECTION)}")

print(f"""
def endpoint : ChapterVIDRadialTrace.EndpointTrace (precision := 20) where
  qD := qD
  qDSixthRoot := qDSixthRoot
  qDSixthTrace := {{
    lowerPower := {{ square := {iv(QD6_LO[0])}, cube := {iv(QD6_LO[1])}, sixth := {iv(QD6_LO[2])} }}
    upperPower := {{ square := {iv(QD6_HI[0])}, cube := {iv(QD6_HI[1])}, sixth := {iv(QD6_HI[2])} }} }}
  xAbs := xAbs
  collisionRadius := collisionRadius
  collisionTrace := {{
    lowerPower := {{ square := {iv(RD_LO[0])}, cube := {iv(RD_LO[1])} }}
    upperPower := {{ square := {iv(RD_HI[0])}, cube := {iv(RD_HI[1])} }} }}
  qDSixthInv := qDSixthInv
  correction := correction
""")

print("""def input (i : Fin 17) : Interval :=
  ⟨(i.val * 65536 : ℕ), (min (i.val + 1) 16 * 65536 : ℕ)⟩
""")
print(vector("qDeltaProduct", field_values("q_product")))
print(vector("qCubeRoot", field_values("q3")))
print(vector("qCubeLowerSquare", power_values("q3lo", 0)))
print(vector("qCubeLowerCube", power_values("q3lo", 1)))
print(vector("qCubeUpperSquare", power_values("q3hi", 0)))
print(vector("qCubeUpperCube", power_values("q3hi", 1)))
print(vector("qSixthRoot", field_values("q6")))
print(vector("qSixthLowerSquare", power_values("q6lo", 0)))
print(vector("qSixthLowerCube", power_values("q6lo", 1)))
print(vector("qSixthLowerSixth", power_values("q6lo", 2)))
print(vector("qSixthUpperSquare", power_values("q6hi", 0)))
print(vector("qSixthUpperCube", power_values("q6hi", 1)))
print(vector("qSixthUpperSixth", power_values("q6hi", 2)))
print(vector("correctionDeltaProduct", field_values("correction_product")))
print(vector("radius", field_values("radius")))

print("""
def trace (i : Fin 17) : ChapterVIDRadialTrace.Trace endpoint (input i) where
  qDeltaProduct := qDeltaProduct i
  qCubeRoot := qCubeRoot i
  qCubeTrace := {
    lowerPower := { square := qCubeLowerSquare i, cube := qCubeLowerCube i }
    upperPower := { square := qCubeUpperSquare i, cube := qCubeUpperCube i } }
  qSixthRoot := qSixthRoot i
  qSixthTrace := {
    lowerPower := { square := qSixthLowerSquare i, cube := qSixthLowerCube i, sixth := qSixthLowerSixth i }
    upperPower := { square := qSixthUpperSquare i, cube := qSixthUpperCube i, sixth := qSixthUpperSixth i } }
  correctionDeltaProduct := correctionDeltaProduct i
  radius := radius i

def operations : List (DyadicOperation 20) :=
  endpoint.operations ++ (List.ofFn fun i : Fin 17 => (trace i).operations).flatten

theorem endpoint_operations_mem (operation : DyadicOperation 20)
    (hoperation : operation ∈ endpoint.operations) : operation ∈ operations := by
  simp [operations, hoperation]

theorem trace_operations_mem (i : Fin 17) (operation : DyadicOperation 20)
    (hoperation : operation ∈ (trace i).operations) : operation ∈ operations := by
  rw [operations, List.mem_append, List.mem_flatten]
  exact Or.inr ⟨(trace i).operations, List.mem_ofFn.mpr ⟨i, rfl⟩, hoperation⟩

theorem endpoint_valid : endpoint.Valid := by
  unfold ChapterVIDRadialTrace.EndpointTrace.Valid
    ChapterVILeanCompCertRoots.CubicRootTrace.Valid
    ChapterVILeanCompCertRoots.SixthRootTrace.Valid
  decide +kernel

theorem trace_valid (i : Fin 17) : (trace i).Valid := by
  unfold ChapterVIDRadialTrace.Trace.Valid
    ChapterVILeanCompCertRoots.CubicRootTrace.Valid
    ChapterVILeanCompCertRoots.SixthRootTrace.Valid
  fin_cases i <;> decide +kernel

theorem operations_admissible : Admissible (batchClaims operations) := by
  refine ⟨?_, ?_, ?_⟩
  · decide +kernel
  · decide +kernel
  · decide +kernel

set_option maxRecDepth 100000 in
theorem operations_returns_zero :
    (batchComputation "chapter-vi-d-radial-grid-20" operations).Returns
      ((0 : Nat) : Int) := by
  decide +kernel

theorem qD_contains : qD.Contains chapterVIDCriticalParameterModulus := by
  obtain ⟨hlower, hupper⟩ := chapterVIDCriticalParameterModulus_bounds
  constructor
  · exact (by norm_num [qD, ChapterVISignedDyadicInterval.toRealInterval,
      ChapterVISignedDyadicInterval.scale] :
        ((qD.lower : ℝ) / ChapterVISignedDyadicInterval.scale 20) ≤ 3 / 4000).trans hlower
  · exact hupper.trans (by norm_num [qD, ChapterVISignedDyadicInterval.toRealInterval,
      ChapterVISignedDyadicInterval.scale] :
        (11 / 10000 : ℝ) ≤ (qD.upper : ℝ) / ChapterVISignedDyadicInterval.scale 20)

theorem xAbs_contains : xAbs.Contains (-chapterVIDRoot) := by
  constructor
  · change (xAbs.lower : ℝ) / ChapterVISignedDyadicInterval.scale 20 ≤ -chapterVIDRoot
    exact (by norm_num [xAbs, ChapterVISignedDyadicInterval.scale] :
      (xAbs.lower : ℝ) / ChapterVISignedDyadicInterval.scale 20 ≤ 26 / 1000).trans
        (by linarith [chapterVIDRoot_mem.2])
  · change -chapterVIDRoot ≤ (xAbs.upper : ℝ) / ChapterVISignedDyadicInterval.scale 20
    exact (by linarith [chapterVIDRoot_mem.1] : -chapterVIDRoot ≤ 27 / 1000).trans
      (by norm_num [xAbs, ChapterVISignedDyadicInterval.scale])

theorem correction_contains :
    endpoint.correction.Contains chapterVIDCertificateContourCorrection := by
  apply endpoint.correction_contains_of_allSound endpoint_valid
  · intro operation hoperation
    exact allSound_of_returns_zero "chapter-vi-d-radial-grid-20"
      operations operations_admissible operations_returns_zero operation
      (endpoint_operations_mem operation hoperation)
  · exact qD_contains
  · exact xAbs_contains

theorem input_contains_of_mem_cell (i : Fin 17) {parameter : I}
    (hparameter : parameter ∈ chapterVIUnitGridCell 15 i) :
    (input i).Contains (parameter : ℝ) := by
  have hbounds := hparameter
  simp only [chapterVIUnitGridCell, Set.mem_ofPred_eq] at hbounds
  constructor
  · change (((i.val * 65536 : ℕ) : ℤ) : ℝ) / (2 : ℝ) ^ 20 ≤ (parameter : ℝ)
    convert hbounds.1 using 1 <;> norm_num <;> ring
  · change (parameter : ℝ) ≤
      (((min (i.val + 1) 16 * 65536 : ℕ) : ℤ) : ℝ) / (2 : ℝ) ^ 20
    convert hbounds.2 using 1 <;> norm_num <;> ring

theorem outputs_contain_cell (i : Fin 17) {parameter : I}
    (hparameter : parameter ∈ chapterVIUnitGridCell 15 i) :
    (trace i).qCubeRoot.Contains
        (chapterVIDCertificateParameter parameter ^ ((3 : ℝ)⁻¹)) ∧
      (trace i).radius.Contains (chapterVIDCertificateContourRadius parameter) := by
  apply (trace i).outputs_contain_of_allSound (trace_valid i)
  · intro operation hoperation
    exact allSound_of_returns_zero "chapter-vi-d-radial-grid-20"
      operations operations_admissible operations_returns_zero operation
      (trace_operations_mem i operation hoperation)
  · exact input_contains_of_mem_cell i hparameter
  · exact qD_contains
  · exact correction_contains

/-- Every radial parameter belongs to a cell whose one compiled verdict encloses both source
coordinates needed by the outer-arc formula. -/
theorem exists_outputs_contain (parameter : I) :
    ∃ i : Fin 17,
      (trace i).qCubeRoot.Contains
          (chapterVIDCertificateParameter parameter ^ ((3 : ℝ)⁻¹)) ∧
        (trace i).radius.Contains (chapterVIDCertificateContourRadius parameter) := by
  let i := chapterVIUnitGridIndex 15 parameter
  exact ⟨i, outputs_contain_cell i (chapterVIUnitGridIndex_mem_cell 15 parameter)⟩

end ChapterVIDRadialCompiledGrid

end PoincareChapterVI
""")
