#!/usr/bin/env python3
"""Generate independently buildable admissibility checks for connector-factor shards."""

from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "PoincareChapterVI" / "ConnectorFactorAdmissibility"
SIDES = ("initial", "final")
SHARDS = 32


def module_text(side: str, index: int) -> str:
    return f"""/- This file is generated by research/generate_chapter_vi_connector_factor_admissibility.py. -/
import PoincareChapterVI.ChapterVIDConnectorFactorBulkReference

namespace PoincareChapterVI.ChapterVIDConnectorFactorBulkReference

open ChapterVILeanCompCertBatch
open LeanCompCert.Ports.SignedProductClaims

set_option maxRecDepth 1000000 in
theorem shard_admissible_{side}_{index} :
    Admissible (batchClaims (referenceShardOperations .{side} ⟨{index}, by decide⟩)) := by
  refine ⟨?_, ?_, ?_⟩
  · decide +kernel
  · decide +kernel
  · decide +kernel

set_option maxRecDepth 1000000 in
theorem shard_allHold_{side}_{index} :
    ∀ claim ∈ batchClaims
      (referenceShardOperations .{side} ⟨{index}, by decide⟩), claim.Holds := by
  decide +kernel

end PoincareChapterVI.ChapterVIDConnectorFactorBulkReference
"""


def aggregate_text() -> str:
    imports = "\n".join(
        f"import PoincareChapterVI.ConnectorFactorAdmissibility.{side.capitalize()}{index}"
        for side in SIDES for index in range(SHARDS)
    )
    cases = []
    for side in SIDES:
        bullets = "\n".join(
            f"    · exact shard_admissible_{side}_{index}" for index in range(SHARDS)
        )
        cases.append(f"  | {side} =>\n    fin_cases shard\n{bullets}")
    case_text = "\n".join(cases)
    all_hold_text = case_text.replace("shard_admissible_", "shard_allHold_")
    return f"""/- This file is generated by research/generate_chapter_vi_connector_factor_admissibility.py. -/
{imports}

namespace PoincareChapterVI.ChapterVIDConnectorFactorBulkReference

open ChapterVILeanCompCertBatch
open LeanCompCert.Ports.SignedProductClaims

/-- Every 32-cell connector-factor artifact remains inside LeanCompCert's 64-bit fragment. -/
theorem shard_admissible (side : ChapterVIDOuterArcSide) (shard : Fin shardCount) :
    Admissible (batchClaims (referenceShardOperations side shard)) := by
  cases side with
{case_text}

/-- Every signed comparison in every connector-factor shard is proved by kernel reduction. -/
theorem shard_allHold (side : ChapterVIDOuterArcSide) (shard : Fin shardCount) :
    ∀ claim ∈ batchClaims (referenceShardOperations side shard), claim.Holds := by
  cases side with
{all_hold_text}

end PoincareChapterVI.ChapterVIDConnectorFactorBulkReference
"""


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    for side in SIDES:
        for index in range(SHARDS):
            (OUT / f"{side.capitalize()}{index}.lean").write_text(
                module_text(side, index)
            )
    (ROOT / "PoincareChapterVI" / "ChapterVIDConnectorFactorBulkAdmissibility.lean").write_text(
        aggregate_text()
    )


if __name__ == "__main__":
    main()
