#!/usr/bin/env python3
"""Generate independently buildable kernel admissibility checks for all polar shards."""

from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "PoincareChapterVI" / "PolarAdmissibility"
SIDES = ("initial", "final")


def module_text(side: str, index: int) -> str:
    return f"""/- This file is generated by research/generate_chapter_vi_polar_admissibility.py. -/
import PoincareChapterVI.ChapterVIDOuterArcPolarCompiledGrid

namespace PoincareChapterVI.ChapterVIDOuterArcPolarCompiledGrid

open ChapterVILeanCompCertBatch
open LeanCompCert.Ports.SignedProductClaims
open scoped unitInterval

set_option maxRecDepth 1000000 in
theorem shard_admissible_{side}_{index} :
    Admissible (batchClaims (shardOperations .{side} {index})) := by
  refine ⟨?_, ?_, ?_⟩
  · decide +kernel
  · decide +kernel
  · decide +kernel

end PoincareChapterVI.ChapterVIDOuterArcPolarCompiledGrid
"""


def aggregate_text() -> str:
    imports = "\n".join(
        f"import PoincareChapterVI.PolarAdmissibility.{side.capitalize()}{index}"
        for side in SIDES for index in range(28)
    )
    cases = []
    for side in SIDES:
        bullets = "\n".join(
            f"    · exact shard_admissible_{side}_{index}" for index in range(28)
        )
        cases.append(f"  | {side} =>\n    fin_cases i\n{bullets}")
    case_text = "\n".join(cases)
    return f"""/- This file is generated by research/generate_chapter_vi_polar_admissibility.py. -/
{imports}

namespace PoincareChapterVI.ChapterVIDOuterArcPolarCompiledGrid

open ChapterVILeanCompCertBatch
open LeanCompCert.Ports.SignedProductClaims
open scoped unitInterval

/-- Every compiled shard stays inside the unsigned 64-bit fragment used by LeanCompCert. -/
theorem shard_admissible (side : ChapterVIDOuterArcSide) (i : Fin 28) :
    Admissible (batchClaims (shardOperations side i)) := by
  cases side with
{case_text}

/-- The only external observation required by the compiled route: every emitted shard returned
the zero failure count.  Admissibility is proved above in Lean's kernel. -/
structure CompiledRunVerdict : Prop where
  returnsZero : ∀ side i,
    (batchComputation (shardArtifactName side i) (shardOperations side i)).Returns
      ((0 : Nat) : Int)

theorem CompiledRunVerdict.toCompiledVerdict (run : CompiledRunVerdict) : CompiledVerdict where
  shard side i := ⟨shard_admissible side i, run.returnsZero side i⟩

theorem radicand_re_pos_of_run (run : CompiledRunVerdict)
    (side : ChapterVIDOuterArcSide) (st : I × I) :
    0 < (chapterVIDOuterArcRadicand side st).re :=
  radicand_re_pos run.toCompiledVerdict side st

theorem radicand_ne_zero_of_run (run : CompiledRunVerdict)
    (side : ChapterVIDOuterArcSide) (st : I × I) :
    chapterVIDOuterArcRadicand side st ≠ 0 :=
  radicand_ne_zero run.toCompiledVerdict side st

theorem exists_squareRootSheet_of_run (run : CompiledRunVerdict)
    (side : ChapterVIDOuterArcSide) (base : I × I) (baseRoot : ℂ)
    (hbaseRoot : baseRoot ^ 2 = chapterVIDOuterArcRadicand side base) :
    ∃ sheet : ChapterVIContinuousSquareRootSheet (chapterVIDOuterArcRadicand side),
      sheet.root base = baseRoot :=
  exists_squareRootSheet run.toCompiledVerdict side base baseRoot hbaseRoot

end PoincareChapterVI.ChapterVIDOuterArcPolarCompiledGrid
"""


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    for side in SIDES:
        for index in range(28):
            (OUT / f"{side.capitalize()}{index}.lean").write_text(
                module_text(side, index)
            )
    aggregate = ROOT / "PoincareChapterVI" / "ChapterVIDOuterArcPolarAdmissibility.lean"
    aggregate.write_text(aggregate_text())


if __name__ == "__main__":
    main()
