#!/usr/bin/env python3
"""Generate independently buildable admissibility checks for homogeneous seam shards."""

from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "PoincareChapterVI" / "HomogeneousAdmissibility"
SIDES = ("initial", "final")
SHARDS = 16


def module_text(side: str, index: int) -> str:
    return f"""/- This file is generated by research/generate_chapter_vi_homogeneous_admissibility.py. -/
import PoincareChapterVI.ChapterVIDHomogeneousCompiledTable

namespace PoincareChapterVI.ChapterVIDHomogeneousCompiledTable

open ChapterVILeanCompCertBatch
open LeanCompCert.Ports.SignedProductClaims

set_option maxRecDepth 1000000 in
theorem shard_admissible_{side}_{index} :
    Admissible (batchClaims (shardOperations .{side} ⟨{index}, by decide⟩)) := by
  refine ⟨?_, ?_, ?_⟩
  · decide +kernel
  · decide +kernel
  · decide +kernel

set_option maxRecDepth 1000000 in
theorem shard_allHold_{side}_{index} :
    ∀ claim ∈ batchClaims (shardOperations .{side} ⟨{index}, by decide⟩), claim.Holds := by
  decide +kernel

end PoincareChapterVI.ChapterVIDHomogeneousCompiledTable
"""


def aggregate_text() -> str:
    imports = "\n".join(
        f"import PoincareChapterVI.HomogeneousAdmissibility.{side.capitalize()}{index}"
        for side in SIDES for index in range(SHARDS)
    )
    cases = []
    hold_cases = []
    for side in SIDES:
        bullets = "\n".join(
            f"    · exact shard_admissible_{side}_{index}" for index in range(SHARDS)
        )
        indented_bullets = "\n".join(f"  {line}" for line in bullets.splitlines())
        cases.append(f"    | {side} =>\n      fin_cases shard\n{indented_bullets}")
        hold_bullets = "\n".join(
            f"      · exact shard_allHold_{side}_{index}" for index in range(SHARDS)
        )
        hold_cases.append(f"    | {side} =>\n      fin_cases shard\n{hold_bullets}")
    return f"""/- This file is generated by research/generate_chapter_vi_homogeneous_admissibility.py. -/
{imports}

namespace PoincareChapterVI.ChapterVIDHomogeneousCompiledTable

open ChapterVILeanCompCertBatch
open LeanCompCert.Ports.SignedProductClaims

/-- Every ten-row homogeneous seam artifact remains inside LeanCompCert's 64-bit fragment. -/
theorem referenceAdmissibility : ReferenceAdmissibility where
  shard side shard := by
    cases side with
{chr(10).join(cases)}

/-- Every signed comparison in every reference artifact is proved by kernel reduction. -/
theorem referenceAllHold (side : ChapterVIDOuterArcSide) (shard : Fin 16) :
    ∀ claim ∈ batchClaims (shardOperations side shard), claim.Holds := by
  cases side with
{chr(10).join(hold_cases)}

/-- Unconditional verified-program verdict for the reference table.  The larger receipt interface
remains available for independently compiled/native reruns, but is not needed by this theorem. -/
theorem referenceRunVerdict : ReferenceRunVerdict referenceAdmissibility where
  returnsZero side shard :=
    ChapterVILeanCompCertIntervalBridge.returns_zero_of_allHold
      (shardArtifactName side shard) (batchClaims (shardOperations side shard))
      (referenceAdmissibility.shard side shard) (referenceAllHold side shard)

/-- The reference table and analytic selector unconditionally produce both collar derivative
certificates. -/
theorem exists_anchoredModel_with_referenceDerivativeCertificates
    (massProduct : ℂ) (b d : ℤ) :
    ∃ model : ChapterVIDAnchoredConnectorModel massProduct b d,
      ChapterVIDConnectorFactorCrossing.OrientedRealDerivativeCertificate
          model.toChapterVIDPrincipalConnectorModel .initial ∧
        ChapterVIDConnectorFactorCrossing.OrientedRealDerivativeCertificate
          model.toChapterVIDPrincipalConnectorModel .final :=
  exists_anchoredModel_with_orientedRealDerivativeCertificates
    referenceAdmissibility referenceRunVerdict massProduct b d

end PoincareChapterVI.ChapterVIDHomogeneousCompiledTable
"""


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    for side in SIDES:
        for index in range(SHARDS):
            (OUT / f"{side.capitalize()}{index}.lean").write_text(
                module_text(side, index)
            )
    (ROOT / "PoincareChapterVI" /
     "ChapterVIDHomogeneousAdmissibility.lean").write_text(aggregate_text())


if __name__ == "__main__":
    main()
