#!/usr/bin/env python3
"""Generate independently buildable admissibility checks for derivative shards."""

from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "PoincareChapterVI" / "ConnectorFactorDerivativeAdmissibility"
SHARDS = {"initial": 20, "final": 21}


def module_text(side: str, index: int) -> str:
    return f"""/- This file is generated by research/generate_chapter_vi_connector_factor_derivative_admissibility.py. -/
import PoincareChapterVI.ChapterVIDConnectorFactorDerivativeReference

namespace PoincareChapterVI.ChapterVIDConnectorFactorDerivativeReference

open ChapterVILeanCompCertBatch
open LeanCompCert.Ports.SignedProductClaims

set_option maxRecDepth 1000000 in
theorem shard_admissible_{side}_{index} :
    Admissible (batchClaims (shardOperations .{side} ⟨{index}, by decide⟩)) := by
  refine ⟨?_, ?_, ?_⟩
  · decide +kernel
  · decide +kernel
  · decide +kernel

end PoincareChapterVI.ChapterVIDConnectorFactorDerivativeReference
"""


def aggregate_text() -> str:
    imports = "\n".join(
        f"import PoincareChapterVI.ConnectorFactorDerivativeAdmissibility.{side.capitalize()}{index}"
        for side, count in SHARDS.items() for index in range(count)
    )
    cases = []
    for side, count in SHARDS.items():
        bullets = "\n".join(
            f"    · exact shard_admissible_{side}_{index}" for index in range(count)
        )
        cases.append(f"  | {side} =>\n    fin_cases shard\n{bullets}")
    case_text = "\n".join(cases)
    return f"""/- This file is generated by research/generate_chapter_vi_connector_factor_derivative_admissibility.py. -/
{imports}

namespace PoincareChapterVI.ChapterVIDConnectorFactorDerivativeReference

open ChapterVILeanCompCertBatch
open LeanCompCert.Ports.SignedProductClaims

/-- Every 12-cell derivative artifact remains inside LeanCompCert's 64-bit fragment. -/
theorem shard_admissible (side : ChapterVIDOuterArcSide)
    (shard : Fin (shardCount side)) :
    Admissible (batchClaims (shardOperations side shard)) := by
  cases side with
{case_text}

end PoincareChapterVI.ChapterVIDConnectorFactorDerivativeReference
"""


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    for side, count in SHARDS.items():
        for index in range(count):
            (OUT / f"{side.capitalize()}{index}.lean").write_text(
                module_text(side, index)
            )
    (ROOT / "PoincareChapterVI" /
     "ChapterVIDConnectorFactorDerivativeAdmissibility.lean").write_text(
        aggregate_text()
    )


if __name__ == "__main__":
    main()
