#!/usr/bin/env python3
"""Emit the compact 28-cell clustered radial grid.

Only root endpoint proposals and cell inputs are emitted.  All multiplication intermediates are
computed by untrusted proposal functions and independently checked by LeanCompCert.
"""

from fractions import Fraction

from chapter_vi_polar_interval_scan import Fixed, radial_data


P = 20
N = 28
fx = Fixed(P)


def iv(value: tuple[int, int]) -> str:
    return f"⟨{value[0]}, {value[1]}⟩"


def vector(name: str, values: list[tuple[int, int]]) -> str:
    body = ",\n  ".join(iv(value) for value in values)
    return (
        f"def {name}Data : Array Interval := #[\n  {body}]\n\n"
        f"def {name} (i : Fin {len(values)}) : Interval := {name}Data[i]\n"
    )


qd_lo = fx.rational(Fraction(8734, 10_000_000))[0]
qd_hi = fx.rational(Fraction(8736, 10_000_000))[1]
q_d = (qd_lo, qd_hi)
xabs_lo = fx.rational(Fraction(26_865_395, 1_000_000_000))[0]
xabs_hi = fx.rational(Fraction(26_865_396, 1_000_000_000))[1]
x_abs = (xabs_lo, xabs_hi)
qd_sixth = fx.root(q_d, 6)
collision = fx.root(x_abs, 3)
cells = [radial_data(fx, i, N, 3) for i in range(N)]

print("""/- This file is generated by research/generate_chapter_vi_clustered_radial_grid.py. -/
import PoincareChapterVI.ChapterVILeanCompCertProposals
import PoincareChapterVI.ChapterVINonuniformGrid

namespace PoincareChapterVI

open ChapterVILeanCompCertBatch
open LeanCompCert.Ports.SignedProductClaims
open scoped unitInterval

namespace ChapterVIDRadialClusteredCompiledGrid

abbrev Interval := ChapterVISignedDyadicInterval 20
""")
print(f"def qD : Interval := {iv(q_d)}")
print(f"def xAbs : Interval := {iv(x_abs)}")
print(f"def qDSixthRoot : Interval := {iv(qd_sixth)}")
print(f"def collisionRadius : Interval := {iv(collision)}")
print("""
def endpoint : ChapterVIDRadialTrace.EndpointTrace (precision := 20) :=
  ChapterVILeanCompCertProposals.radialEndpointTrace
    qD qDSixthRoot xAbs collisionRadius
""")
for field in ("input", "qCubeRoot", "qSixthRoot"):
    print(vector(field, [cell[field] for cell in cells]))
print("""
def trace (i : Fin 28) : ChapterVIDRadialTrace.Trace endpoint (input i) :=
  ChapterVILeanCompCertProposals.radialTrace endpoint (input i)
    (qCubeRoot i) (qSixthRoot i)

noncomputable def operations : List (DyadicOperation 20) :=
  endpoint.operations ++ (List.ofFn fun i : Fin 28 => (trace i).operations).flatten

theorem endpoint_operations_mem (operation : DyadicOperation 20)
    (hoperation : operation ∈ endpoint.operations) : operation ∈ operations := by
  simp [operations, hoperation]

theorem trace_operations_mem (i : Fin 28) (operation : DyadicOperation 20)
    (hoperation : operation ∈ (trace i).operations) : operation ∈ operations := by
  rw [operations]
  simp only [List.mem_append, List.mem_flatten]
  right
  exact ⟨(trace i).operations, List.mem_ofFn.mpr ⟨i, rfl⟩, hoperation⟩

theorem endpoint_valid : endpoint.Valid := by
  unfold ChapterVIDRadialTrace.EndpointTrace.Valid
    ChapterVILeanCompCertRoots.CubicRootTrace.Valid
    ChapterVILeanCompCertRoots.SixthRootTrace.Valid
  decide +kernel

theorem trace_valid (i : Fin 28) : (trace i).Valid := by
  unfold ChapterVIDRadialTrace.Trace.Valid
    ChapterVILeanCompCertRoots.CubicRootTrace.Valid
    ChapterVILeanCompCertRoots.SixthRootTrace.Valid
  fin_cases i <;> decide +kernel

set_option maxRecDepth 100000 in
theorem operations_admissible : Admissible (batchClaims operations) := by
  refine ⟨?_, ?_, ?_⟩
  · decide +kernel
  · decide +kernel
  · decide +kernel

set_option maxRecDepth 100000 in
theorem operations_returns_zero :
    (batchComputation "chapter-vi-d-radial-clustered-grid-20" operations).Returns
      ((0 : Nat) : Int) := by
  decide +kernel

theorem qD_contains : qD.Contains chapterVIDCriticalParameterModulus := by
  obtain ⟨hlower, hupper⟩ := chapterVIDCriticalParameterModulus_tight_bounds
  constructor
  · exact (by norm_num [qD, ChapterVISignedDyadicInterval.toRealInterval,
      ChapterVISignedDyadicInterval.scale] :
        ((qD.lower : ℝ) / ChapterVISignedDyadicInterval.scale 20) ≤ 8734 / 10000000).trans hlower
  · exact hupper.trans (by norm_num [qD, ChapterVISignedDyadicInterval.toRealInterval,
      ChapterVISignedDyadicInterval.scale] :
        (8736 / 10000000 : ℝ) ≤ (qD.upper : ℝ) / ChapterVISignedDyadicInterval.scale 20)

theorem xAbs_contains : xAbs.Contains (-chapterVIDRoot) := by
  constructor
  · change (28170 : ℝ) / (2 : ℝ) ^ 20 ≤ -chapterVIDRoot
    exact (by norm_num : (28170 : ℝ) / (2 : ℝ) ^ 20 ≤ 26865395 / 1000000000).trans
      (by linarith [chapterVIDRoot_fine_mem.2])
  · change -chapterVIDRoot ≤ (28171 : ℝ) / (2 : ℝ) ^ 20
    exact (by linarith [chapterVIDRoot_fine_mem.1] :
      -chapterVIDRoot ≤ 26865396 / 1000000000).trans (by norm_num)

theorem correction_contains :
    endpoint.correction.Contains chapterVIDCertificateContourCorrection := by
  apply endpoint.correction_contains_of_allSound endpoint_valid
  · intro operation hoperation
    exact allSound_of_returns_zero "chapter-vi-d-radial-clustered-grid-20"
      operations operations_admissible operations_returns_zero operation
      (endpoint_operations_mem operation hoperation)
  · exact qD_contains
  · exact xAbs_contains

theorem input_contains_of_mem_cell (i : Fin 28) {parameter : I}
    (hlower : (chapterVICubicClusterNode 28 i : ℝ) ≤ parameter)
    (hupper : (parameter : ℝ) ≤ chapterVICubicClusterNode 28 (i + 1)) :
    (input i).Contains (parameter : ℝ) := by
  fin_cases i <;>
    norm_num [input, inputData, chapterVICubicClusterNode,
      ChapterVISignedDyadicInterval.Contains,
      ChapterVISignedDyadicInterval.toRealInterval,
      ChapterVISignedDyadicInterval.scale] at hlower hupper ⊢ <;>
    constructor <;> linarith

theorem outputs_contain_cell (i : Fin 28) {parameter : I}
    (hlower : (chapterVICubicClusterNode 28 i : ℝ) ≤ parameter)
    (hupper : (parameter : ℝ) ≤ chapterVICubicClusterNode 28 (i + 1)) :
    (trace i).qCubeRoot.Contains
        (chapterVIDCertificateParameter parameter ^ ((3 : ℝ)⁻¹)) ∧
      (trace i).radius.Contains (chapterVIDCertificateContourRadius parameter) := by
  apply (trace i).outputs_contain_of_allSound (trace_valid i)
  · intro operation hoperation
    exact allSound_of_returns_zero "chapter-vi-d-radial-clustered-grid-20"
      operations operations_admissible operations_returns_zero operation
      (trace_operations_mem i operation hoperation)
  · exact input_contains_of_mem_cell i hlower hupper
  · exact qD_contains
  · exact correction_contains

theorem exists_outputs_contain (parameter : I) :
    ∃ i : Fin 28,
      (trace i).qCubeRoot.Contains
          (chapterVIDCertificateParameter parameter ^ ((3 : ℝ)⁻¹)) ∧
        (trace i).radius.Contains (chapterVIDCertificateContourRadius parameter) := by
  rcases exists_mem_cubicClusterCell 28 (by norm_num) parameter with
    ⟨i, hi, hlower, hupper⟩
  exact ⟨⟨i, hi⟩, outputs_contain_cell ⟨i, hi⟩ hlower hupper⟩

end ChapterVIDRadialClusteredCompiledGrid

end PoincareChapterVI
""")
