#!/usr/bin/env python3
"""Generate small kernel-reduced shards for the radial-tail interval tables."""

from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
LEAN = ROOT / "PoincareChapterVI"


def write(path: Path, body: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(body)


def fin(value: int, bound: int) -> str:
    return f"(⟨{value}, by decide⟩ : Fin {bound})"


def centered_shards() -> None:
    directory = LEAN / "RadialTailCenteredKernel"
    for old in directory.glob("*.lean"):
        old.unlink()
    aggregate_imports = []
    theorem_names = {"program": {}, "output": {}, "argument": {}}
    for side in ("upper", "lower"):
        for row in range(6):
            angular_cells = 128 if side == "lower" and row < 2 else 64
            for radial in range(16):
                suffix = f"{side}_{row}_{radial}"
                names = {
                    "program": f"program_valid_{suffix}",
                    "output": f"output_negative_{suffix}",
                    "argument": f"argument_bound_{suffix}",
                }
                for kind, name in names.items():
                    theorem_names[kind][side, row, radial] = name
                chunk_imports = []
                chunk_size = 16
                chunk_count = angular_cells // chunk_size
                for kind in ("program", "output", "argument"):
                    for chunk in range(chunk_count):
                        stem = f"{side.capitalize()}{row}_{radial}_{kind.capitalize()}{chunk}"
                        module = f"PoincareChapterVI.RadialTailCenteredKernel.{stem}"
                        chunk_imports.append(module)
                        offset = chunk * chunk_size
                        angular = f"(⟨{offset} + index.val, by omega⟩ : Fin {angular_cells})"
                        if kind == "program":
                            proposition = f"""ProgramValid
        (inputs .{side} {fin(row, 6)} {fin(radial, 16)} {angular})
        (ChapterVIDRadialTailBaseCenteredProgram.program .{side}) = true"""
                        elif kind == "output":
                            proposition = f"""(cellOutput .{side} {fin(row, 6)} {fin(radial, 16)}
        {angular}).real.upper < 0"""
                        else:
                            proposition = f"""ChapterVILeanCompCertProposals.componentBudget
          (cellArgument .{side} {fin(row, 6)} {fin(radial, 16)} {angular}).real +
        ChapterVILeanCompCertProposals.componentBudget
          (cellArgument .{side} {fin(row, 6)} {fin(radial, 16)} {angular}).imag ≤
        366503875925"""
                        chunk_body = f"""/- This file is generated by research/generate_radial_tail_kernel_shards.py. -/
import PoincareChapterVI.ChapterVIDRadialTailCenteredCompiledGrid

namespace PoincareChapterVI.ChapterVIDRadialTailCenteredCompiledGrid

open ChapterVILeanCompCertBatch
open ChapterVILeanCompCertAffineTrace
open ChapterVIDRadialTailCellInputTrace

set_option maxRecDepth 1000000
set_option maxHeartbeats 0

theorem {kind}_{suffix}_{chunk} (index : Fin {chunk_size}) :
    {proposition} := by
  revert index
  decide +kernel

end PoincareChapterVI.ChapterVIDRadialTailCenteredCompiledGrid
"""
                        write(directory / f"{stem}.lean", chunk_body)

                def angular_dispatch(kind: str) -> str:
                    lines = ["  intro angular", "  fin_cases angular"]
                    for angular_value in range(angular_cells):
                        chunk = angular_value // chunk_size
                        local = angular_value % chunk_size
                        lines.append(
                            f"  · exact {kind}_{suffix}_{chunk} {fin(local, chunk_size)}"
                        )
                    return "\n".join(lines)

                radial_module = f"PoincareChapterVI.RadialTailCenteredKernel.{side.capitalize()}{row}_{radial}"
                aggregate_imports.append(radial_module)
                radial_body = "\n".join(f"import {module}" for module in chunk_imports) + f"""

namespace PoincareChapterVI.ChapterVIDRadialTailCenteredCompiledGrid

open ChapterVILeanCompCertAffineTrace
open ChapterVIDRadialTailCellInputTrace

theorem {names['program']} : ∀ angular : Fin {angular_cells},
    ProgramValid (inputs .{side} {fin(row, 6)} {fin(radial, 16)} angular)
      (ChapterVIDRadialTailBaseCenteredProgram.program .{side}) = true := by
{angular_dispatch('program')}

theorem {names['output']} : ∀ angular : Fin {angular_cells},
    (cellOutput .{side} {fin(row, 6)} {fin(radial, 16)} angular).real.upper < 0 := by
{angular_dispatch('output')}

theorem {names['argument']} : ∀ angular : Fin {angular_cells},
    ChapterVILeanCompCertProposals.componentBudget
        (cellArgument .{side} {fin(row, 6)} {fin(radial, 16)} angular).real +
      ChapterVILeanCompCertProposals.componentBudget
        (cellArgument .{side} {fin(row, 6)} {fin(radial, 16)} angular).imag ≤
      366503875925 := by
{angular_dispatch('argument')}

end PoincareChapterVI.ChapterVIDRadialTailCenteredCompiledGrid
"""
                write(directory / f"{side.capitalize()}{row}_{radial}.lean", radial_body)

    def dispatch(kind: str) -> str:
        lines = ["  intro side row radial angular", "  cases side with"]
        for side in ("upper", "lower"):
            lines.append(f"  | {side} =>")
            lines.append("      fin_cases row <;> fin_cases radial")
            for row in range(6):
                for radial in range(16):
                    name = theorem_names[kind][side, row, radial]
                    lines.append(f"      · exact {name} angular")
        return "\n".join(lines)

    aggregate = "/- This file is generated by research/generate_radial_tail_kernel_shards.py. -/\n" + \
        "\n".join(f"import {module}" for module in aggregate_imports) + f"""

/-! Kernel-reduced aggregate of the 192 centered radial shards. -/

namespace PoincareChapterVI

open ChapterVILeanCompCertBatch
open ChapterVILeanCompCertAffineTrace

namespace ChapterVIDRadialTailCenteredCompiledGrid

open ChapterVIDRadialTailCellInputTrace

set_option maxRecDepth 1000000
set_option maxHeartbeats 0

theorem all_program_valid :
    ∀ side row radial angular,
      ProgramValid (inputs side row radial angular)
        (ChapterVIDRadialTailBaseCenteredProgram.program side) = true := by
{dispatch('program')}

/-- Every outward-rounded operation in all 14,336 cells is mathematically sound. -/
theorem all_operations_sound :
    ∀ side row radial angular operation,
      operation ∈ cellOperations side row radial angular → operation.Sound := by
  intro side row radial angular
  exact proposeProgram_operations_sound _ _
    (all_program_valid side row radial angular)

theorem all_output_upper_negative :
    ∀ side row radial angular,
      (cellOutput side row radial angular).real.upper < 0 := by
{dispatch('output')}

theorem all_argument_l1_bound :
    ∀ side row radial angular,
      ChapterVILeanCompCertProposals.componentBudget
          (cellArgument side row radial angular).real +
        ChapterVILeanCompCertProposals.componentBudget
          (cellArgument side row radial angular).imag ≤ 366503875925 := by
{dispatch('argument')}

end ChapterVIDRadialTailCenteredCompiledGrid
end PoincareChapterVI
"""
    write(LEAN / "ChapterVIDRadialTailCenteredKernel.lean", aggregate)


def endpoint_shards() -> None:
    directory = LEAN / "RadialTailEndpointKernel"
    imports = []

    for side, cells in (("upper", 64), ("lower", 128)):
        for angular in range(cells):
            module = f"PoincareChapterVI.RadialTailEndpointKernel.Direct{side.capitalize()}{angular}"
            imports.append(module)
            positive = side == "upper" and angular < 62 or side == "lower" and angular >= 4
            positive_theorem = ""
            if positive:
                positive_theorem = f"""
theorem direct_positive_{side}_{angular} :
    0 < (directOutput .{side} {fin(angular, cells)}).real.lower := by
  decide +kernel
"""
            body = f"""/- This file is generated by research/generate_radial_tail_kernel_shards.py. -/
import PoincareChapterVI.ChapterVIDRadialTailEndpointCompiledGrid

namespace PoincareChapterVI.ChapterVIDRadialTailEndpointCompiledGrid

open ChapterVIFieldExpression Expr
open ChapterVILeanCompCertAffineTrace

set_option maxRecDepth 1000000
set_option maxHeartbeats 0

theorem direct_program_valid_{side}_{angular} :
    ProgramValid (directInputs .{side} {fin(angular, cells)})
      (ChapterVIDRadialTailBaseCenteredProgram.program .{side}) = true := by
  decide +kernel
{positive_theorem}
end PoincareChapterVI.ChapterVIDRadialTailEndpointCompiledGrid
"""
            write(directory / f"Direct{side.capitalize()}{angular}.lean", body)

    for k in range(63):
        module = f"PoincareChapterVI.RadialTailEndpointKernel.UpperLocal{k}"
        imports.append(module)
        body = f"""/- This file is generated by research/generate_radial_tail_kernel_shards.py. -/
import PoincareChapterVI.ChapterVIDRadialTailEndpointCompiledGrid

namespace PoincareChapterVI.ChapterVIDRadialTailEndpointCompiledGrid

open ChapterVIFieldExpression Expr
open ChapterVILeanCompCertAffineTrace
open ChapterVIDRadialTailEndpointTrace

set_option maxRecDepth 1000000
set_option maxHeartbeats 0

theorem upper_base_program_valid_{k} :
    ProgramValid (endpointInputsFromT .upper
      (rationalTModel (upperLocalStart {fin(k, 63)}) (upperLocalEnd {fin(k, 63)})))
      (ChapterVIDRadialTailBaseCenteredProgram.program .upper) = true := by
  decide +kernel

theorem upper_velocity_trace_valid_{k} : ∀ i,
    TraceValid (boxesFromT .upper
      (rationalTModel (upperLocalStart {fin(k, 63)}) (upperLocalEnd {fin(k, 63)})))
      (velocity .upper i) = true := by
  intro i
  fin_cases i <;> decide +kernel

theorem upper_curvature_jet_valid_{k} :
    JetTraceValid (boxesFromT .upper
      (rationalTModel (upperLocalStart {fin(k, 63)}) (upperLocalEnd {fin(k, 63)})))
      (velocityBoxesFromT .upper
        (rationalTModel (upperLocalStart {fin(k, 63)}) (upperLocalEnd {fin(k, 63)})))
      (firstDerivative .upper) = true := by
  decide +kernel

theorem upper_curvature_positive_{k} :
    0 < (secondJetFromT .upper (upperLocalStart {fin(k, 63)})
      (upperLocalEnd {fin(k, 63)})).derivative.real.lower := by
  decide +kernel

end PoincareChapterVI.ChapterVIDRadialTailEndpointCompiledGrid
"""
        write(directory / f"UpperLocal{k}.lean", body)

    imports.append("PoincareChapterVI.RadialTailEndpointKernel.LowerLocal")
    lower = """/- This file is generated by research/generate_radial_tail_kernel_shards.py. -/
import PoincareChapterVI.ChapterVIDRadialTailEndpointCompiledGrid

namespace PoincareChapterVI.ChapterVIDRadialTailEndpointCompiledGrid

open ChapterVIFieldExpression Expr
open ChapterVILeanCompCertAffineTrace
open ChapterVIDRadialTailEndpointTrace

set_option maxRecDepth 1000000
set_option maxHeartbeats 0

theorem lower_base_program_valid :
    ProgramValid (endpointInputsFromT .lower (rationalTModel 0 (1 / 1024)))
      (ChapterVIDRadialTailBaseCenteredProgram.program .lower) = true := by
  decide +kernel

theorem lower_velocity_trace_valid : ∀ i,
    TraceValid (boxesFromT .lower (rationalTModel 0 (1 / 1024)))
      (velocity .lower i) = true := by
  intro i
  fin_cases i <;> decide +kernel

theorem lower_curvature_jet_valid :
    JetTraceValid (boxesFromT .lower (rationalTModel 0 (1 / 1024)))
      (velocityBoxesFromT .lower (rationalTModel 0 (1 / 1024)))
      (firstDerivative .lower) = true := by
  decide +kernel

theorem lower_curvature_positive :
    0 < (secondJetFromT .lower 0 (1 / 1024)).derivative.real.lower := by
  decide +kernel

end PoincareChapterVI.ChapterVIDRadialTailEndpointCompiledGrid
"""
    write(directory / "LowerLocal.lean", lower)

    def bullets(names: list[str], indent: str = "  ") -> str:
        return "\n".join(f"{indent}· exact {name}" for name in names)

    direct_dispatch = ["  intro side angular", "  cases side with", "  | upper =>", "      fin_cases angular"]
    direct_dispatch += [f"      · exact direct_program_valid_upper_{i}" for i in range(64)]
    direct_dispatch += ["  | lower =>", "      fin_cases angular"]
    direct_dispatch += [f"      · exact direct_program_valid_lower_{i}" for i in range(128)]

    def upper_dispatch(prefix: str, applied: str = "") -> str:
        names = [f"{prefix}_{i}{applied}" for i in range(63)]
        return "\n".join(["  intro k", "  fin_cases k", bullets(names)])

    aggregate = "/- This file is generated by research/generate_radial_tail_kernel_shards.py. -/\n" + \
        "\n".join(f"import {module}" for module in imports) + f"""

/-! Kernel-reduced aggregate of the endpoint direct and curvature shards. -/

namespace PoincareChapterVI
namespace ChapterVIDRadialTailEndpointCompiledGrid

open ChapterVIFieldExpression Expr
open ChapterVILeanCompCertAffineTrace
open ChapterVIDRadialTailBaseCenteredAffineTrace
open ChapterVIDRadialTailCellInputTrace
open ChapterVIDRadialTailEndpointTrace

set_option maxRecDepth 1000000
set_option maxHeartbeats 0

theorem direct_program_valid : ∀ side angular,
    ProgramValid (directInputs side angular)
      (ChapterVIDRadialTailBaseCenteredProgram.program side) = true := by
{chr(10).join(direct_dispatch)}

theorem direct_program_operations_sound : ∀ side angular operation,
    operation ∈ (ChapterVIDRadialTailBaseCenteredAffineTrace.trace side
      (directInputs side angular)).operations → operation.Sound := by
  intro side angular
  exact proposeProgram_operations_sound _ _ (direct_program_valid side angular)

theorem direct_product_operations_sound : ∀ side angular operation,
    operation ∈ (directProductTrace side angular).operations → operation.Sound := by
  intro side angular
  exact proposeMul_operations_sound _ _

theorem upper_direct_positive : ∀ i : Fin 62,
    0 < (directOutput .upper ⟨i, by simp [angularCells]; omega⟩).real.lower := by
  intro i
  fin_cases i
{bullets([f'direct_positive_upper_{i}' for i in range(62)])}

theorem lower_direct_positive : ∀ i : Fin 124,
    0 < (directOutput .lower ⟨i + 4, by simp [angularCells]; omega⟩).real.lower := by
  intro i
  fin_cases i
{bullets([f'direct_positive_lower_{i}' for i in range(4, 128)])}

theorem upper_base_program_valid : ∀ k : Fin 63,
    ProgramValid (endpointInputsFromT .upper
      (rationalTModel (upperLocalStart k) (upperLocalEnd k)))
      (ChapterVIDRadialTailBaseCenteredProgram.program .upper) = true := by
{upper_dispatch('upper_base_program_valid')}

theorem upper_velocity_trace_valid : ∀ k : Fin 63, ∀ i,
    TraceValid (boxesFromT .upper
      (rationalTModel (upperLocalStart k) (upperLocalEnd k)))
      (velocity .upper i) = true := by
  intro k
  fin_cases k
{bullets([f'exact upper_velocity_trace_valid_{i}' for i in range(63)]).replace('exact exact ', 'exact ')}

theorem upper_curvature_jet_valid : ∀ k : Fin 63,
    JetTraceValid (boxesFromT .upper
      (rationalTModel (upperLocalStart k) (upperLocalEnd k)))
      (velocityBoxesFromT .upper
        (rationalTModel (upperLocalStart k) (upperLocalEnd k)))
      (firstDerivative .upper) = true := by
{upper_dispatch('upper_curvature_jet_valid')}

theorem upper_base_operations_sound (k : Fin 63) (operation) :
    operation ∈ (ChapterVIDRadialTailBaseCenteredAffineTrace.trace .upper
      (endpointInputsFromT .upper
        (rationalTModel (upperLocalStart k) (upperLocalEnd k)))).operations →
      operation.Sound :=
  proposeProgram_operations_sound _ _ (upper_base_program_valid k) operation

theorem lower_base_operations_sound (operation) :
    operation ∈ (ChapterVIDRadialTailBaseCenteredAffineTrace.trace .lower
      (endpointInputsFromT .lower (rationalTModel 0 (1 / 1024)))).operations →
      operation.Sound :=
  proposeProgram_operations_sound _ _ lower_base_program_valid operation

theorem upper_velocity_operations_sound (k : Fin 63) (i) (operation) :
    operation ∈ (proposeTrace (boxesFromT .upper
      (rationalTModel (upperLocalStart k) (upperLocalEnd k)))
      (velocity .upper i)).operations → operation.Sound :=
  proposeTrace_operations_sound _ _ (upper_velocity_trace_valid k i) operation

theorem lower_velocity_operations_sound (i) (operation) :
    operation ∈ (proposeTrace (boxesFromT .lower (rationalTModel 0 (1 / 1024)))
      (velocity .lower i)).operations → operation.Sound :=
  proposeTrace_operations_sound _ _ (lower_velocity_trace_valid i) operation

theorem upper_curvature_operations_sound (k : Fin 63) (operation) :
    operation ∈ (secondJetFromT .upper
      (upperLocalStart k) (upperLocalEnd k)).operations → operation.Sound := by
  simpa [secondJetFromT] using
    proposeJetTrace_operations_sound _ _ _ (upper_curvature_jet_valid k) operation

theorem lower_curvature_operations_sound (operation) :
    operation ∈ (secondJetFromT .lower 0 (1 / 1024)).operations → operation.Sound := by
  simpa [secondJetFromT] using
    proposeJetTrace_operations_sound _ _ _ lower_curvature_jet_valid operation

theorem upper_curvature_positive : ∀ i : Fin 63,
    0 < (secondJetFromT .upper (upperLocalStart i) (upperLocalEnd i)).derivative.real.lower := by
{upper_dispatch('upper_curvature_positive')}

end ChapterVIDRadialTailEndpointCompiledGrid
end PoincareChapterVI
"""
    write(LEAN / "ChapterVIDRadialTailEndpointKernel.lean", aggregate)


if __name__ == "__main__":
    centered_shards()
    endpoint_shards()
