#!/usr/bin/env python3
"""Generate independently buildable admissibility checks for second-derivative shards."""

from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "PoincareChapterVI" / "ConnectorFactorSecondDerivativeAdmissibility"
SHARDS = {"initial": 7, "final": 3}
NAMESPACE = (
    "PoincareChapterVI."
    "ChapterVIDConnectorFactorSecondDerivativeReference"
)


def module_text(side: str, index: int) -> str:
    return f"""/- This file is generated by research/generate_chapter_vi_connector_factor_second_derivative_admissibility.py. -/
import PoincareChapterVI.ChapterVIDConnectorFactorSecondDerivativeReference

namespace {NAMESPACE}

open ChapterVILeanCompCertBatch
open LeanCompCert.Ports.SignedProductClaims

set_option maxRecDepth 1000000 in
theorem shard_admissible_{side}_{index} :
    Admissible (batchClaims (shardOperations .{side} ⟨{index}, by decide⟩)) := by
  refine ⟨?_, ?_, ?_⟩
  · decide +kernel
  · decide +kernel
  · decide +kernel

end {NAMESPACE}
"""


def aggregate_text() -> str:
    imports = "\n".join(
        "import PoincareChapterVI."
        f"ConnectorFactorSecondDerivativeAdmissibility.{side.capitalize()}{index}"
        for side, count in SHARDS.items()
        for index in range(count)
    )
    cases = []
    for side, count in SHARDS.items():
        bullets = "\n".join(
            f"    · exact shard_admissible_{side}_{index}"
            for index in range(count)
        )
        cases.append(f"  | {side} =>\n    fin_cases shard\n{bullets}")
    return f"""/- This file is generated by research/generate_chapter_vi_connector_factor_second_derivative_admissibility.py. -/
{imports}

namespace {NAMESPACE}

open ChapterVILeanCompCertBatch
open LeanCompCert.Ports.SignedProductClaims

/-- Every three-cell curvature artifact remains inside LeanCompCert's 64-bit fragment. -/
theorem shard_admissible (side : ChapterVIDOuterArcSide)
    (shard : Fin (shardCount side)) :
    Admissible (batchClaims (shardOperations side shard)) := by
  cases side with
{chr(10).join(cases)}

end {NAMESPACE}
"""


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    for side, count in SHARDS.items():
        for index in range(count):
            (OUT / f"{side.capitalize()}{index}.lean").write_text(
                module_text(side, index)
            )
    (ROOT / "PoincareChapterVI" /
     "ChapterVIDConnectorFactorSecondDerivativeAdmissibility.lean").write_text(
        aggregate_text()
    )


if __name__ == "__main__":
    main()
