/- This file is generated by research/generate_radial_tail_kernel_shards.py. -/
import PoincareChapterVI.ChapterVIDRadialTailCenteredCompiledGrid

namespace PoincareChapterVI.ChapterVIDRadialTailCenteredCompiledGrid

open ChapterVILeanCompCertBatch
open ChapterVILeanCompCertAffineTrace
open ChapterVIDRadialTailCellInputTrace

set_option maxRecDepth 1000000
set_option maxHeartbeats 0

theorem argument_lower_1_9_6 (index : Fin 16) :
    ChapterVILeanCompCertProposals.componentBudget
          (cellArgument .lower (⟨1, by decide⟩ : Fin 6) (⟨9, by decide⟩ : Fin 16) (⟨96 + index.val, by omega⟩ : Fin 128)).real +
        ChapterVILeanCompCertProposals.componentBudget
          (cellArgument .lower (⟨1, by decide⟩ : Fin 6) (⟨9, by decide⟩ : Fin 16) (⟨96 + index.val, by omega⟩ : Fin 128)).imag ≤
        366503875925 := by
  revert index
  decide +kernel

end PoincareChapterVI.ChapterVIDRadialTailCenteredCompiledGrid
