/- This file is generated by research/generate_radial_tail_kernel_shards.py. -/
import PoincareChapterVI.ChapterVIDRadialTailCenteredCompiledGrid

namespace PoincareChapterVI.ChapterVIDRadialTailCenteredCompiledGrid

open ChapterVILeanCompCertBatch
open ChapterVILeanCompCertAffineTrace
open ChapterVIDRadialTailCellInputTrace

set_option maxRecDepth 1000000
set_option maxHeartbeats 0

theorem program_lower_5_2_2 (index : Fin 16) :
    ProgramValid
        (inputs .lower (⟨5, by decide⟩ : Fin 6) (⟨2, by decide⟩ : Fin 16) (⟨32 + index.val, by omega⟩ : Fin 64))
        (ChapterVIDRadialTailBaseCenteredProgram.program .lower) = true := by
  revert index
  decide +kernel

end PoincareChapterVI.ChapterVIDRadialTailCenteredCompiledGrid
