/- This file is generated by research/generate_radial_tail_kernel_shards.py. -/
import PoincareChapterVI.ChapterVIDRadialTailCenteredCompiledGrid

namespace PoincareChapterVI.ChapterVIDRadialTailCenteredCompiledGrid

open ChapterVILeanCompCertBatch
open ChapterVILeanCompCertAffineTrace
open ChapterVIDRadialTailCellInputTrace

set_option maxRecDepth 1000000
set_option maxHeartbeats 0

theorem output_lower_1_7_5 (index : Fin 16) :
    (cellOutput .lower (⟨1, by decide⟩ : Fin 6) (⟨7, by decide⟩ : Fin 16)
        (⟨80 + index.val, by omega⟩ : Fin 128)).real.upper < 0 := by
  revert index
  decide +kernel

end PoincareChapterVI.ChapterVIDRadialTailCenteredCompiledGrid
