/- This file is generated by research/generate_radial_tail_kernel_shards.py. -/
import PoincareChapterVI.ChapterVIDRadialTailCenteredCompiledGrid

namespace PoincareChapterVI.ChapterVIDRadialTailCenteredCompiledGrid

open ChapterVILeanCompCertBatch
open ChapterVILeanCompCertAffineTrace
open ChapterVIDRadialTailCellInputTrace

set_option maxRecDepth 1000000
set_option maxHeartbeats 0

theorem output_upper_0_14_3 (index : Fin 16) :
    (cellOutput .upper (⟨0, by decide⟩ : Fin 6) (⟨14, by decide⟩ : Fin 16)
        (⟨48 + index.val, by omega⟩ : Fin 64)).real.upper < 0 := by
  revert index
  decide +kernel

end PoincareChapterVI.ChapterVIDRadialTailCenteredCompiledGrid
