/- This file is generated by research/generate_radial_tail_kernel_shards.py. -/
import PoincareChapterVI.ChapterVIDRadialTailCenteredCompiledGrid

namespace PoincareChapterVI.ChapterVIDRadialTailCenteredCompiledGrid

open ChapterVILeanCompCertBatch
open ChapterVILeanCompCertAffineTrace
open ChapterVIDRadialTailCellInputTrace

set_option maxRecDepth 1000000
set_option maxHeartbeats 0

theorem argument_upper_0_10_1 (index : Fin 16) :
    ChapterVILeanCompCertProposals.componentBudget
          (cellArgument .upper (⟨0, by decide⟩ : Fin 6) (⟨10, by decide⟩ : Fin 16) (⟨16 + index.val, by omega⟩ : Fin 64)).real +
        ChapterVILeanCompCertProposals.componentBudget
          (cellArgument .upper (⟨0, by decide⟩ : Fin 6) (⟨10, by decide⟩ : Fin 16) (⟨16 + index.val, by omega⟩ : Fin 64)).imag ≤
        366503875925 := by
  revert index
  decide +kernel

end PoincareChapterVI.ChapterVIDRadialTailCenteredCompiledGrid
