import PoincareChapterVI

/-! Kernel trust audit for the principal exported results. -/

#print axioms PoincareChapterVI.classicalPlanarRestrictedThreeBodyNonintegrability
#print axioms PoincareChapterVI.chapterVISection103_affineCoefficient_eq_gaussian
#print axioms PoincareChapterVI.chapterVIRuppertInverse_mul_minor
#print axioms PoincareChapterVI.chapterVIRuppertGaussianMinor_det_ne_zero
#print axioms PoincareChapterVI.chapterVIComplexRuppertMatrix_mulVec_eq_zero
#print axioms PoincareChapterVI.chapterVI_encodedRuppertKernel_trivial
#print axioms PoincareChapterVI.chapterVI_boundedRuppertKernel_trivial
#print axioms PoincareChapterVI.chapterVI_normalizedFactor_components_eq_zero
#print axioms PoincareChapterVI.chapterVI_gaussianResultant_ne_zero
#print axioms PoincareChapterVI.chapterVI_fractionPolynomial_isCoprime_derivative
#print axioms PoincareChapterVI.chapterVI_section103AffinePolynomial_irreducible
#print axioms PoincareChapterVI.chapterVI_section103ProjectivePolynomial_irreducible
#print axioms PoincareChapterVI.chapterVISection103_no_projective_infinitesimal_rotation
