import PoincareChapterVI

/-! Kernel trust audit for the principal exported results. -/

#print axioms PoincareChapterVI.classicalPlanarRestrictedThreeBodyNonintegrability
#print axioms PoincareChapterVI.chapterVISection103_affineCoefficient_eq_gaussian
#print axioms PoincareChapterVI.chapterVIRuppertInverse_mul_minor
#print axioms PoincareChapterVI.chapterVIRuppertGaussianMinor_det_ne_zero
#print axioms PoincareChapterVI.chapterVIComplexRuppertMatrix_mulVec_eq_zero
#print axioms PoincareChapterVI.chapterVI_encodedRuppertKernel_trivial
#print axioms PoincareChapterVI.chapterVI_boundedRuppertKernel_trivial
#print axioms PoincareChapterVI.chapterVI_normalizedFactor_components_eq_zero
#print axioms PoincareChapterVI.chapterVI_gaussianResultant_ne_zero
#print axioms PoincareChapterVI.chapterVI_fractionPolynomial_isCoprime_derivative
#print axioms PoincareChapterVI.chapterVI_section103AffinePolynomial_irreducible
#print axioms PoincareChapterVI.chapterVI_section103ProjectivePolynomial_irreducible
#print axioms PoincareChapterVI.chapterVI_section103Projective_reduced_isRelPrime
#print axioms PoincareChapterVI.Section103Source.chapterVISection103_reducedSource_eq_projectivePolynomial
#print axioms PoincareChapterVI.chapterVI_section103OriginReducedTangentLine_not_dvd_sexticTangentCone
#print axioms PoincareChapterVI.chapterVI_section103XInfinitySextic_hasInitialDegree_two
#print axioms PoincareChapterVI.chapterVI_section103XInfinityReduced_hasInitialDegree_three
#print axioms PoincareChapterVI.Section103Resultant.chapterVI_xInfinitySylvester_coeff_below_eight
#print axioms PoincareChapterVI.Section103Resultant.chapterVI_xInfinitySylvester_coeff_eight
#print axioms PoincareChapterVI.Section103Resultant.chapterVI_yInfinitySylvester_coeff_below_eight
#print axioms PoincareChapterVI.Section103Resultant.chapterVI_yInfinitySylvester_coeff_eight
#print axioms PoincareChapterVI.Section103Resultant.xChartResultant_natTrailingDegree
#print axioms PoincareChapterVI.Section103Resultant.yChartResultant_natTrailingDegree
#print axioms PoincareChapterVI.Section103Resultant.xGeometricChartResultant_natTrailingDegree
#print axioms PoincareChapterVI.Section103Resultant.yGeometricChartResultant_natTrailingDegree
#print axioms PoincareChapterVI.chapterVI_origin_localIntersectionIdeal_eq
#print axioms PoincareChapterVI.chapterVIOriginLocalIntersectionMultiplicity_eq_two
#print axioms PoincareChapterVI.TriangularAlgebra.finrank_eq_eight
#print axioms PoincareChapterVI.TriangularAlgebra.Z_pow_six
#print axioms PoincareChapterVI.TriangularAlgebra.Y_sq
#print axioms PoincareChapterVI.TriangularAlgebra.Y_mul_Z_sq
#print axioms PoincareChapterVI.TriangularAlgebra.pow_six_eq_zero_of_coeff_zero
#print axioms PoincareChapterVI.TriangularAlgebra.isUnit_iff_coeff_zero_ne
#print axioms PoincareChapterVI.InfinityLocalModel.localModelIdeal_le_ker
#print axioms PoincareChapterVI.InfinityLocalModel.localModelIdeal_quotient_length_eq_eight
#print axioms PoincareChapterVI.InfinityChartNormalForm.chapterVI_xInfinity_localIntersectionIdeal_eq_localModelIdeal
#print axioms PoincareChapterVI.InfinityChartNormalForm.chapterVI_yInfinity_localIntersectionIdeal_eq_localModelIdeal
#print axioms PoincareChapterVI.InfinityChartNormalForm.chapterVIXInfinityLocalIntersectionMultiplicity_eq_eight
#print axioms PoincareChapterVI.InfinityChartNormalForm.chapterVIYInfinityLocalIntersectionMultiplicity_eq_eight
#print axioms PoincareChapterVI.chapterVISection103_no_projective_infinitesimal_rotation
