/- This file is generated by research/generate_chapter_vi_polar_admissibility.py. -/
import PoincareChapterVI.PolarAdmissibility.Initial0
import PoincareChapterVI.PolarAdmissibility.Initial1
import PoincareChapterVI.PolarAdmissibility.Initial2
import PoincareChapterVI.PolarAdmissibility.Initial3
import PoincareChapterVI.PolarAdmissibility.Initial4
import PoincareChapterVI.PolarAdmissibility.Initial5
import PoincareChapterVI.PolarAdmissibility.Initial6
import PoincareChapterVI.PolarAdmissibility.Initial7
import PoincareChapterVI.PolarAdmissibility.Initial8
import PoincareChapterVI.PolarAdmissibility.Initial9
import PoincareChapterVI.PolarAdmissibility.Initial10
import PoincareChapterVI.PolarAdmissibility.Initial11
import PoincareChapterVI.PolarAdmissibility.Initial12
import PoincareChapterVI.PolarAdmissibility.Initial13
import PoincareChapterVI.PolarAdmissibility.Initial14
import PoincareChapterVI.PolarAdmissibility.Initial15
import PoincareChapterVI.PolarAdmissibility.Initial16
import PoincareChapterVI.PolarAdmissibility.Initial17
import PoincareChapterVI.PolarAdmissibility.Initial18
import PoincareChapterVI.PolarAdmissibility.Initial19
import PoincareChapterVI.PolarAdmissibility.Initial20
import PoincareChapterVI.PolarAdmissibility.Initial21
import PoincareChapterVI.PolarAdmissibility.Initial22
import PoincareChapterVI.PolarAdmissibility.Initial23
import PoincareChapterVI.PolarAdmissibility.Initial24
import PoincareChapterVI.PolarAdmissibility.Initial25
import PoincareChapterVI.PolarAdmissibility.Initial26
import PoincareChapterVI.PolarAdmissibility.Initial27
import PoincareChapterVI.PolarAdmissibility.Final0
import PoincareChapterVI.PolarAdmissibility.Final1
import PoincareChapterVI.PolarAdmissibility.Final2
import PoincareChapterVI.PolarAdmissibility.Final3
import PoincareChapterVI.PolarAdmissibility.Final4
import PoincareChapterVI.PolarAdmissibility.Final5
import PoincareChapterVI.PolarAdmissibility.Final6
import PoincareChapterVI.PolarAdmissibility.Final7
import PoincareChapterVI.PolarAdmissibility.Final8
import PoincareChapterVI.PolarAdmissibility.Final9
import PoincareChapterVI.PolarAdmissibility.Final10
import PoincareChapterVI.PolarAdmissibility.Final11
import PoincareChapterVI.PolarAdmissibility.Final12
import PoincareChapterVI.PolarAdmissibility.Final13
import PoincareChapterVI.PolarAdmissibility.Final14
import PoincareChapterVI.PolarAdmissibility.Final15
import PoincareChapterVI.PolarAdmissibility.Final16
import PoincareChapterVI.PolarAdmissibility.Final17
import PoincareChapterVI.PolarAdmissibility.Final18
import PoincareChapterVI.PolarAdmissibility.Final19
import PoincareChapterVI.PolarAdmissibility.Final20
import PoincareChapterVI.PolarAdmissibility.Final21
import PoincareChapterVI.PolarAdmissibility.Final22
import PoincareChapterVI.PolarAdmissibility.Final23
import PoincareChapterVI.PolarAdmissibility.Final24
import PoincareChapterVI.PolarAdmissibility.Final25
import PoincareChapterVI.PolarAdmissibility.Final26
import PoincareChapterVI.PolarAdmissibility.Final27

namespace PoincareChapterVI.ChapterVIDOuterArcPolarCompiledGrid

open ChapterVILeanCompCertBatch
open LeanCompCert.Ports.SignedProductClaims
open scoped unitInterval

/-- Every compiled shard stays inside the unsigned 64-bit fragment used by LeanCompCert. -/
theorem shard_admissible (side : ChapterVIDOuterArcSide) (i : Fin 28) :
    Admissible (batchClaims (shardOperations side i)) := by
  cases side with
  | initial =>
    fin_cases i
    · exact shard_admissible_initial_0
    · exact shard_admissible_initial_1
    · exact shard_admissible_initial_2
    · exact shard_admissible_initial_3
    · exact shard_admissible_initial_4
    · exact shard_admissible_initial_5
    · exact shard_admissible_initial_6
    · exact shard_admissible_initial_7
    · exact shard_admissible_initial_8
    · exact shard_admissible_initial_9
    · exact shard_admissible_initial_10
    · exact shard_admissible_initial_11
    · exact shard_admissible_initial_12
    · exact shard_admissible_initial_13
    · exact shard_admissible_initial_14
    · exact shard_admissible_initial_15
    · exact shard_admissible_initial_16
    · exact shard_admissible_initial_17
    · exact shard_admissible_initial_18
    · exact shard_admissible_initial_19
    · exact shard_admissible_initial_20
    · exact shard_admissible_initial_21
    · exact shard_admissible_initial_22
    · exact shard_admissible_initial_23
    · exact shard_admissible_initial_24
    · exact shard_admissible_initial_25
    · exact shard_admissible_initial_26
    · exact shard_admissible_initial_27
  | final =>
    fin_cases i
    · exact shard_admissible_final_0
    · exact shard_admissible_final_1
    · exact shard_admissible_final_2
    · exact shard_admissible_final_3
    · exact shard_admissible_final_4
    · exact shard_admissible_final_5
    · exact shard_admissible_final_6
    · exact shard_admissible_final_7
    · exact shard_admissible_final_8
    · exact shard_admissible_final_9
    · exact shard_admissible_final_10
    · exact shard_admissible_final_11
    · exact shard_admissible_final_12
    · exact shard_admissible_final_13
    · exact shard_admissible_final_14
    · exact shard_admissible_final_15
    · exact shard_admissible_final_16
    · exact shard_admissible_final_17
    · exact shard_admissible_final_18
    · exact shard_admissible_final_19
    · exact shard_admissible_final_20
    · exact shard_admissible_final_21
    · exact shard_admissible_final_22
    · exact shard_admissible_final_23
    · exact shard_admissible_final_24
    · exact shard_admissible_final_25
    · exact shard_admissible_final_26
    · exact shard_admissible_final_27

/-- Every signed comparison in every polar shard is proved by kernel reduction. -/
theorem shard_allHold (side : ChapterVIDOuterArcSide) (i : Fin 28) :
    ∀ claim ∈ batchClaims (shardOperations side i), claim.Holds := by
  cases side with
  | initial =>
    fin_cases i
    · exact shard_allHold_initial_0
    · exact shard_allHold_initial_1
    · exact shard_allHold_initial_2
    · exact shard_allHold_initial_3
    · exact shard_allHold_initial_4
    · exact shard_allHold_initial_5
    · exact shard_allHold_initial_6
    · exact shard_allHold_initial_7
    · exact shard_allHold_initial_8
    · exact shard_allHold_initial_9
    · exact shard_allHold_initial_10
    · exact shard_allHold_initial_11
    · exact shard_allHold_initial_12
    · exact shard_allHold_initial_13
    · exact shard_allHold_initial_14
    · exact shard_allHold_initial_15
    · exact shard_allHold_initial_16
    · exact shard_allHold_initial_17
    · exact shard_allHold_initial_18
    · exact shard_allHold_initial_19
    · exact shard_allHold_initial_20
    · exact shard_allHold_initial_21
    · exact shard_allHold_initial_22
    · exact shard_allHold_initial_23
    · exact shard_allHold_initial_24
    · exact shard_allHold_initial_25
    · exact shard_allHold_initial_26
    · exact shard_allHold_initial_27
  | final =>
    fin_cases i
    · exact shard_allHold_final_0
    · exact shard_allHold_final_1
    · exact shard_allHold_final_2
    · exact shard_allHold_final_3
    · exact shard_allHold_final_4
    · exact shard_allHold_final_5
    · exact shard_allHold_final_6
    · exact shard_allHold_final_7
    · exact shard_allHold_final_8
    · exact shard_allHold_final_9
    · exact shard_allHold_final_10
    · exact shard_allHold_final_11
    · exact shard_allHold_final_12
    · exact shard_allHold_final_13
    · exact shard_allHold_final_14
    · exact shard_allHold_final_15
    · exact shard_allHold_final_16
    · exact shard_allHold_final_17
    · exact shard_allHold_final_18
    · exact shard_allHold_final_19
    · exact shard_allHold_final_20
    · exact shard_allHold_final_21
    · exact shard_allHold_final_22
    · exact shard_allHold_final_23
    · exact shard_allHold_final_24
    · exact shard_allHold_final_25
    · exact shard_allHold_final_26
    · exact shard_allHold_final_27

/-- The only external observation required by the compiled route: every emitted shard returned
the zero failure count.  Admissibility is proved above in Lean's kernel. -/
structure CompiledRunVerdict : Prop where
  returnsZero : ∀ side i,
    (batchComputation (shardArtifactName side i) (shardOperations side i)).Returns
      ((0 : Nat) : Int)

/-- Unconditional verified-program verdict for the reference polar table. -/
theorem referenceRunVerdict : CompiledRunVerdict where
  returnsZero side i :=
    ChapterVILeanCompCertIntervalBridge.returns_zero_of_allHold
      (shardArtifactName side i) (batchClaims (shardOperations side i))
      (shard_admissible side i) (shard_allHold side i)

theorem CompiledRunVerdict.toCompiledVerdict (run : CompiledRunVerdict) : CompiledVerdict where
  shard side i := ⟨shard_admissible side i, run.returnsZero side i⟩

theorem radicand_re_pos_of_run (run : CompiledRunVerdict)
    (side : ChapterVIDOuterArcSide) (st : I × I) :
    0 < (chapterVIDOuterArcRadicand side st).re :=
  radicand_re_pos run.toCompiledVerdict side st

theorem radicand_ne_zero_of_run (run : CompiledRunVerdict)
    (side : ChapterVIDOuterArcSide) (st : I × I) :
    chapterVIDOuterArcRadicand side st ≠ 0 :=
  radicand_ne_zero run.toCompiledVerdict side st

theorem exists_squareRootSheet_of_run (run : CompiledRunVerdict)
    (side : ChapterVIDOuterArcSide) (base : I × I) (baseRoot : ℂ)
    (hbaseRoot : baseRoot ^ 2 = chapterVIDOuterArcRadicand side base) :
    ∃ sheet : ChapterVIContinuousSquareRootSheet (chapterVIDOuterArcRadicand side),
      sheet.root base = baseRoot :=
  exists_squareRootSheet run.toCompiledVerdict side base baseRoot hbaseRoot

end PoincareChapterVI.ChapterVIDOuterArcPolarCompiledGrid
