/- This file is generated by research/generate_chapter_vi_clustered_unit_grid.py. -/
import PoincareChapterVI.ChapterVILeanCompCertProposals
import PoincareChapterVI.ChapterVINonuniformGrid

namespace PoincareChapterVI

open ChapterVILeanCompCertBatch
open LeanCompCert.Ports.SignedProductClaims
open scoped unitInterval

namespace ChapterVIDOuterArcUnitClusteredCompiledGrid

abbrev Interval := ChapterVISignedDyadicInterval 20

def inputData : Array Interval := #[
  ⟨0, 64512⟩,
  ⟨64512, 126976⟩,
  ⟨126976, 187392⟩,
  ⟨187392, 245760⟩,
  ⟨245760, 302080⟩,
  ⟨302080, 356352⟩,
  ⟨356352, 408576⟩,
  ⟨408576, 458752⟩,
  ⟨458752, 506880⟩,
  ⟨506880, 552960⟩,
  ⟨552960, 596992⟩,
  ⟨596992, 638976⟩,
  ⟨638976, 678912⟩,
  ⟨678912, 716800⟩,
  ⟨716800, 752640⟩,
  ⟨752640, 786432⟩,
  ⟨786432, 818176⟩,
  ⟨818176, 847872⟩,
  ⟨847872, 875520⟩,
  ⟨875520, 901120⟩,
  ⟨901120, 924672⟩,
  ⟨924672, 946176⟩,
  ⟨946176, 965632⟩,
  ⟨965632, 983040⟩,
  ⟨983040, 998400⟩,
  ⟨998400, 1011712⟩,
  ⟨1011712, 1022976⟩,
  ⟨1022976, 1032192⟩,
  ⟨1032192, 1039360⟩,
  ⟨1039360, 1044480⟩,
  ⟨1044480, 1047552⟩,
  ⟨1047552, 1048576⟩]

def input (i : Fin 32) : Interval := inputData[i]

def trace (i : Fin 32) : ChapterVIDOuterArcUnitTrace.Trace (input i) :=
  ChapterVILeanCompCertProposals.outerUnitTrace (input i)

noncomputable def operations : List (DyadicOperation 20) :=
  (List.ofFn fun i : Fin 32 => (trace i).operations).flatten

theorem trace_operations_mem (i : Fin 32) (operation : DyadicOperation 20)
    (hoperation : operation ∈ (trace i).operations) : operation ∈ operations := by
  rw [operations, List.mem_flatten]
  exact ⟨(trace i).operations, List.mem_ofFn.mpr ⟨i, rfl⟩, hoperation⟩

set_option maxRecDepth 100000 in
theorem operations_admissible : Admissible (batchClaims operations) := by
  refine ⟨?_, ?_, ?_⟩
  · decide +kernel
  · decide +kernel
  · decide +kernel

set_option maxRecDepth 100000 in
theorem operations_returns_zero :
    (batchComputation "chapter-vi-d-outer-unit-clustered-grid-20" operations).Returns
      ((0 : Nat) : Int) := by
  decide +kernel

theorem input_contains_of_mem_cell (i : Fin 32) {parameter : I}
    (hlower : (chapterVIQuadraticClusterNode 32 i : ℝ) ≤ parameter)
    (hupper : (parameter : ℝ) ≤ chapterVIQuadraticClusterNode 32 (i + 1)) :
    (input i).Contains (parameter : ℝ) := by
  fin_cases i <;>
    norm_num [input, inputData, chapterVIQuadraticClusterNode,
      ChapterVISignedDyadicInterval.Contains,
      ChapterVISignedDyadicInterval.toRealInterval,
      ChapterVISignedDyadicInterval.scale] at hlower hupper ⊢ <;>
    constructor <;> linarith

theorem outerOutput_contains_cell (side : ChapterVIDOuterArcSide)
    (i : Fin 32) {parameter : I}
    (hlower : (chapterVIQuadraticClusterNode 32 i : ℝ) ≤ parameter)
    (hupper : (parameter : ℝ) ≤ chapterVIQuadraticClusterNode 32 (i + 1)) :
    (ChapterVIDOuterArcUnitTrace.outerOutput side (trace i)).Contains
      (chapterVIDRationalOuterArcUnit side parameter) := by
  apply ChapterVIDOuterArcUnitTrace.outerOutput_contains_of_allSound
  · intro operation hoperation
    exact allSound_of_returns_zero "chapter-vi-d-outer-unit-clustered-grid-20"
      operations operations_admissible operations_returns_zero operation
      (trace_operations_mem i operation hoperation)
  · exact input_contains_of_mem_cell i hlower hupper

theorem exists_outerOutput_contains (side : ChapterVIDOuterArcSide) (parameter : I) :
    ∃ i : Fin 32,
      (ChapterVIDOuterArcUnitTrace.outerOutput side (trace i)).Contains
        (chapterVIDRationalOuterArcUnit side parameter) := by
  rcases exists_mem_quadraticClusterCell 32 (by norm_num) parameter with
    ⟨i, hi, hlower, hupper⟩
  exact ⟨⟨i, hi⟩, outerOutput_contains_cell side ⟨i, hi⟩ hlower hupper⟩

end ChapterVIDOuterArcUnitClusteredCompiledGrid

end PoincareChapterVI

