/- This file is generated by
research/generate_chapter_vi_pinching_prefix_admissibility.py. -/
import PoincareChapterVI.PinchingArcPrefixAdmissibility.Upper0
import PoincareChapterVI.PinchingArcPrefixAdmissibility.Upper1
import PoincareChapterVI.PinchingArcPrefixAdmissibility.Upper2
import PoincareChapterVI.PinchingArcPrefixAdmissibility.Upper3
import PoincareChapterVI.PinchingArcPrefixAdmissibility.Upper4
import PoincareChapterVI.PinchingArcPrefixAdmissibility.Upper5
import PoincareChapterVI.PinchingArcPrefixAdmissibility.Upper6
import PoincareChapterVI.PinchingArcPrefixAdmissibility.Upper7
import PoincareChapterVI.PinchingArcPrefixAdmissibility.Upper8
import PoincareChapterVI.PinchingArcPrefixAdmissibility.Upper9
import PoincareChapterVI.PinchingArcPrefixAdmissibility.Upper10
import PoincareChapterVI.PinchingArcPrefixAdmissibility.Upper11
import PoincareChapterVI.PinchingArcPrefixAdmissibility.Upper12
import PoincareChapterVI.PinchingArcPrefixAdmissibility.Upper13
import PoincareChapterVI.PinchingArcPrefixAdmissibility.Upper14
import PoincareChapterVI.PinchingArcPrefixAdmissibility.Upper15
import PoincareChapterVI.PinchingArcPrefixAdmissibility.Upper16
import PoincareChapterVI.PinchingArcPrefixAdmissibility.Upper17
import PoincareChapterVI.PinchingArcPrefixAdmissibility.Upper18
import PoincareChapterVI.PinchingArcPrefixAdmissibility.Upper19
import PoincareChapterVI.PinchingArcPrefixAdmissibility.Upper20
import PoincareChapterVI.PinchingArcPrefixAdmissibility.Upper21
import PoincareChapterVI.PinchingArcPrefixAdmissibility.Lower0
import PoincareChapterVI.PinchingArcPrefixAdmissibility.Lower1
import PoincareChapterVI.PinchingArcPrefixAdmissibility.Lower2
import PoincareChapterVI.PinchingArcPrefixAdmissibility.Lower3
import PoincareChapterVI.PinchingArcPrefixAdmissibility.Lower4
import PoincareChapterVI.PinchingArcPrefixAdmissibility.Lower5
import PoincareChapterVI.PinchingArcPrefixAdmissibility.Lower6
import PoincareChapterVI.PinchingArcPrefixAdmissibility.Lower7
import PoincareChapterVI.PinchingArcPrefixAdmissibility.Lower8
import PoincareChapterVI.PinchingArcPrefixAdmissibility.Lower9
import PoincareChapterVI.PinchingArcPrefixAdmissibility.Lower10
import PoincareChapterVI.PinchingArcPrefixAdmissibility.Lower11
import PoincareChapterVI.PinchingArcPrefixAdmissibility.Lower12
import PoincareChapterVI.PinchingArcPrefixAdmissibility.Lower13
import PoincareChapterVI.PinchingArcPrefixAdmissibility.Lower14
import PoincareChapterVI.PinchingArcPrefixAdmissibility.Lower15
import PoincareChapterVI.PinchingArcPrefixAdmissibility.Lower16
import PoincareChapterVI.PinchingArcPrefixAdmissibility.Lower17
import PoincareChapterVI.PinchingArcPrefixAdmissibility.Lower18
import PoincareChapterVI.PinchingArcPrefixAdmissibility.Lower19
import PoincareChapterVI.PinchingArcPrefixAdmissibility.Lower20
import PoincareChapterVI.PinchingArcPrefixAdmissibility.Lower21

namespace PoincareChapterVI.ChapterVIDPinchingArcPrefixCompiledGrid

open ChapterVILeanCompCertBatch
open LeanCompCert.Ports.SignedProductClaims
open scoped unitInterval

theorem shard_admissible (side : ChapterVIDPinchingArcSide) (i : Fin 22) :
    Admissible (batchClaims (shardOperations side i)) := by
  cases side with
  | upper =>
    fin_cases i
    · exact shard_admissible_upper_0
    · exact shard_admissible_upper_1
    · exact shard_admissible_upper_2
    · exact shard_admissible_upper_3
    · exact shard_admissible_upper_4
    · exact shard_admissible_upper_5
    · exact shard_admissible_upper_6
    · exact shard_admissible_upper_7
    · exact shard_admissible_upper_8
    · exact shard_admissible_upper_9
    · exact shard_admissible_upper_10
    · exact shard_admissible_upper_11
    · exact shard_admissible_upper_12
    · exact shard_admissible_upper_13
    · exact shard_admissible_upper_14
    · exact shard_admissible_upper_15
    · exact shard_admissible_upper_16
    · exact shard_admissible_upper_17
    · exact shard_admissible_upper_18
    · exact shard_admissible_upper_19
    · exact shard_admissible_upper_20
    · exact shard_admissible_upper_21
  | lower =>
    fin_cases i
    · exact shard_admissible_lower_0
    · exact shard_admissible_lower_1
    · exact shard_admissible_lower_2
    · exact shard_admissible_lower_3
    · exact shard_admissible_lower_4
    · exact shard_admissible_lower_5
    · exact shard_admissible_lower_6
    · exact shard_admissible_lower_7
    · exact shard_admissible_lower_8
    · exact shard_admissible_lower_9
    · exact shard_admissible_lower_10
    · exact shard_admissible_lower_11
    · exact shard_admissible_lower_12
    · exact shard_admissible_lower_13
    · exact shard_admissible_lower_14
    · exact shard_admissible_lower_15
    · exact shard_admissible_lower_16
    · exact shard_admissible_lower_17
    · exact shard_admissible_lower_18
    · exact shard_admissible_lower_19
    · exact shard_admissible_lower_20
    · exact shard_admissible_lower_21

theorem shard_allHold (side : ChapterVIDPinchingArcSide) (i : Fin 22) :
    ∀ claim ∈ batchClaims (shardOperations side i), claim.Holds := by
  cases side with
  | upper =>
    fin_cases i
    · exact shard_allHold_upper_0
    · exact shard_allHold_upper_1
    · exact shard_allHold_upper_2
    · exact shard_allHold_upper_3
    · exact shard_allHold_upper_4
    · exact shard_allHold_upper_5
    · exact shard_allHold_upper_6
    · exact shard_allHold_upper_7
    · exact shard_allHold_upper_8
    · exact shard_allHold_upper_9
    · exact shard_allHold_upper_10
    · exact shard_allHold_upper_11
    · exact shard_allHold_upper_12
    · exact shard_allHold_upper_13
    · exact shard_allHold_upper_14
    · exact shard_allHold_upper_15
    · exact shard_allHold_upper_16
    · exact shard_allHold_upper_17
    · exact shard_allHold_upper_18
    · exact shard_allHold_upper_19
    · exact shard_allHold_upper_20
    · exact shard_allHold_upper_21
  | lower =>
    fin_cases i
    · exact shard_allHold_lower_0
    · exact shard_allHold_lower_1
    · exact shard_allHold_lower_2
    · exact shard_allHold_lower_3
    · exact shard_allHold_lower_4
    · exact shard_allHold_lower_5
    · exact shard_allHold_lower_6
    · exact shard_allHold_lower_7
    · exact shard_allHold_lower_8
    · exact shard_allHold_lower_9
    · exact shard_allHold_lower_10
    · exact shard_allHold_lower_11
    · exact shard_allHold_lower_12
    · exact shard_allHold_lower_13
    · exact shard_allHold_lower_14
    · exact shard_allHold_lower_15
    · exact shard_allHold_lower_16
    · exact shard_allHold_lower_17
    · exact shard_allHold_lower_18
    · exact shard_allHold_lower_19
    · exact shard_allHold_lower_20
    · exact shard_allHold_lower_21

/-- Unconditional verified-program verdict for all 44 pinching-prefix shards. -/
theorem referenceRunVerdict : CompiledVerdict where
  shard side i :=
    ⟨shard_admissible side i,
      ChapterVILeanCompCertIntervalBridge.returns_zero_of_allHold
        (shardArtifactName side i) (batchClaims (shardOperations side i))
        (shard_admissible side i) (shard_allHold side i)⟩

/-- The literal radicand has positive real part on both pinching quarters throughout the
certified global prefix. -/
theorem radicand_re_pos_reference
    (side : ChapterVIDPinchingArcSide) (st : I × I)
    (hprefix : (st.1 : ℝ) ≤ prefixEnd) :
    0 < (chapterVIDPinchingArcRadicand side st).re :=
  radicand_re_pos referenceRunVerdict side st hprefix

theorem radicand_ne_zero_reference
    (side : ChapterVIDPinchingArcSide) (st : I × I)
    (hprefix : (st.1 : ℝ) ≤ prefixEnd) :
    chapterVIDPinchingArcRadicand side st ≠ 0 :=
  radicand_ne_zero referenceRunVerdict side st hprefix

end PoincareChapterVI.ChapterVIDPinchingArcPrefixCompiledGrid
