/- This file is generated by research/generate_radial_tail_kernel_shards.py. -/
import PoincareChapterVI.RadialTailCenteredKernel.Upper0_0
import PoincareChapterVI.RadialTailCenteredKernel.Upper0_1
import PoincareChapterVI.RadialTailCenteredKernel.Upper0_2
import PoincareChapterVI.RadialTailCenteredKernel.Upper0_3
import PoincareChapterVI.RadialTailCenteredKernel.Upper0_4
import PoincareChapterVI.RadialTailCenteredKernel.Upper0_5
import PoincareChapterVI.RadialTailCenteredKernel.Upper0_6
import PoincareChapterVI.RadialTailCenteredKernel.Upper0_7
import PoincareChapterVI.RadialTailCenteredKernel.Upper0_8
import PoincareChapterVI.RadialTailCenteredKernel.Upper0_9
import PoincareChapterVI.RadialTailCenteredKernel.Upper0_10
import PoincareChapterVI.RadialTailCenteredKernel.Upper0_11
import PoincareChapterVI.RadialTailCenteredKernel.Upper0_12
import PoincareChapterVI.RadialTailCenteredKernel.Upper0_13
import PoincareChapterVI.RadialTailCenteredKernel.Upper0_14
import PoincareChapterVI.RadialTailCenteredKernel.Upper0_15
import PoincareChapterVI.RadialTailCenteredKernel.Upper1_0
import PoincareChapterVI.RadialTailCenteredKernel.Upper1_1
import PoincareChapterVI.RadialTailCenteredKernel.Upper1_2
import PoincareChapterVI.RadialTailCenteredKernel.Upper1_3
import PoincareChapterVI.RadialTailCenteredKernel.Upper1_4
import PoincareChapterVI.RadialTailCenteredKernel.Upper1_5
import PoincareChapterVI.RadialTailCenteredKernel.Upper1_6
import PoincareChapterVI.RadialTailCenteredKernel.Upper1_7
import PoincareChapterVI.RadialTailCenteredKernel.Upper1_8
import PoincareChapterVI.RadialTailCenteredKernel.Upper1_9
import PoincareChapterVI.RadialTailCenteredKernel.Upper1_10
import PoincareChapterVI.RadialTailCenteredKernel.Upper1_11
import PoincareChapterVI.RadialTailCenteredKernel.Upper1_12
import PoincareChapterVI.RadialTailCenteredKernel.Upper1_13
import PoincareChapterVI.RadialTailCenteredKernel.Upper1_14
import PoincareChapterVI.RadialTailCenteredKernel.Upper1_15
import PoincareChapterVI.RadialTailCenteredKernel.Upper2_0
import PoincareChapterVI.RadialTailCenteredKernel.Upper2_1
import PoincareChapterVI.RadialTailCenteredKernel.Upper2_2
import PoincareChapterVI.RadialTailCenteredKernel.Upper2_3
import PoincareChapterVI.RadialTailCenteredKernel.Upper2_4
import PoincareChapterVI.RadialTailCenteredKernel.Upper2_5
import PoincareChapterVI.RadialTailCenteredKernel.Upper2_6
import PoincareChapterVI.RadialTailCenteredKernel.Upper2_7
import PoincareChapterVI.RadialTailCenteredKernel.Upper2_8
import PoincareChapterVI.RadialTailCenteredKernel.Upper2_9
import PoincareChapterVI.RadialTailCenteredKernel.Upper2_10
import PoincareChapterVI.RadialTailCenteredKernel.Upper2_11
import PoincareChapterVI.RadialTailCenteredKernel.Upper2_12
import PoincareChapterVI.RadialTailCenteredKernel.Upper2_13
import PoincareChapterVI.RadialTailCenteredKernel.Upper2_14
import PoincareChapterVI.RadialTailCenteredKernel.Upper2_15
import PoincareChapterVI.RadialTailCenteredKernel.Upper3_0
import PoincareChapterVI.RadialTailCenteredKernel.Upper3_1
import PoincareChapterVI.RadialTailCenteredKernel.Upper3_2
import PoincareChapterVI.RadialTailCenteredKernel.Upper3_3
import PoincareChapterVI.RadialTailCenteredKernel.Upper3_4
import PoincareChapterVI.RadialTailCenteredKernel.Upper3_5
import PoincareChapterVI.RadialTailCenteredKernel.Upper3_6
import PoincareChapterVI.RadialTailCenteredKernel.Upper3_7
import PoincareChapterVI.RadialTailCenteredKernel.Upper3_8
import PoincareChapterVI.RadialTailCenteredKernel.Upper3_9
import PoincareChapterVI.RadialTailCenteredKernel.Upper3_10
import PoincareChapterVI.RadialTailCenteredKernel.Upper3_11
import PoincareChapterVI.RadialTailCenteredKernel.Upper3_12
import PoincareChapterVI.RadialTailCenteredKernel.Upper3_13
import PoincareChapterVI.RadialTailCenteredKernel.Upper3_14
import PoincareChapterVI.RadialTailCenteredKernel.Upper3_15
import PoincareChapterVI.RadialTailCenteredKernel.Upper4_0
import PoincareChapterVI.RadialTailCenteredKernel.Upper4_1
import PoincareChapterVI.RadialTailCenteredKernel.Upper4_2
import PoincareChapterVI.RadialTailCenteredKernel.Upper4_3
import PoincareChapterVI.RadialTailCenteredKernel.Upper4_4
import PoincareChapterVI.RadialTailCenteredKernel.Upper4_5
import PoincareChapterVI.RadialTailCenteredKernel.Upper4_6
import PoincareChapterVI.RadialTailCenteredKernel.Upper4_7
import PoincareChapterVI.RadialTailCenteredKernel.Upper4_8
import PoincareChapterVI.RadialTailCenteredKernel.Upper4_9
import PoincareChapterVI.RadialTailCenteredKernel.Upper4_10
import PoincareChapterVI.RadialTailCenteredKernel.Upper4_11
import PoincareChapterVI.RadialTailCenteredKernel.Upper4_12
import PoincareChapterVI.RadialTailCenteredKernel.Upper4_13
import PoincareChapterVI.RadialTailCenteredKernel.Upper4_14
import PoincareChapterVI.RadialTailCenteredKernel.Upper4_15
import PoincareChapterVI.RadialTailCenteredKernel.Upper5_0
import PoincareChapterVI.RadialTailCenteredKernel.Upper5_1
import PoincareChapterVI.RadialTailCenteredKernel.Upper5_2
import PoincareChapterVI.RadialTailCenteredKernel.Upper5_3
import PoincareChapterVI.RadialTailCenteredKernel.Upper5_4
import PoincareChapterVI.RadialTailCenteredKernel.Upper5_5
import PoincareChapterVI.RadialTailCenteredKernel.Upper5_6
import PoincareChapterVI.RadialTailCenteredKernel.Upper5_7
import PoincareChapterVI.RadialTailCenteredKernel.Upper5_8
import PoincareChapterVI.RadialTailCenteredKernel.Upper5_9
import PoincareChapterVI.RadialTailCenteredKernel.Upper5_10
import PoincareChapterVI.RadialTailCenteredKernel.Upper5_11
import PoincareChapterVI.RadialTailCenteredKernel.Upper5_12
import PoincareChapterVI.RadialTailCenteredKernel.Upper5_13
import PoincareChapterVI.RadialTailCenteredKernel.Upper5_14
import PoincareChapterVI.RadialTailCenteredKernel.Upper5_15
import PoincareChapterVI.RadialTailCenteredKernel.Lower0_0
import PoincareChapterVI.RadialTailCenteredKernel.Lower0_1
import PoincareChapterVI.RadialTailCenteredKernel.Lower0_2
import PoincareChapterVI.RadialTailCenteredKernel.Lower0_3
import PoincareChapterVI.RadialTailCenteredKernel.Lower0_4
import PoincareChapterVI.RadialTailCenteredKernel.Lower0_5
import PoincareChapterVI.RadialTailCenteredKernel.Lower0_6
import PoincareChapterVI.RadialTailCenteredKernel.Lower0_7
import PoincareChapterVI.RadialTailCenteredKernel.Lower0_8
import PoincareChapterVI.RadialTailCenteredKernel.Lower0_9
import PoincareChapterVI.RadialTailCenteredKernel.Lower0_10
import PoincareChapterVI.RadialTailCenteredKernel.Lower0_11
import PoincareChapterVI.RadialTailCenteredKernel.Lower0_12
import PoincareChapterVI.RadialTailCenteredKernel.Lower0_13
import PoincareChapterVI.RadialTailCenteredKernel.Lower0_14
import PoincareChapterVI.RadialTailCenteredKernel.Lower0_15
import PoincareChapterVI.RadialTailCenteredKernel.Lower1_0
import PoincareChapterVI.RadialTailCenteredKernel.Lower1_1
import PoincareChapterVI.RadialTailCenteredKernel.Lower1_2
import PoincareChapterVI.RadialTailCenteredKernel.Lower1_3
import PoincareChapterVI.RadialTailCenteredKernel.Lower1_4
import PoincareChapterVI.RadialTailCenteredKernel.Lower1_5
import PoincareChapterVI.RadialTailCenteredKernel.Lower1_6
import PoincareChapterVI.RadialTailCenteredKernel.Lower1_7
import PoincareChapterVI.RadialTailCenteredKernel.Lower1_8
import PoincareChapterVI.RadialTailCenteredKernel.Lower1_9
import PoincareChapterVI.RadialTailCenteredKernel.Lower1_10
import PoincareChapterVI.RadialTailCenteredKernel.Lower1_11
import PoincareChapterVI.RadialTailCenteredKernel.Lower1_12
import PoincareChapterVI.RadialTailCenteredKernel.Lower1_13
import PoincareChapterVI.RadialTailCenteredKernel.Lower1_14
import PoincareChapterVI.RadialTailCenteredKernel.Lower1_15
import PoincareChapterVI.RadialTailCenteredKernel.Lower2_0
import PoincareChapterVI.RadialTailCenteredKernel.Lower2_1
import PoincareChapterVI.RadialTailCenteredKernel.Lower2_2
import PoincareChapterVI.RadialTailCenteredKernel.Lower2_3
import PoincareChapterVI.RadialTailCenteredKernel.Lower2_4
import PoincareChapterVI.RadialTailCenteredKernel.Lower2_5
import PoincareChapterVI.RadialTailCenteredKernel.Lower2_6
import PoincareChapterVI.RadialTailCenteredKernel.Lower2_7
import PoincareChapterVI.RadialTailCenteredKernel.Lower2_8
import PoincareChapterVI.RadialTailCenteredKernel.Lower2_9
import PoincareChapterVI.RadialTailCenteredKernel.Lower2_10
import PoincareChapterVI.RadialTailCenteredKernel.Lower2_11
import PoincareChapterVI.RadialTailCenteredKernel.Lower2_12
import PoincareChapterVI.RadialTailCenteredKernel.Lower2_13
import PoincareChapterVI.RadialTailCenteredKernel.Lower2_14
import PoincareChapterVI.RadialTailCenteredKernel.Lower2_15
import PoincareChapterVI.RadialTailCenteredKernel.Lower3_0
import PoincareChapterVI.RadialTailCenteredKernel.Lower3_1
import PoincareChapterVI.RadialTailCenteredKernel.Lower3_2
import PoincareChapterVI.RadialTailCenteredKernel.Lower3_3
import PoincareChapterVI.RadialTailCenteredKernel.Lower3_4
import PoincareChapterVI.RadialTailCenteredKernel.Lower3_5
import PoincareChapterVI.RadialTailCenteredKernel.Lower3_6
import PoincareChapterVI.RadialTailCenteredKernel.Lower3_7
import PoincareChapterVI.RadialTailCenteredKernel.Lower3_8
import PoincareChapterVI.RadialTailCenteredKernel.Lower3_9
import PoincareChapterVI.RadialTailCenteredKernel.Lower3_10
import PoincareChapterVI.RadialTailCenteredKernel.Lower3_11
import PoincareChapterVI.RadialTailCenteredKernel.Lower3_12
import PoincareChapterVI.RadialTailCenteredKernel.Lower3_13
import PoincareChapterVI.RadialTailCenteredKernel.Lower3_14
import PoincareChapterVI.RadialTailCenteredKernel.Lower3_15
import PoincareChapterVI.RadialTailCenteredKernel.Lower4_0
import PoincareChapterVI.RadialTailCenteredKernel.Lower4_1
import PoincareChapterVI.RadialTailCenteredKernel.Lower4_2
import PoincareChapterVI.RadialTailCenteredKernel.Lower4_3
import PoincareChapterVI.RadialTailCenteredKernel.Lower4_4
import PoincareChapterVI.RadialTailCenteredKernel.Lower4_5
import PoincareChapterVI.RadialTailCenteredKernel.Lower4_6
import PoincareChapterVI.RadialTailCenteredKernel.Lower4_7
import PoincareChapterVI.RadialTailCenteredKernel.Lower4_8
import PoincareChapterVI.RadialTailCenteredKernel.Lower4_9
import PoincareChapterVI.RadialTailCenteredKernel.Lower4_10
import PoincareChapterVI.RadialTailCenteredKernel.Lower4_11
import PoincareChapterVI.RadialTailCenteredKernel.Lower4_12
import PoincareChapterVI.RadialTailCenteredKernel.Lower4_13
import PoincareChapterVI.RadialTailCenteredKernel.Lower4_14
import PoincareChapterVI.RadialTailCenteredKernel.Lower4_15
import PoincareChapterVI.RadialTailCenteredKernel.Lower5_0
import PoincareChapterVI.RadialTailCenteredKernel.Lower5_1
import PoincareChapterVI.RadialTailCenteredKernel.Lower5_2
import PoincareChapterVI.RadialTailCenteredKernel.Lower5_3
import PoincareChapterVI.RadialTailCenteredKernel.Lower5_4
import PoincareChapterVI.RadialTailCenteredKernel.Lower5_5
import PoincareChapterVI.RadialTailCenteredKernel.Lower5_6
import PoincareChapterVI.RadialTailCenteredKernel.Lower5_7
import PoincareChapterVI.RadialTailCenteredKernel.Lower5_8
import PoincareChapterVI.RadialTailCenteredKernel.Lower5_9
import PoincareChapterVI.RadialTailCenteredKernel.Lower5_10
import PoincareChapterVI.RadialTailCenteredKernel.Lower5_11
import PoincareChapterVI.RadialTailCenteredKernel.Lower5_12
import PoincareChapterVI.RadialTailCenteredKernel.Lower5_13
import PoincareChapterVI.RadialTailCenteredKernel.Lower5_14
import PoincareChapterVI.RadialTailCenteredKernel.Lower5_15

/-! Kernel-reduced aggregate of the 192 centered radial shards. -/

namespace PoincareChapterVI

open ChapterVILeanCompCertBatch
open ChapterVILeanCompCertAffineTrace

namespace ChapterVIDRadialTailCenteredCompiledGrid

open ChapterVIDRadialTailCellInputTrace

set_option maxRecDepth 1000000
set_option maxHeartbeats 0

theorem all_program_valid :
    ∀ side row radial angular,
      ProgramValid (inputs side row radial angular)
        (ChapterVIDRadialTailBaseCenteredProgram.program side) = true := by
  intro side row radial angular
  cases side with
  | upper =>
      fin_cases row <;> fin_cases radial
      · exact program_valid_upper_0_0 angular
      · exact program_valid_upper_0_1 angular
      · exact program_valid_upper_0_2 angular
      · exact program_valid_upper_0_3 angular
      · exact program_valid_upper_0_4 angular
      · exact program_valid_upper_0_5 angular
      · exact program_valid_upper_0_6 angular
      · exact program_valid_upper_0_7 angular
      · exact program_valid_upper_0_8 angular
      · exact program_valid_upper_0_9 angular
      · exact program_valid_upper_0_10 angular
      · exact program_valid_upper_0_11 angular
      · exact program_valid_upper_0_12 angular
      · exact program_valid_upper_0_13 angular
      · exact program_valid_upper_0_14 angular
      · exact program_valid_upper_0_15 angular
      · exact program_valid_upper_1_0 angular
      · exact program_valid_upper_1_1 angular
      · exact program_valid_upper_1_2 angular
      · exact program_valid_upper_1_3 angular
      · exact program_valid_upper_1_4 angular
      · exact program_valid_upper_1_5 angular
      · exact program_valid_upper_1_6 angular
      · exact program_valid_upper_1_7 angular
      · exact program_valid_upper_1_8 angular
      · exact program_valid_upper_1_9 angular
      · exact program_valid_upper_1_10 angular
      · exact program_valid_upper_1_11 angular
      · exact program_valid_upper_1_12 angular
      · exact program_valid_upper_1_13 angular
      · exact program_valid_upper_1_14 angular
      · exact program_valid_upper_1_15 angular
      · exact program_valid_upper_2_0 angular
      · exact program_valid_upper_2_1 angular
      · exact program_valid_upper_2_2 angular
      · exact program_valid_upper_2_3 angular
      · exact program_valid_upper_2_4 angular
      · exact program_valid_upper_2_5 angular
      · exact program_valid_upper_2_6 angular
      · exact program_valid_upper_2_7 angular
      · exact program_valid_upper_2_8 angular
      · exact program_valid_upper_2_9 angular
      · exact program_valid_upper_2_10 angular
      · exact program_valid_upper_2_11 angular
      · exact program_valid_upper_2_12 angular
      · exact program_valid_upper_2_13 angular
      · exact program_valid_upper_2_14 angular
      · exact program_valid_upper_2_15 angular
      · exact program_valid_upper_3_0 angular
      · exact program_valid_upper_3_1 angular
      · exact program_valid_upper_3_2 angular
      · exact program_valid_upper_3_3 angular
      · exact program_valid_upper_3_4 angular
      · exact program_valid_upper_3_5 angular
      · exact program_valid_upper_3_6 angular
      · exact program_valid_upper_3_7 angular
      · exact program_valid_upper_3_8 angular
      · exact program_valid_upper_3_9 angular
      · exact program_valid_upper_3_10 angular
      · exact program_valid_upper_3_11 angular
      · exact program_valid_upper_3_12 angular
      · exact program_valid_upper_3_13 angular
      · exact program_valid_upper_3_14 angular
      · exact program_valid_upper_3_15 angular
      · exact program_valid_upper_4_0 angular
      · exact program_valid_upper_4_1 angular
      · exact program_valid_upper_4_2 angular
      · exact program_valid_upper_4_3 angular
      · exact program_valid_upper_4_4 angular
      · exact program_valid_upper_4_5 angular
      · exact program_valid_upper_4_6 angular
      · exact program_valid_upper_4_7 angular
      · exact program_valid_upper_4_8 angular
      · exact program_valid_upper_4_9 angular
      · exact program_valid_upper_4_10 angular
      · exact program_valid_upper_4_11 angular
      · exact program_valid_upper_4_12 angular
      · exact program_valid_upper_4_13 angular
      · exact program_valid_upper_4_14 angular
      · exact program_valid_upper_4_15 angular
      · exact program_valid_upper_5_0 angular
      · exact program_valid_upper_5_1 angular
      · exact program_valid_upper_5_2 angular
      · exact program_valid_upper_5_3 angular
      · exact program_valid_upper_5_4 angular
      · exact program_valid_upper_5_5 angular
      · exact program_valid_upper_5_6 angular
      · exact program_valid_upper_5_7 angular
      · exact program_valid_upper_5_8 angular
      · exact program_valid_upper_5_9 angular
      · exact program_valid_upper_5_10 angular
      · exact program_valid_upper_5_11 angular
      · exact program_valid_upper_5_12 angular
      · exact program_valid_upper_5_13 angular
      · exact program_valid_upper_5_14 angular
      · exact program_valid_upper_5_15 angular
  | lower =>
      fin_cases row <;> fin_cases radial
      · exact program_valid_lower_0_0 angular
      · exact program_valid_lower_0_1 angular
      · exact program_valid_lower_0_2 angular
      · exact program_valid_lower_0_3 angular
      · exact program_valid_lower_0_4 angular
      · exact program_valid_lower_0_5 angular
      · exact program_valid_lower_0_6 angular
      · exact program_valid_lower_0_7 angular
      · exact program_valid_lower_0_8 angular
      · exact program_valid_lower_0_9 angular
      · exact program_valid_lower_0_10 angular
      · exact program_valid_lower_0_11 angular
      · exact program_valid_lower_0_12 angular
      · exact program_valid_lower_0_13 angular
      · exact program_valid_lower_0_14 angular
      · exact program_valid_lower_0_15 angular
      · exact program_valid_lower_1_0 angular
      · exact program_valid_lower_1_1 angular
      · exact program_valid_lower_1_2 angular
      · exact program_valid_lower_1_3 angular
      · exact program_valid_lower_1_4 angular
      · exact program_valid_lower_1_5 angular
      · exact program_valid_lower_1_6 angular
      · exact program_valid_lower_1_7 angular
      · exact program_valid_lower_1_8 angular
      · exact program_valid_lower_1_9 angular
      · exact program_valid_lower_1_10 angular
      · exact program_valid_lower_1_11 angular
      · exact program_valid_lower_1_12 angular
      · exact program_valid_lower_1_13 angular
      · exact program_valid_lower_1_14 angular
      · exact program_valid_lower_1_15 angular
      · exact program_valid_lower_2_0 angular
      · exact program_valid_lower_2_1 angular
      · exact program_valid_lower_2_2 angular
      · exact program_valid_lower_2_3 angular
      · exact program_valid_lower_2_4 angular
      · exact program_valid_lower_2_5 angular
      · exact program_valid_lower_2_6 angular
      · exact program_valid_lower_2_7 angular
      · exact program_valid_lower_2_8 angular
      · exact program_valid_lower_2_9 angular
      · exact program_valid_lower_2_10 angular
      · exact program_valid_lower_2_11 angular
      · exact program_valid_lower_2_12 angular
      · exact program_valid_lower_2_13 angular
      · exact program_valid_lower_2_14 angular
      · exact program_valid_lower_2_15 angular
      · exact program_valid_lower_3_0 angular
      · exact program_valid_lower_3_1 angular
      · exact program_valid_lower_3_2 angular
      · exact program_valid_lower_3_3 angular
      · exact program_valid_lower_3_4 angular
      · exact program_valid_lower_3_5 angular
      · exact program_valid_lower_3_6 angular
      · exact program_valid_lower_3_7 angular
      · exact program_valid_lower_3_8 angular
      · exact program_valid_lower_3_9 angular
      · exact program_valid_lower_3_10 angular
      · exact program_valid_lower_3_11 angular
      · exact program_valid_lower_3_12 angular
      · exact program_valid_lower_3_13 angular
      · exact program_valid_lower_3_14 angular
      · exact program_valid_lower_3_15 angular
      · exact program_valid_lower_4_0 angular
      · exact program_valid_lower_4_1 angular
      · exact program_valid_lower_4_2 angular
      · exact program_valid_lower_4_3 angular
      · exact program_valid_lower_4_4 angular
      · exact program_valid_lower_4_5 angular
      · exact program_valid_lower_4_6 angular
      · exact program_valid_lower_4_7 angular
      · exact program_valid_lower_4_8 angular
      · exact program_valid_lower_4_9 angular
      · exact program_valid_lower_4_10 angular
      · exact program_valid_lower_4_11 angular
      · exact program_valid_lower_4_12 angular
      · exact program_valid_lower_4_13 angular
      · exact program_valid_lower_4_14 angular
      · exact program_valid_lower_4_15 angular
      · exact program_valid_lower_5_0 angular
      · exact program_valid_lower_5_1 angular
      · exact program_valid_lower_5_2 angular
      · exact program_valid_lower_5_3 angular
      · exact program_valid_lower_5_4 angular
      · exact program_valid_lower_5_5 angular
      · exact program_valid_lower_5_6 angular
      · exact program_valid_lower_5_7 angular
      · exact program_valid_lower_5_8 angular
      · exact program_valid_lower_5_9 angular
      · exact program_valid_lower_5_10 angular
      · exact program_valid_lower_5_11 angular
      · exact program_valid_lower_5_12 angular
      · exact program_valid_lower_5_13 angular
      · exact program_valid_lower_5_14 angular
      · exact program_valid_lower_5_15 angular

/-- Every outward-rounded operation in all 14,336 cells is mathematically sound. -/
theorem all_operations_sound :
    ∀ side row radial angular operation,
      operation ∈ cellOperations side row radial angular → operation.Sound := by
  intro side row radial angular
  exact proposeProgram_operations_sound _ _
    (all_program_valid side row radial angular)

theorem all_output_upper_negative :
    ∀ side row radial angular,
      (cellOutput side row radial angular).real.upper < 0 := by
  intro side row radial angular
  cases side with
  | upper =>
      fin_cases row <;> fin_cases radial
      · exact output_negative_upper_0_0 angular
      · exact output_negative_upper_0_1 angular
      · exact output_negative_upper_0_2 angular
      · exact output_negative_upper_0_3 angular
      · exact output_negative_upper_0_4 angular
      · exact output_negative_upper_0_5 angular
      · exact output_negative_upper_0_6 angular
      · exact output_negative_upper_0_7 angular
      · exact output_negative_upper_0_8 angular
      · exact output_negative_upper_0_9 angular
      · exact output_negative_upper_0_10 angular
      · exact output_negative_upper_0_11 angular
      · exact output_negative_upper_0_12 angular
      · exact output_negative_upper_0_13 angular
      · exact output_negative_upper_0_14 angular
      · exact output_negative_upper_0_15 angular
      · exact output_negative_upper_1_0 angular
      · exact output_negative_upper_1_1 angular
      · exact output_negative_upper_1_2 angular
      · exact output_negative_upper_1_3 angular
      · exact output_negative_upper_1_4 angular
      · exact output_negative_upper_1_5 angular
      · exact output_negative_upper_1_6 angular
      · exact output_negative_upper_1_7 angular
      · exact output_negative_upper_1_8 angular
      · exact output_negative_upper_1_9 angular
      · exact output_negative_upper_1_10 angular
      · exact output_negative_upper_1_11 angular
      · exact output_negative_upper_1_12 angular
      · exact output_negative_upper_1_13 angular
      · exact output_negative_upper_1_14 angular
      · exact output_negative_upper_1_15 angular
      · exact output_negative_upper_2_0 angular
      · exact output_negative_upper_2_1 angular
      · exact output_negative_upper_2_2 angular
      · exact output_negative_upper_2_3 angular
      · exact output_negative_upper_2_4 angular
      · exact output_negative_upper_2_5 angular
      · exact output_negative_upper_2_6 angular
      · exact output_negative_upper_2_7 angular
      · exact output_negative_upper_2_8 angular
      · exact output_negative_upper_2_9 angular
      · exact output_negative_upper_2_10 angular
      · exact output_negative_upper_2_11 angular
      · exact output_negative_upper_2_12 angular
      · exact output_negative_upper_2_13 angular
      · exact output_negative_upper_2_14 angular
      · exact output_negative_upper_2_15 angular
      · exact output_negative_upper_3_0 angular
      · exact output_negative_upper_3_1 angular
      · exact output_negative_upper_3_2 angular
      · exact output_negative_upper_3_3 angular
      · exact output_negative_upper_3_4 angular
      · exact output_negative_upper_3_5 angular
      · exact output_negative_upper_3_6 angular
      · exact output_negative_upper_3_7 angular
      · exact output_negative_upper_3_8 angular
      · exact output_negative_upper_3_9 angular
      · exact output_negative_upper_3_10 angular
      · exact output_negative_upper_3_11 angular
      · exact output_negative_upper_3_12 angular
      · exact output_negative_upper_3_13 angular
      · exact output_negative_upper_3_14 angular
      · exact output_negative_upper_3_15 angular
      · exact output_negative_upper_4_0 angular
      · exact output_negative_upper_4_1 angular
      · exact output_negative_upper_4_2 angular
      · exact output_negative_upper_4_3 angular
      · exact output_negative_upper_4_4 angular
      · exact output_negative_upper_4_5 angular
      · exact output_negative_upper_4_6 angular
      · exact output_negative_upper_4_7 angular
      · exact output_negative_upper_4_8 angular
      · exact output_negative_upper_4_9 angular
      · exact output_negative_upper_4_10 angular
      · exact output_negative_upper_4_11 angular
      · exact output_negative_upper_4_12 angular
      · exact output_negative_upper_4_13 angular
      · exact output_negative_upper_4_14 angular
      · exact output_negative_upper_4_15 angular
      · exact output_negative_upper_5_0 angular
      · exact output_negative_upper_5_1 angular
      · exact output_negative_upper_5_2 angular
      · exact output_negative_upper_5_3 angular
      · exact output_negative_upper_5_4 angular
      · exact output_negative_upper_5_5 angular
      · exact output_negative_upper_5_6 angular
      · exact output_negative_upper_5_7 angular
      · exact output_negative_upper_5_8 angular
      · exact output_negative_upper_5_9 angular
      · exact output_negative_upper_5_10 angular
      · exact output_negative_upper_5_11 angular
      · exact output_negative_upper_5_12 angular
      · exact output_negative_upper_5_13 angular
      · exact output_negative_upper_5_14 angular
      · exact output_negative_upper_5_15 angular
  | lower =>
      fin_cases row <;> fin_cases radial
      · exact output_negative_lower_0_0 angular
      · exact output_negative_lower_0_1 angular
      · exact output_negative_lower_0_2 angular
      · exact output_negative_lower_0_3 angular
      · exact output_negative_lower_0_4 angular
      · exact output_negative_lower_0_5 angular
      · exact output_negative_lower_0_6 angular
      · exact output_negative_lower_0_7 angular
      · exact output_negative_lower_0_8 angular
      · exact output_negative_lower_0_9 angular
      · exact output_negative_lower_0_10 angular
      · exact output_negative_lower_0_11 angular
      · exact output_negative_lower_0_12 angular
      · exact output_negative_lower_0_13 angular
      · exact output_negative_lower_0_14 angular
      · exact output_negative_lower_0_15 angular
      · exact output_negative_lower_1_0 angular
      · exact output_negative_lower_1_1 angular
      · exact output_negative_lower_1_2 angular
      · exact output_negative_lower_1_3 angular
      · exact output_negative_lower_1_4 angular
      · exact output_negative_lower_1_5 angular
      · exact output_negative_lower_1_6 angular
      · exact output_negative_lower_1_7 angular
      · exact output_negative_lower_1_8 angular
      · exact output_negative_lower_1_9 angular
      · exact output_negative_lower_1_10 angular
      · exact output_negative_lower_1_11 angular
      · exact output_negative_lower_1_12 angular
      · exact output_negative_lower_1_13 angular
      · exact output_negative_lower_1_14 angular
      · exact output_negative_lower_1_15 angular
      · exact output_negative_lower_2_0 angular
      · exact output_negative_lower_2_1 angular
      · exact output_negative_lower_2_2 angular
      · exact output_negative_lower_2_3 angular
      · exact output_negative_lower_2_4 angular
      · exact output_negative_lower_2_5 angular
      · exact output_negative_lower_2_6 angular
      · exact output_negative_lower_2_7 angular
      · exact output_negative_lower_2_8 angular
      · exact output_negative_lower_2_9 angular
      · exact output_negative_lower_2_10 angular
      · exact output_negative_lower_2_11 angular
      · exact output_negative_lower_2_12 angular
      · exact output_negative_lower_2_13 angular
      · exact output_negative_lower_2_14 angular
      · exact output_negative_lower_2_15 angular
      · exact output_negative_lower_3_0 angular
      · exact output_negative_lower_3_1 angular
      · exact output_negative_lower_3_2 angular
      · exact output_negative_lower_3_3 angular
      · exact output_negative_lower_3_4 angular
      · exact output_negative_lower_3_5 angular
      · exact output_negative_lower_3_6 angular
      · exact output_negative_lower_3_7 angular
      · exact output_negative_lower_3_8 angular
      · exact output_negative_lower_3_9 angular
      · exact output_negative_lower_3_10 angular
      · exact output_negative_lower_3_11 angular
      · exact output_negative_lower_3_12 angular
      · exact output_negative_lower_3_13 angular
      · exact output_negative_lower_3_14 angular
      · exact output_negative_lower_3_15 angular
      · exact output_negative_lower_4_0 angular
      · exact output_negative_lower_4_1 angular
      · exact output_negative_lower_4_2 angular
      · exact output_negative_lower_4_3 angular
      · exact output_negative_lower_4_4 angular
      · exact output_negative_lower_4_5 angular
      · exact output_negative_lower_4_6 angular
      · exact output_negative_lower_4_7 angular
      · exact output_negative_lower_4_8 angular
      · exact output_negative_lower_4_9 angular
      · exact output_negative_lower_4_10 angular
      · exact output_negative_lower_4_11 angular
      · exact output_negative_lower_4_12 angular
      · exact output_negative_lower_4_13 angular
      · exact output_negative_lower_4_14 angular
      · exact output_negative_lower_4_15 angular
      · exact output_negative_lower_5_0 angular
      · exact output_negative_lower_5_1 angular
      · exact output_negative_lower_5_2 angular
      · exact output_negative_lower_5_3 angular
      · exact output_negative_lower_5_4 angular
      · exact output_negative_lower_5_5 angular
      · exact output_negative_lower_5_6 angular
      · exact output_negative_lower_5_7 angular
      · exact output_negative_lower_5_8 angular
      · exact output_negative_lower_5_9 angular
      · exact output_negative_lower_5_10 angular
      · exact output_negative_lower_5_11 angular
      · exact output_negative_lower_5_12 angular
      · exact output_negative_lower_5_13 angular
      · exact output_negative_lower_5_14 angular
      · exact output_negative_lower_5_15 angular

theorem all_argument_l1_bound :
    ∀ side row radial angular,
      ChapterVILeanCompCertProposals.componentBudget
          (cellArgument side row radial angular).real +
        ChapterVILeanCompCertProposals.componentBudget
          (cellArgument side row radial angular).imag ≤ 366503875925 := by
  intro side row radial angular
  cases side with
  | upper =>
      fin_cases row <;> fin_cases radial
      · exact argument_bound_upper_0_0 angular
      · exact argument_bound_upper_0_1 angular
      · exact argument_bound_upper_0_2 angular
      · exact argument_bound_upper_0_3 angular
      · exact argument_bound_upper_0_4 angular
      · exact argument_bound_upper_0_5 angular
      · exact argument_bound_upper_0_6 angular
      · exact argument_bound_upper_0_7 angular
      · exact argument_bound_upper_0_8 angular
      · exact argument_bound_upper_0_9 angular
      · exact argument_bound_upper_0_10 angular
      · exact argument_bound_upper_0_11 angular
      · exact argument_bound_upper_0_12 angular
      · exact argument_bound_upper_0_13 angular
      · exact argument_bound_upper_0_14 angular
      · exact argument_bound_upper_0_15 angular
      · exact argument_bound_upper_1_0 angular
      · exact argument_bound_upper_1_1 angular
      · exact argument_bound_upper_1_2 angular
      · exact argument_bound_upper_1_3 angular
      · exact argument_bound_upper_1_4 angular
      · exact argument_bound_upper_1_5 angular
      · exact argument_bound_upper_1_6 angular
      · exact argument_bound_upper_1_7 angular
      · exact argument_bound_upper_1_8 angular
      · exact argument_bound_upper_1_9 angular
      · exact argument_bound_upper_1_10 angular
      · exact argument_bound_upper_1_11 angular
      · exact argument_bound_upper_1_12 angular
      · exact argument_bound_upper_1_13 angular
      · exact argument_bound_upper_1_14 angular
      · exact argument_bound_upper_1_15 angular
      · exact argument_bound_upper_2_0 angular
      · exact argument_bound_upper_2_1 angular
      · exact argument_bound_upper_2_2 angular
      · exact argument_bound_upper_2_3 angular
      · exact argument_bound_upper_2_4 angular
      · exact argument_bound_upper_2_5 angular
      · exact argument_bound_upper_2_6 angular
      · exact argument_bound_upper_2_7 angular
      · exact argument_bound_upper_2_8 angular
      · exact argument_bound_upper_2_9 angular
      · exact argument_bound_upper_2_10 angular
      · exact argument_bound_upper_2_11 angular
      · exact argument_bound_upper_2_12 angular
      · exact argument_bound_upper_2_13 angular
      · exact argument_bound_upper_2_14 angular
      · exact argument_bound_upper_2_15 angular
      · exact argument_bound_upper_3_0 angular
      · exact argument_bound_upper_3_1 angular
      · exact argument_bound_upper_3_2 angular
      · exact argument_bound_upper_3_3 angular
      · exact argument_bound_upper_3_4 angular
      · exact argument_bound_upper_3_5 angular
      · exact argument_bound_upper_3_6 angular
      · exact argument_bound_upper_3_7 angular
      · exact argument_bound_upper_3_8 angular
      · exact argument_bound_upper_3_9 angular
      · exact argument_bound_upper_3_10 angular
      · exact argument_bound_upper_3_11 angular
      · exact argument_bound_upper_3_12 angular
      · exact argument_bound_upper_3_13 angular
      · exact argument_bound_upper_3_14 angular
      · exact argument_bound_upper_3_15 angular
      · exact argument_bound_upper_4_0 angular
      · exact argument_bound_upper_4_1 angular
      · exact argument_bound_upper_4_2 angular
      · exact argument_bound_upper_4_3 angular
      · exact argument_bound_upper_4_4 angular
      · exact argument_bound_upper_4_5 angular
      · exact argument_bound_upper_4_6 angular
      · exact argument_bound_upper_4_7 angular
      · exact argument_bound_upper_4_8 angular
      · exact argument_bound_upper_4_9 angular
      · exact argument_bound_upper_4_10 angular
      · exact argument_bound_upper_4_11 angular
      · exact argument_bound_upper_4_12 angular
      · exact argument_bound_upper_4_13 angular
      · exact argument_bound_upper_4_14 angular
      · exact argument_bound_upper_4_15 angular
      · exact argument_bound_upper_5_0 angular
      · exact argument_bound_upper_5_1 angular
      · exact argument_bound_upper_5_2 angular
      · exact argument_bound_upper_5_3 angular
      · exact argument_bound_upper_5_4 angular
      · exact argument_bound_upper_5_5 angular
      · exact argument_bound_upper_5_6 angular
      · exact argument_bound_upper_5_7 angular
      · exact argument_bound_upper_5_8 angular
      · exact argument_bound_upper_5_9 angular
      · exact argument_bound_upper_5_10 angular
      · exact argument_bound_upper_5_11 angular
      · exact argument_bound_upper_5_12 angular
      · exact argument_bound_upper_5_13 angular
      · exact argument_bound_upper_5_14 angular
      · exact argument_bound_upper_5_15 angular
  | lower =>
      fin_cases row <;> fin_cases radial
      · exact argument_bound_lower_0_0 angular
      · exact argument_bound_lower_0_1 angular
      · exact argument_bound_lower_0_2 angular
      · exact argument_bound_lower_0_3 angular
      · exact argument_bound_lower_0_4 angular
      · exact argument_bound_lower_0_5 angular
      · exact argument_bound_lower_0_6 angular
      · exact argument_bound_lower_0_7 angular
      · exact argument_bound_lower_0_8 angular
      · exact argument_bound_lower_0_9 angular
      · exact argument_bound_lower_0_10 angular
      · exact argument_bound_lower_0_11 angular
      · exact argument_bound_lower_0_12 angular
      · exact argument_bound_lower_0_13 angular
      · exact argument_bound_lower_0_14 angular
      · exact argument_bound_lower_0_15 angular
      · exact argument_bound_lower_1_0 angular
      · exact argument_bound_lower_1_1 angular
      · exact argument_bound_lower_1_2 angular
      · exact argument_bound_lower_1_3 angular
      · exact argument_bound_lower_1_4 angular
      · exact argument_bound_lower_1_5 angular
      · exact argument_bound_lower_1_6 angular
      · exact argument_bound_lower_1_7 angular
      · exact argument_bound_lower_1_8 angular
      · exact argument_bound_lower_1_9 angular
      · exact argument_bound_lower_1_10 angular
      · exact argument_bound_lower_1_11 angular
      · exact argument_bound_lower_1_12 angular
      · exact argument_bound_lower_1_13 angular
      · exact argument_bound_lower_1_14 angular
      · exact argument_bound_lower_1_15 angular
      · exact argument_bound_lower_2_0 angular
      · exact argument_bound_lower_2_1 angular
      · exact argument_bound_lower_2_2 angular
      · exact argument_bound_lower_2_3 angular
      · exact argument_bound_lower_2_4 angular
      · exact argument_bound_lower_2_5 angular
      · exact argument_bound_lower_2_6 angular
      · exact argument_bound_lower_2_7 angular
      · exact argument_bound_lower_2_8 angular
      · exact argument_bound_lower_2_9 angular
      · exact argument_bound_lower_2_10 angular
      · exact argument_bound_lower_2_11 angular
      · exact argument_bound_lower_2_12 angular
      · exact argument_bound_lower_2_13 angular
      · exact argument_bound_lower_2_14 angular
      · exact argument_bound_lower_2_15 angular
      · exact argument_bound_lower_3_0 angular
      · exact argument_bound_lower_3_1 angular
      · exact argument_bound_lower_3_2 angular
      · exact argument_bound_lower_3_3 angular
      · exact argument_bound_lower_3_4 angular
      · exact argument_bound_lower_3_5 angular
      · exact argument_bound_lower_3_6 angular
      · exact argument_bound_lower_3_7 angular
      · exact argument_bound_lower_3_8 angular
      · exact argument_bound_lower_3_9 angular
      · exact argument_bound_lower_3_10 angular
      · exact argument_bound_lower_3_11 angular
      · exact argument_bound_lower_3_12 angular
      · exact argument_bound_lower_3_13 angular
      · exact argument_bound_lower_3_14 angular
      · exact argument_bound_lower_3_15 angular
      · exact argument_bound_lower_4_0 angular
      · exact argument_bound_lower_4_1 angular
      · exact argument_bound_lower_4_2 angular
      · exact argument_bound_lower_4_3 angular
      · exact argument_bound_lower_4_4 angular
      · exact argument_bound_lower_4_5 angular
      · exact argument_bound_lower_4_6 angular
      · exact argument_bound_lower_4_7 angular
      · exact argument_bound_lower_4_8 angular
      · exact argument_bound_lower_4_9 angular
      · exact argument_bound_lower_4_10 angular
      · exact argument_bound_lower_4_11 angular
      · exact argument_bound_lower_4_12 angular
      · exact argument_bound_lower_4_13 angular
      · exact argument_bound_lower_4_14 angular
      · exact argument_bound_lower_4_15 angular
      · exact argument_bound_lower_5_0 angular
      · exact argument_bound_lower_5_1 angular
      · exact argument_bound_lower_5_2 angular
      · exact argument_bound_lower_5_3 angular
      · exact argument_bound_lower_5_4 angular
      · exact argument_bound_lower_5_5 angular
      · exact argument_bound_lower_5_6 angular
      · exact argument_bound_lower_5_7 angular
      · exact argument_bound_lower_5_8 angular
      · exact argument_bound_lower_5_9 angular
      · exact argument_bound_lower_5_10 angular
      · exact argument_bound_lower_5_11 angular
      · exact argument_bound_lower_5_12 angular
      · exact argument_bound_lower_5_13 angular
      · exact argument_bound_lower_5_14 angular
      · exact argument_bound_lower_5_15 angular

end ChapterVIDRadialTailCenteredCompiledGrid
end PoincareChapterVI
