/- This file is generated by research/generate_chapter_vi_homogeneous_admissibility.py. -/
import PoincareChapterVI.HomogeneousAdmissibility.Initial0
import PoincareChapterVI.HomogeneousAdmissibility.Initial1
import PoincareChapterVI.HomogeneousAdmissibility.Initial2
import PoincareChapterVI.HomogeneousAdmissibility.Initial3
import PoincareChapterVI.HomogeneousAdmissibility.Initial4
import PoincareChapterVI.HomogeneousAdmissibility.Initial5
import PoincareChapterVI.HomogeneousAdmissibility.Initial6
import PoincareChapterVI.HomogeneousAdmissibility.Initial7
import PoincareChapterVI.HomogeneousAdmissibility.Initial8
import PoincareChapterVI.HomogeneousAdmissibility.Initial9
import PoincareChapterVI.HomogeneousAdmissibility.Initial10
import PoincareChapterVI.HomogeneousAdmissibility.Initial11
import PoincareChapterVI.HomogeneousAdmissibility.Initial12
import PoincareChapterVI.HomogeneousAdmissibility.Initial13
import PoincareChapterVI.HomogeneousAdmissibility.Initial14
import PoincareChapterVI.HomogeneousAdmissibility.Initial15
import PoincareChapterVI.HomogeneousAdmissibility.Final0
import PoincareChapterVI.HomogeneousAdmissibility.Final1
import PoincareChapterVI.HomogeneousAdmissibility.Final2
import PoincareChapterVI.HomogeneousAdmissibility.Final3
import PoincareChapterVI.HomogeneousAdmissibility.Final4
import PoincareChapterVI.HomogeneousAdmissibility.Final5
import PoincareChapterVI.HomogeneousAdmissibility.Final6
import PoincareChapterVI.HomogeneousAdmissibility.Final7
import PoincareChapterVI.HomogeneousAdmissibility.Final8
import PoincareChapterVI.HomogeneousAdmissibility.Final9
import PoincareChapterVI.HomogeneousAdmissibility.Final10
import PoincareChapterVI.HomogeneousAdmissibility.Final11
import PoincareChapterVI.HomogeneousAdmissibility.Final12
import PoincareChapterVI.HomogeneousAdmissibility.Final13
import PoincareChapterVI.HomogeneousAdmissibility.Final14
import PoincareChapterVI.HomogeneousAdmissibility.Final15

namespace PoincareChapterVI.ChapterVIDHomogeneousCompiledTable

open ChapterVILeanCompCertBatch
open LeanCompCert.Ports.SignedProductClaims

/-- Every ten-row homogeneous seam artifact remains inside LeanCompCert's 64-bit fragment. -/
theorem referenceAdmissibility : ReferenceAdmissibility where
  shard side shard := by
    cases side with
    | initial =>
      fin_cases shard
      · exact shard_admissible_initial_0
      · exact shard_admissible_initial_1
      · exact shard_admissible_initial_2
      · exact shard_admissible_initial_3
      · exact shard_admissible_initial_4
      · exact shard_admissible_initial_5
      · exact shard_admissible_initial_6
      · exact shard_admissible_initial_7
      · exact shard_admissible_initial_8
      · exact shard_admissible_initial_9
      · exact shard_admissible_initial_10
      · exact shard_admissible_initial_11
      · exact shard_admissible_initial_12
      · exact shard_admissible_initial_13
      · exact shard_admissible_initial_14
      · exact shard_admissible_initial_15
    | final =>
      fin_cases shard
      · exact shard_admissible_final_0
      · exact shard_admissible_final_1
      · exact shard_admissible_final_2
      · exact shard_admissible_final_3
      · exact shard_admissible_final_4
      · exact shard_admissible_final_5
      · exact shard_admissible_final_6
      · exact shard_admissible_final_7
      · exact shard_admissible_final_8
      · exact shard_admissible_final_9
      · exact shard_admissible_final_10
      · exact shard_admissible_final_11
      · exact shard_admissible_final_12
      · exact shard_admissible_final_13
      · exact shard_admissible_final_14
      · exact shard_admissible_final_15

/-- Every signed comparison in every reference artifact is proved by kernel reduction. -/
theorem referenceAllHold (side : ChapterVIDOuterArcSide) (shard : Fin 16) :
    ∀ claim ∈ batchClaims (shardOperations side shard), claim.Holds := by
  cases side with
    | initial =>
      fin_cases shard
      · exact shard_allHold_initial_0
      · exact shard_allHold_initial_1
      · exact shard_allHold_initial_2
      · exact shard_allHold_initial_3
      · exact shard_allHold_initial_4
      · exact shard_allHold_initial_5
      · exact shard_allHold_initial_6
      · exact shard_allHold_initial_7
      · exact shard_allHold_initial_8
      · exact shard_allHold_initial_9
      · exact shard_allHold_initial_10
      · exact shard_allHold_initial_11
      · exact shard_allHold_initial_12
      · exact shard_allHold_initial_13
      · exact shard_allHold_initial_14
      · exact shard_allHold_initial_15
    | final =>
      fin_cases shard
      · exact shard_allHold_final_0
      · exact shard_allHold_final_1
      · exact shard_allHold_final_2
      · exact shard_allHold_final_3
      · exact shard_allHold_final_4
      · exact shard_allHold_final_5
      · exact shard_allHold_final_6
      · exact shard_allHold_final_7
      · exact shard_allHold_final_8
      · exact shard_allHold_final_9
      · exact shard_allHold_final_10
      · exact shard_allHold_final_11
      · exact shard_allHold_final_12
      · exact shard_allHold_final_13
      · exact shard_allHold_final_14
      · exact shard_allHold_final_15

/-- Unconditional verified-program verdict for the reference table.  The larger receipt interface
remains available for independently compiled/native reruns, but is not needed by this theorem. -/
theorem referenceRunVerdict : ReferenceRunVerdict referenceAdmissibility where
  returnsZero side shard :=
    ChapterVILeanCompCertIntervalBridge.returns_zero_of_allHold
      (shardArtifactName side shard) (batchClaims (shardOperations side shard))
      (referenceAdmissibility.shard side shard) (referenceAllHold side shard)

/-- The reference table and analytic selector unconditionally produce both collar derivative
certificates. -/
theorem exists_anchoredModel_with_referenceDerivativeCertificates
    (massProduct : ℂ) (b d : ℤ) :
    ∃ model : ChapterVIDAnchoredConnectorModel massProduct b d,
      ChapterVIDConnectorFactorCrossing.OrientedRealDerivativeCertificate
          model.toChapterVIDPrincipalConnectorModel .initial ∧
        ChapterVIDConnectorFactorCrossing.OrientedRealDerivativeCertificate
          model.toChapterVIDPrincipalConnectorModel .final :=
  exists_anchoredModel_with_orientedRealDerivativeCertificates
    referenceAdmissibility referenceRunVerdict massProduct b d

end PoincareChapterVI.ChapterVIDHomogeneousCompiledTable
