/- This file is generated by research/generate_chapter_vi_connector_factor_second_derivative_admissibility.py. -/
import PoincareChapterVI.ConnectorFactorSecondDerivativeAdmissibility.Initial0
import PoincareChapterVI.ConnectorFactorSecondDerivativeAdmissibility.Initial1
import PoincareChapterVI.ConnectorFactorSecondDerivativeAdmissibility.Initial2
import PoincareChapterVI.ConnectorFactorSecondDerivativeAdmissibility.Initial3
import PoincareChapterVI.ConnectorFactorSecondDerivativeAdmissibility.Initial4
import PoincareChapterVI.ConnectorFactorSecondDerivativeAdmissibility.Initial5
import PoincareChapterVI.ConnectorFactorSecondDerivativeAdmissibility.Initial6
import PoincareChapterVI.ConnectorFactorSecondDerivativeAdmissibility.Final0
import PoincareChapterVI.ConnectorFactorSecondDerivativeAdmissibility.Final1
import PoincareChapterVI.ConnectorFactorSecondDerivativeAdmissibility.Final2

namespace PoincareChapterVI.ChapterVIDConnectorFactorSecondDerivativeReference

open ChapterVILeanCompCertBatch
open LeanCompCert.Ports.SignedProductClaims

/-- Every three-cell curvature artifact remains inside LeanCompCert's 64-bit fragment. -/
theorem shard_admissible (side : ChapterVIDOuterArcSide)
    (shard : Fin (shardCount side)) :
    Admissible (batchClaims (shardOperations side shard)) := by
  cases side with
  | initial =>
    fin_cases shard
    · exact shard_admissible_initial_0
    · exact shard_admissible_initial_1
    · exact shard_admissible_initial_2
    · exact shard_admissible_initial_3
    · exact shard_admissible_initial_4
    · exact shard_admissible_initial_5
    · exact shard_admissible_initial_6
  | final =>
    fin_cases shard
    · exact shard_admissible_final_0
    · exact shard_admissible_final_1
    · exact shard_admissible_final_2

end PoincareChapterVI.ChapterVIDConnectorFactorSecondDerivativeReference
