/- This file is generated by research/generate_chapter_vi_clustered_radial_grid.py. -/
import PoincareChapterVI.ChapterVILeanCompCertProposals
import PoincareChapterVI.ChapterVINonuniformGrid

namespace PoincareChapterVI

open ChapterVILeanCompCertBatch
open LeanCompCert.Ports.SignedProductClaims
open scoped unitInterval

namespace ChapterVIDRadialClusteredCompiledGrid

abbrev Interval := ChapterVISignedDyadicInterval 20

def qD : Interval := ⟨915, 917⟩
def xAbs : Interval := ⟨28170, 28171⟩
def qDSixthRoot : Interval := ⟨324139, 324263⟩
def collisionRadius : Interval := ⟨314047, 314053⟩

def endpoint : ChapterVIDRadialTrace.EndpointTrace (precision := 20) :=
  ChapterVILeanCompCertProposals.radialEndpointTrace
    qD qDSixthRoot xAbs collisionRadius

def inputData : Array Interval := #[
  ⟨0, 108383⟩,
  ⟨108382, 209028⟩,
  ⟨209027, 302221⟩,
  ⟨302220, 388249⟩,
  ⟨388248, 467398⟩,
  ⟨467397, 539956⟩,
  ⟨539955, 606208⟩,
  ⟨606208, 666442⟩,
  ⟨666441, 720944⟩,
  ⟨720943, 770001⟩,
  ⟨770000, 813898⟩,
  ⟨813897, 852924⟩,
  ⟨852923, 887364⟩,
  ⟨887363, 917504⟩,
  ⟨917504, 943633⟩,
  ⟨943632, 966036⟩,
  ⟨966035, 984999⟩,
  ⟨984998, 1000810⟩,
  ⟨1000809, 1013755⟩,
  ⟨1013754, 1024120⟩,
  ⟨1024119, 1032192⟩,
  ⟨1032192, 1038259⟩,
  ⟨1038258, 1042606⟩,
  ⟨1042605, 1045519⟩,
  ⟨1045518, 1047287⟩,
  ⟨1047286, 1048194⟩,
  ⟨1048193, 1048529⟩,
  ⟨1048528, 1048576⟩]

def input (i : Fin 28) : Interval := inputData[i]

def qCubeRootData : Array Interval := #[
  ⟨1011160, 1048576⟩,
  ⟨973747, 1011162⟩,
  ⟨936338, 973749⟩,
  ⟨898932, 936340⟩,
  ⟨861530, 898934⟩,
  ⟨824134, 861533⟩,
  ⟨786744, 824137⟩,
  ⟨749361, 786747⟩,
  ⟨711988, 749365⟩,
  ⟨674624, 711991⟩,
  ⟨637276, 674628⟩,
  ⟨599943, 637280⟩,
  ⟨562633, 599948⟩,
  ⟨525351, 562639⟩,
  ⟨488106, 525357⟩,
  ⟨450910, 488115⟩,
  ⟨413785, 450919⟩,
  ⟨376756, 413795⟩,
  ⟨339866, 376768⟩,
  ⟨303193, 339881⟩,
  ⟨266857, 303211⟩,
  ⟨231076, 266876⟩,
  ⟨196293, 231105⟩,
  ⟨163413, 196334⟩,
  ⟨134276, 163472⟩,
  ⟨112528, 134361⟩,
  ⟨101850, 112648⟩,
  ⟨100200, 101995⟩]

def qCubeRoot (i : Fin 28) : Interval := qCubeRootData[i]

def qSixthRootData : Array Interval := #[
  ⟨1029698, 1048576⟩,
  ⟨1010469, 1029700⟩,
  ⟨990869, 1010471⟩,
  ⟨970875, 990871⟩,
  ⟨950463, 970877⟩,
  ⟨929606, 950466⟩,
  ⟨908273, 929608⟩,
  ⟨886432, 908276⟩,
  ⟨864044, 886435⟩,
  ⟨841067, 864047⟩,
  ⟨817454, 841071⟩,
  ⟨793149, 817458⟩,
  ⟨768090, 793153⟩,
  ⟨742207, 768095⟩,
  ⟨715414, 742211⟩,
  ⟨687614, 715420⟩,
  ⟨658699, 687622⟩,
  ⟨628535, 658708⟩,
  ⟨596971, 628546⟩,
  ⟨563843, 596985⟩,
  ⟨528980, 563861⟩,
  ⟨492240, 528998⟩,
  ⟨453684, 492272⟩,
  ⟨413948, 453730⟩,
  ⟨375232, 414021⟩,
  ⟨343505, 375351⟩,
  ⟨326803, 343683⟩,
  ⟨324139, 327032⟩]

def qSixthRoot (i : Fin 28) : Interval := qSixthRootData[i]


def trace (i : Fin 28) : ChapterVIDRadialTrace.Trace endpoint (input i) :=
  ChapterVILeanCompCertProposals.radialTrace endpoint (input i)
    (qCubeRoot i) (qSixthRoot i)

noncomputable def operations : List (DyadicOperation 20) :=
  endpoint.operations ++ (List.ofFn fun i : Fin 28 => (trace i).operations).flatten

theorem endpoint_operations_mem (operation : DyadicOperation 20)
    (hoperation : operation ∈ endpoint.operations) : operation ∈ operations := by
  simp [operations, hoperation]

theorem trace_operations_mem (i : Fin 28) (operation : DyadicOperation 20)
    (hoperation : operation ∈ (trace i).operations) : operation ∈ operations := by
  rw [operations]
  simp only [List.mem_append, List.mem_flatten]
  right
  exact ⟨(trace i).operations, List.mem_ofFn.mpr ⟨i, rfl⟩, hoperation⟩

theorem endpoint_valid : endpoint.Valid := by
  unfold ChapterVIDRadialTrace.EndpointTrace.Valid
    ChapterVILeanCompCertRoots.CubicRootTrace.Valid
    ChapterVILeanCompCertRoots.SixthRootTrace.Valid
  decide +kernel

theorem trace_valid (i : Fin 28) : (trace i).Valid := by
  unfold ChapterVIDRadialTrace.Trace.Valid
    ChapterVILeanCompCertRoots.CubicRootTrace.Valid
    ChapterVILeanCompCertRoots.SixthRootTrace.Valid
  fin_cases i <;> decide +kernel

set_option maxRecDepth 100000 in
theorem operations_admissible : Admissible (batchClaims operations) := by
  refine ⟨?_, ?_, ?_⟩
  · decide +kernel
  · decide +kernel
  · decide +kernel

set_option maxRecDepth 100000 in
theorem operations_returns_zero :
    (batchComputation "chapter-vi-d-radial-clustered-grid-20" operations).Returns
      ((0 : Nat) : Int) := by
  decide +kernel

theorem qD_contains : qD.Contains chapterVIDCriticalParameterModulus := by
  obtain ⟨hlower, hupper⟩ := chapterVIDCriticalParameterModulus_tight_bounds
  constructor
  · exact (by norm_num [qD, ChapterVISignedDyadicInterval.toRealInterval,
      ChapterVISignedDyadicInterval.scale] :
        ((qD.lower : ℝ) / ChapterVISignedDyadicInterval.scale 20) ≤ 8734 / 10000000).trans hlower
  · exact hupper.trans (by norm_num [qD, ChapterVISignedDyadicInterval.toRealInterval,
      ChapterVISignedDyadicInterval.scale] :
        (8736 / 10000000 : ℝ) ≤ (qD.upper : ℝ) / ChapterVISignedDyadicInterval.scale 20)

theorem xAbs_contains : xAbs.Contains (-chapterVIDRoot) := by
  constructor
  · change (28170 : ℝ) / (2 : ℝ) ^ 20 ≤ -chapterVIDRoot
    exact (by norm_num : (28170 : ℝ) / (2 : ℝ) ^ 20 ≤ 26865395 / 1000000000).trans
      (by linarith [chapterVIDRoot_fine_mem.2])
  · change -chapterVIDRoot ≤ (28171 : ℝ) / (2 : ℝ) ^ 20
    exact (by linarith [chapterVIDRoot_fine_mem.1] :
      -chapterVIDRoot ≤ 26865396 / 1000000000).trans (by norm_num)

/-- The shared compiled endpoint trace gives a reusable dyadic enclosure of the exact collision
radius. Connector endpoint bounds consume this result without reevaluating a cubic root. -/
theorem collisionRadius_contains :
    collisionRadius.Contains ‖chapterVIDCollisionLift‖ := by
  have hsound : ∀ operation ∈ endpoint.collisionTrace.operations,
      operation.Sound := by
    intro operation hoperation
    exact allSound_of_returns_zero "chapter-vi-d-radial-clustered-grid-20"
      operations operations_admissible operations_returns_zero operation
      (endpoint_operations_mem operation
        (by simp [ChapterVIDRadialTrace.EndpointTrace.operations, hoperation]))
  have hroot := endpoint.collisionTrace.output_contains_of_valid endpoint_valid.2
    hsound (by linarith [chapterVIDRoot_lt_zero]) xAbs_contains
  rw [← chapterVIDCollisionRadius_eq_rpow] at hroot
  exact hroot

theorem correction_contains :
    endpoint.correction.Contains chapterVIDCertificateContourCorrection := by
  apply endpoint.correction_contains_of_allSound endpoint_valid
  · intro operation hoperation
    exact allSound_of_returns_zero "chapter-vi-d-radial-clustered-grid-20"
      operations operations_admissible operations_returns_zero operation
      (endpoint_operations_mem operation hoperation)
  · exact qD_contains
  · exact xAbs_contains

theorem input_contains_of_mem_cell (i : Fin 28) {parameter : I}
    (hlower : (chapterVICubicClusterNode 28 i : ℝ) ≤ parameter)
    (hupper : (parameter : ℝ) ≤ chapterVICubicClusterNode 28 (i + 1)) :
    (input i).Contains (parameter : ℝ) := by
  fin_cases i <;>
    norm_num [input, inputData, chapterVICubicClusterNode,
      ChapterVISignedDyadicInterval.Contains,
      ChapterVISignedDyadicInterval.toRealInterval,
      ChapterVISignedDyadicInterval.scale] at hlower hupper ⊢ <;>
    constructor <;> linarith

theorem outputs_contain_cell (i : Fin 28) {parameter : I}
    (hlower : (chapterVICubicClusterNode 28 i : ℝ) ≤ parameter)
    (hupper : (parameter : ℝ) ≤ chapterVICubicClusterNode 28 (i + 1)) :
    (trace i).qCubeRoot.Contains
        (chapterVIDCertificateParameter parameter ^ ((3 : ℝ)⁻¹)) ∧
      (trace i).radius.Contains (chapterVIDCertificateContourRadius parameter) := by
  apply (trace i).outputs_contain_of_allSound (trace_valid i)
  · intro operation hoperation
    exact allSound_of_returns_zero "chapter-vi-d-radial-clustered-grid-20"
      operations operations_admissible operations_returns_zero operation
      (trace_operations_mem i operation hoperation)
  · exact input_contains_of_mem_cell i hlower hupper
  · exact qD_contains
  · exact correction_contains

theorem exists_outputs_contain (parameter : I) :
    ∃ i : Fin 28,
      (trace i).qCubeRoot.Contains
          (chapterVIDCertificateParameter parameter ^ ((3 : ℝ)⁻¹)) ∧
        (trace i).radius.Contains (chapterVIDCertificateContourRadius parameter) := by
  rcases exists_mem_cubicClusterCell 28 (by norm_num) parameter with
    ⟨i, hi, hlower, hupper⟩
  exact ⟨⟨i, hi⟩, outputs_contain_cell ⟨i, hi⟩ hlower hupper⟩

end ChapterVIDRadialClusteredCompiledGrid

end PoincareChapterVI
