/- This file is generated by research/generate_chapter_vi_radial_grid.py. -/
import PoincareChapterVI.ChapterVIDRadialTrace
import PoincareChapterVI.ChapterVIUnitSquareGrid

namespace PoincareChapterVI

open ChapterVILeanCompCertBatch
open LeanCompCert.Ports.SignedProductClaims
open scoped unitInterval

namespace ChapterVIDRadialCompiledGrid

abbrev Interval := ChapterVIDRadialTrace.Interval 20

def qD : Interval := ⟨915, 917⟩
def qDSixthRoot : Interval := ⟨324139, 324263⟩
def xAbs : Interval := ⟨28170, 28171⟩
def collisionRadius : Interval := ⟨314047, 314053⟩
def qDSixthInv : Interval := ⟨3390801, 3392100⟩
def correction : Interval := ⟨1015540, 1015949⟩

def endpoint : ChapterVIDRadialTrace.EndpointTrace (precision := 20) where
  qD := qD
  qDSixthRoot := qDSixthRoot
  qDSixthTrace := {
    lowerPower := { square := ⟨100198, 100199⟩, cube := ⟨30973, 30974⟩, sixth := ⟨914, 915⟩ }
    upperPower := { square := ⟨100275, 100276⟩, cube := ⟨31009, 31010⟩, sixth := ⟨917, 918⟩ } }
  xAbs := xAbs
  collisionRadius := collisionRadius
  collisionTrace := {
    lowerPower := { square := ⟨94056, 94057⟩, cube := ⟨28169, 28170⟩ }
    upperPower := { square := ⟨94060, 94061⟩, cube := ⟨28171, 28172⟩ } }
  qDSixthInv := qDSixthInv
  correction := correction

def input (i : Fin 17) : Interval :=
  ⟨(i.val * 65536 : ℕ), (min (i.val + 1) 16 * 65536 : ℕ)⟩

def qDeltaProduct : Fin 17 → Interval := ![
  ⟨-65479, 0⟩,
  ⟨-130958, -65478⟩,
  ⟨-196437, -130957⟩,
  ⟨-261916, -196436⟩,
  ⟨-327395, -261914⟩,
  ⟨-392873, -327393⟩,
  ⟨-458352, -392872⟩,
  ⟨-523831, -458350⟩,
  ⟨-589310, -523829⟩,
  ⟨-654789, -589308⟩,
  ⟨-720267, -654786⟩,
  ⟨-785746, -720265⟩,
  ⟨-851225, -785744⟩,
  ⟨-916704, -851222⟩,
  ⟨-982183, -916701⟩,
  ⟨-1047661, -982180⟩,
  ⟨-1047661, -1047659⟩]

def qCubeRoot : Fin 17 → Interval := ![
  ⟨1026278, 1048576⟩,
  ⟨1002968, 1026280⟩,
  ⟨978520, 1002969⟩,
  ⟨952786, 978522⟩,
  ⟨925581, 952788⟩,
  ⟨896676, 925583⟩,
  ⟨865775, 896677⟩,
  ⟨832496, 865778⟩,
  ⟨796320, 832499⟩,
  ⟨756519, 796323⟩,
  ⟨712023, 756522⟩,
  ⟨661136, 712025⟩,
  ⟨600914, 661140⟩,
  ⟨525351, 600919⟩,
  ⟨417933, 525357⟩,
  ⟨100200, 417941⟩,
  ⟨100200, 100276⟩]

def qCubeLowerSquare : Fin 17 → Interval := ![
  ⟨1004454, 1004455⟩,
  ⟨959343, 959344⟩,
  ⟨913144, 913145⟩,
  ⟨865746, 865747⟩,
  ⟨817012, 817013⟩,
  ⟨766780, 766781⟩,
  ⟨714842, 714843⟩,
  ⟨660943, 660944⟩,
  ⟨604749, 604750⟩,
  ⟨545807, 545808⟩,
  ⟨483490, 483491⟩,
  ⟨416851, 416852⟩,
  ⟨344369, 344370⟩,
  ⟨263208, 263209⟩,
  ⟨166576, 166577⟩,
  ⟨9574, 9575⟩,
  ⟨9574, 9575⟩]

def qCubeLowerCube : Fin 17 → Interval := ![
  ⟨983094, 983096⟩,
  ⟨917616, 917618⟩,
  ⟨852136, 852138⟩,
  ⟨786657, 786659⟩,
  ⟨721178, 721180⟩,
  ⟨655701, 655703⟩,
  ⟨590221, 590223⟩,
  ⟨524742, 524744⟩,
  ⟨459264, 459266⟩,
  ⟨393784, 393786⟩,
  ⟨328308, 328309⟩,
  ⟨262828, 262829⟩,
  ⟨197349, 197351⟩,
  ⟨131870, 131872⟩,
  ⟨66392, 66393⟩,
  ⟨914, 915⟩,
  ⟨914, 915⟩]

def qCubeUpperSquare : Fin 17 → Interval := ![
  ⟨1048576, 1048576⟩,
  ⟨1004458, 1004459⟩,
  ⟨959345, 959346⟩,
  ⟨913148, 913149⟩,
  ⟨865750, 865751⟩,
  ⟨817016, 817017⟩,
  ⟨766782, 766783⟩,
  ⟨714847, 714848⟩,
  ⟨660948, 660949⟩,
  ⟨604753, 604754⟩,
  ⟨545812, 545813⟩,
  ⟨483493, 483494⟩,
  ⟨416856, 416857⟩,
  ⟨344375, 344376⟩,
  ⟨263214, 263215⟩,
  ⟨166582, 166583⟩,
  ⟨9589, 9590⟩]

def qCubeUpperCube : Fin 17 → Interval := ![
  ⟨1048576, 1048576⟩,
  ⟨983100, 983102⟩,
  ⟨917619, 917620⟩,
  ⟨852141, 852143⟩,
  ⟨786663, 786665⟩,
  ⟨721183, 721185⟩,
  ⟨655704, 655706⟩,
  ⟨590227, 590229⟩,
  ⟨524748, 524750⟩,
  ⟨459269, 459271⟩,
  ⟨393790, 393791⟩,
  ⟨328311, 328312⟩,
  ⟨262832, 262834⟩,
  ⟨197354, 197356⟩,
  ⟨131875, 131876⟩,
  ⟨66396, 66397⟩,
  ⟨917, 918⟩]

def qSixthRoot : Fin 17 → Interval := ![
  ⟨1037367, 1048576⟩,
  ⟨1025518, 1037369⟩,
  ⟨1012942, 1025520⟩,
  ⟨999534, 1012944⟩,
  ⟨985160, 999536⟩,
  ⟨969656, 985162⟩,
  ⟨952801, 969657⟩,
  ⟨934310, 952803⟩,
  ⟨913784, 934312⟩,
  ⟨890656, 913786⟩,
  ⟨864066, 890658⟩,
  ⟨832617, 864068⟩,
  ⟨793790, 832620⟩,
  ⟨742207, 793795⟩,
  ⟨661992, 742211⟩,
  ⟨324139, 662000⟩,
  ⟨324139, 324263⟩]

def qSixthLowerSquare : Fin 17 → Interval := ![
  ⟨1026277, 1026278⟩,
  ⟨1002967, 1002968⟩,
  ⟨978518, 978519⟩,
  ⟨952785, 952786⟩,
  ⟨925579, 925580⟩,
  ⟨896675, 896676⟩,
  ⟨865773, 865774⟩,
  ⟨832495, 832496⟩,
  ⟨796319, 796320⟩,
  ⟨756519, 756520⟩,
  ⟨712022, 712023⟩,
  ⟨661135, 661136⟩,
  ⟨600912, 600913⟩,
  ⟨525351, 525352⟩,
  ⟨417931, 417932⟩,
  ⟨100198, 100199⟩,
  ⟨100198, 100199⟩]

def qSixthLowerCube : Fin 17 → Interval := ![
  ⟨1015306, 1015308⟩,
  ⟨980911, 980913⟩,
  ⟨945264, 945266⟩,
  ⟨908223, 908225⟩,
  ⟨869601, 869603⟩,
  ⟨829187, 829189⟩,
  ⟨786694, 786696⟩,
  ⟨741775, 741777⟩,
  ⟨693954, 693955⟩,
  ⟨642584, 642585⟩,
  ⟨586732, 586734⟩,
  ⟨524971, 524973⟩,
  ⟨454900, 454902⟩,
  ⟨371855, 371857⟩,
  ⟨263850, 263851⟩,
  ⟨30973, 30974⟩,
  ⟨30973, 30974⟩]

def qSixthLowerSixth : Fin 17 → Interval := ![
  ⟨983091, 983096⟩,
  ⟨917612, 917617⟩,
  ⟨852130, 852135⟩,
  ⟨786656, 786660⟩,
  ⟨721174, 721178⟩,
  ⟨655699, 655703⟩,
  ⟨590217, 590221⟩,
  ⟨524740, 524744⟩,
  ⟨459262, 459265⟩,
  ⟨393785, 393787⟩,
  ⟨328306, 328309⟩,
  ⟨262827, 262830⟩,
  ⟨197347, 197350⟩,
  ⟨131870, 131872⟩,
  ⟨66391, 66393⟩,
  ⟨914, 915⟩,
  ⟨914, 915⟩]

def qSixthUpperSquare : Fin 17 → Interval := ![
  ⟨1048576, 1048576⟩,
  ⟨1026281, 1026282⟩,
  ⟨1002970, 1002971⟩,
  ⟨978522, 978523⟩,
  ⟨952789, 952790⟩,
  ⟨925583, 925584⟩,
  ⟨896677, 896678⟩,
  ⟨865777, 865778⟩,
  ⟨832499, 832500⟩,
  ⟨796322, 796323⟩,
  ⟨756522, 756523⟩,
  ⟨712026, 712027⟩,
  ⟨661140, 661141⟩,
  ⟨600920, 600921⟩,
  ⟨525357, 525358⟩,
  ⟨417942, 417943⟩,
  ⟨100275, 100276⟩]

def qSixthUpperCube : Fin 17 → Interval := ![
  ⟨1048576, 1048576⟩,
  ⟨1015312, 1015314⟩,
  ⟨980916, 980918⟩,
  ⟨945270, 945272⟩,
  ⟨908228, 908230⟩,
  ⟨869607, 869609⟩,
  ⟨829190, 829192⟩,
  ⟨786700, 786702⟩,
  ⟨741781, 741782⟩,
  ⟨693958, 693960⟩,
  ⟨642588, 642589⟩,
  ⟨586737, 586739⟩,
  ⟨524977, 524978⟩,
  ⟨454909, 454911⟩,
  ⟨371862, 371863⟩,
  ⟨263860, 263861⟩,
  ⟨31009, 31010⟩]

def qSixthUpperSixth : Fin 17 → Interval := ![
  ⟨1048576, 1048576⟩,
  ⟨983103, 983108⟩,
  ⟨917621, 917626⟩,
  ⟨852141, 852146⟩,
  ⟨786665, 786669⟩,
  ⟨721184, 721188⟩,
  ⟨655704, 655708⟩,
  ⟨590226, 590230⟩,
  ⟨524748, 524751⟩,
  ⟨459268, 459271⟩,
  ⟨393790, 393792⟩,
  ⟨328312, 328315⟩,
  ⟨262833, 262835⟩,
  ⟨197355, 197358⟩,
  ⟨131875, 131877⟩,
  ⟨66396, 66398⟩,
  ⟨917, 918⟩]

def correctionDeltaProduct : Fin 17 → Interval := ![
  ⟨-2065, 0⟩,
  ⟨-4130, -2039⟩,
  ⟨-6195, -4078⟩,
  ⟨-8259, -6117⟩,
  ⟨-10324, -8156⟩,
  ⟨-12389, -10195⟩,
  ⟨-14454, -12235⟩,
  ⟨-16518, -14274⟩,
  ⟨-18583, -16313⟩,
  ⟨-20648, -18352⟩,
  ⟨-22713, -20391⟩,
  ⟨-24777, -22431⟩,
  ⟨-26842, -24470⟩,
  ⟨-28907, -26509⟩,
  ⟨-30972, -28548⟩,
  ⟨-33036, -30587⟩,
  ⟨-33036, -32627⟩]

def radius : Fin 17 → Interval := ![
  ⟨1035324, 1048576⟩,
  ⟨1021478, 1035352⟩,
  ⟨1006957, 1021532⟩,
  ⟨991661, 1007035⟩,
  ⟨975460, 991762⟩,
  ⟨958199, 975584⟩,
  ⟨939667, 958343⟩,
  ⟨919592, 939833⟩,
  ⟨897589, 919777⟩,
  ⟨873117, 897794⟩,
  ⟨845349, 873338⟩,
  ⟨812942, 845584⟩,
  ⟨773470, 813190⟩,
  ⟨721745, 773728⟩,
  ⟨642438, 722004⟩,
  ⟨313926, 642690⟩,
  ⟨313926, 314174⟩]


def trace (i : Fin 17) : ChapterVIDRadialTrace.Trace endpoint (input i) where
  qDeltaProduct := qDeltaProduct i
  qCubeRoot := qCubeRoot i
  qCubeTrace := {
    lowerPower := { square := qCubeLowerSquare i, cube := qCubeLowerCube i }
    upperPower := { square := qCubeUpperSquare i, cube := qCubeUpperCube i } }
  qSixthRoot := qSixthRoot i
  qSixthTrace := {
    lowerPower := { square := qSixthLowerSquare i, cube := qSixthLowerCube i, sixth := qSixthLowerSixth i }
    upperPower := { square := qSixthUpperSquare i, cube := qSixthUpperCube i, sixth := qSixthUpperSixth i } }
  correctionDeltaProduct := correctionDeltaProduct i
  radius := radius i

def operations : List (DyadicOperation 20) :=
  endpoint.operations ++ (List.ofFn fun i : Fin 17 => (trace i).operations).flatten

theorem endpoint_operations_mem (operation : DyadicOperation 20)
    (hoperation : operation ∈ endpoint.operations) : operation ∈ operations := by
  simp [operations, hoperation]

theorem trace_operations_mem (i : Fin 17) (operation : DyadicOperation 20)
    (hoperation : operation ∈ (trace i).operations) : operation ∈ operations := by
  rw [operations, List.mem_append, List.mem_flatten]
  exact Or.inr ⟨(trace i).operations, List.mem_ofFn.mpr ⟨i, rfl⟩, hoperation⟩

theorem endpoint_valid : endpoint.Valid := by
  unfold ChapterVIDRadialTrace.EndpointTrace.Valid
    ChapterVILeanCompCertRoots.CubicRootTrace.Valid
    ChapterVILeanCompCertRoots.SixthRootTrace.Valid
  decide +kernel

theorem trace_valid (i : Fin 17) : (trace i).Valid := by
  unfold ChapterVIDRadialTrace.Trace.Valid
    ChapterVILeanCompCertRoots.CubicRootTrace.Valid
    ChapterVILeanCompCertRoots.SixthRootTrace.Valid
  fin_cases i <;> decide +kernel

theorem operations_admissible : Admissible (batchClaims operations) := by
  refine ⟨?_, ?_, ?_⟩
  · decide +kernel
  · decide +kernel
  · decide +kernel

set_option maxRecDepth 100000 in
theorem operations_returns_zero :
    (batchComputation "chapter-vi-d-radial-grid-20" operations).Returns
      ((0 : Nat) : Int) := by
  decide +kernel

theorem qD_contains : qD.Contains chapterVIDCriticalParameterModulus := by
  obtain ⟨hlower, hupper⟩ := chapterVIDCriticalParameterModulus_tight_bounds
  constructor
  · exact (by norm_num [qD, ChapterVISignedDyadicInterval.toRealInterval,
      ChapterVISignedDyadicInterval.scale] :
        ((qD.lower : ℝ) / ChapterVISignedDyadicInterval.scale 20) ≤ 8734 / 10000000).trans hlower
  · exact hupper.trans (by norm_num [qD, ChapterVISignedDyadicInterval.toRealInterval,
      ChapterVISignedDyadicInterval.scale] :
        (8736 / 10000000 : ℝ) ≤ (qD.upper : ℝ) / ChapterVISignedDyadicInterval.scale 20)

theorem xAbs_contains : xAbs.Contains (-chapterVIDRoot) := by
  constructor
  · change (xAbs.lower : ℝ) / ChapterVISignedDyadicInterval.scale 20 ≤ -chapterVIDRoot
    exact (by norm_num [xAbs, ChapterVISignedDyadicInterval.scale] :
      (xAbs.lower : ℝ) / ChapterVISignedDyadicInterval.scale 20 ≤
        26865395 / 1000000000).trans
        (by linarith [chapterVIDRoot_fine_mem.2])
  · change -chapterVIDRoot ≤ (xAbs.upper : ℝ) / ChapterVISignedDyadicInterval.scale 20
    exact (by linarith [chapterVIDRoot_fine_mem.1] :
      -chapterVIDRoot ≤ 26865396 / 1000000000).trans
      (by norm_num [xAbs, ChapterVISignedDyadicInterval.scale])

theorem correction_contains :
    endpoint.correction.Contains chapterVIDCertificateContourCorrection := by
  apply endpoint.correction_contains_of_allSound endpoint_valid
  · intro operation hoperation
    exact allSound_of_returns_zero "chapter-vi-d-radial-grid-20"
      operations operations_admissible operations_returns_zero operation
      (endpoint_operations_mem operation hoperation)
  · exact qD_contains
  · exact xAbs_contains

theorem input_contains_of_mem_cell (i : Fin 17) {parameter : I}
    (hparameter : parameter ∈ chapterVIUnitGridCell 15 i) :
    (input i).Contains (parameter : ℝ) := by
  have hbounds := hparameter
  simp only [chapterVIUnitGridCell, Set.mem_ofPred_eq] at hbounds
  constructor
  · change (((i.val * 65536 : ℕ) : ℤ) : ℝ) / (2 : ℝ) ^ 20 ≤ (parameter : ℝ)
    convert hbounds.1 using 1 <;> norm_num <;> ring
  · change (parameter : ℝ) ≤
      (((min (i.val + 1) 16 * 65536 : ℕ) : ℤ) : ℝ) / (2 : ℝ) ^ 20
    convert hbounds.2 using 1 <;> norm_num <;> ring

theorem outputs_contain_cell (i : Fin 17) {parameter : I}
    (hparameter : parameter ∈ chapterVIUnitGridCell 15 i) :
    (trace i).qCubeRoot.Contains
        (chapterVIDCertificateParameter parameter ^ ((3 : ℝ)⁻¹)) ∧
      (trace i).radius.Contains (chapterVIDCertificateContourRadius parameter) := by
  apply (trace i).outputs_contain_of_allSound (trace_valid i)
  · intro operation hoperation
    exact allSound_of_returns_zero "chapter-vi-d-radial-grid-20"
      operations operations_admissible operations_returns_zero operation
      (trace_operations_mem i operation hoperation)
  · exact input_contains_of_mem_cell i hparameter
  · exact qD_contains
  · exact correction_contains

/-- Every radial parameter belongs to a cell whose one compiled verdict encloses both source
coordinates needed by the outer-arc formula. -/
theorem exists_outputs_contain (parameter : I) :
    ∃ i : Fin 17,
      (trace i).qCubeRoot.Contains
          (chapterVIDCertificateParameter parameter ^ ((3 : ℝ)⁻¹)) ∧
        (trace i).radius.Contains (chapterVIDCertificateContourRadius parameter) := by
  let i := chapterVIUnitGridIndex 15 parameter
  exact ⟨i, outputs_contain_cell i (chapterVIUnitGridIndex_mem_cell 15 parameter)⟩

end ChapterVIDRadialCompiledGrid

end PoincareChapterVI

