/- This file is generated by research/generate_chapter_vi_connector_factor_admissibility.py. -/
import PoincareChapterVI.ConnectorFactorAdmissibility.Initial0
import PoincareChapterVI.ConnectorFactorAdmissibility.Initial1
import PoincareChapterVI.ConnectorFactorAdmissibility.Initial2
import PoincareChapterVI.ConnectorFactorAdmissibility.Initial3
import PoincareChapterVI.ConnectorFactorAdmissibility.Initial4
import PoincareChapterVI.ConnectorFactorAdmissibility.Initial5
import PoincareChapterVI.ConnectorFactorAdmissibility.Initial6
import PoincareChapterVI.ConnectorFactorAdmissibility.Initial7
import PoincareChapterVI.ConnectorFactorAdmissibility.Initial8
import PoincareChapterVI.ConnectorFactorAdmissibility.Initial9
import PoincareChapterVI.ConnectorFactorAdmissibility.Initial10
import PoincareChapterVI.ConnectorFactorAdmissibility.Initial11
import PoincareChapterVI.ConnectorFactorAdmissibility.Initial12
import PoincareChapterVI.ConnectorFactorAdmissibility.Initial13
import PoincareChapterVI.ConnectorFactorAdmissibility.Initial14
import PoincareChapterVI.ConnectorFactorAdmissibility.Initial15
import PoincareChapterVI.ConnectorFactorAdmissibility.Initial16
import PoincareChapterVI.ConnectorFactorAdmissibility.Initial17
import PoincareChapterVI.ConnectorFactorAdmissibility.Initial18
import PoincareChapterVI.ConnectorFactorAdmissibility.Initial19
import PoincareChapterVI.ConnectorFactorAdmissibility.Initial20
import PoincareChapterVI.ConnectorFactorAdmissibility.Initial21
import PoincareChapterVI.ConnectorFactorAdmissibility.Initial22
import PoincareChapterVI.ConnectorFactorAdmissibility.Initial23
import PoincareChapterVI.ConnectorFactorAdmissibility.Initial24
import PoincareChapterVI.ConnectorFactorAdmissibility.Initial25
import PoincareChapterVI.ConnectorFactorAdmissibility.Initial26
import PoincareChapterVI.ConnectorFactorAdmissibility.Initial27
import PoincareChapterVI.ConnectorFactorAdmissibility.Initial28
import PoincareChapterVI.ConnectorFactorAdmissibility.Initial29
import PoincareChapterVI.ConnectorFactorAdmissibility.Initial30
import PoincareChapterVI.ConnectorFactorAdmissibility.Initial31
import PoincareChapterVI.ConnectorFactorAdmissibility.Final0
import PoincareChapterVI.ConnectorFactorAdmissibility.Final1
import PoincareChapterVI.ConnectorFactorAdmissibility.Final2
import PoincareChapterVI.ConnectorFactorAdmissibility.Final3
import PoincareChapterVI.ConnectorFactorAdmissibility.Final4
import PoincareChapterVI.ConnectorFactorAdmissibility.Final5
import PoincareChapterVI.ConnectorFactorAdmissibility.Final6
import PoincareChapterVI.ConnectorFactorAdmissibility.Final7
import PoincareChapterVI.ConnectorFactorAdmissibility.Final8
import PoincareChapterVI.ConnectorFactorAdmissibility.Final9
import PoincareChapterVI.ConnectorFactorAdmissibility.Final10
import PoincareChapterVI.ConnectorFactorAdmissibility.Final11
import PoincareChapterVI.ConnectorFactorAdmissibility.Final12
import PoincareChapterVI.ConnectorFactorAdmissibility.Final13
import PoincareChapterVI.ConnectorFactorAdmissibility.Final14
import PoincareChapterVI.ConnectorFactorAdmissibility.Final15
import PoincareChapterVI.ConnectorFactorAdmissibility.Final16
import PoincareChapterVI.ConnectorFactorAdmissibility.Final17
import PoincareChapterVI.ConnectorFactorAdmissibility.Final18
import PoincareChapterVI.ConnectorFactorAdmissibility.Final19
import PoincareChapterVI.ConnectorFactorAdmissibility.Final20
import PoincareChapterVI.ConnectorFactorAdmissibility.Final21
import PoincareChapterVI.ConnectorFactorAdmissibility.Final22
import PoincareChapterVI.ConnectorFactorAdmissibility.Final23
import PoincareChapterVI.ConnectorFactorAdmissibility.Final24
import PoincareChapterVI.ConnectorFactorAdmissibility.Final25
import PoincareChapterVI.ConnectorFactorAdmissibility.Final26
import PoincareChapterVI.ConnectorFactorAdmissibility.Final27
import PoincareChapterVI.ConnectorFactorAdmissibility.Final28
import PoincareChapterVI.ConnectorFactorAdmissibility.Final29
import PoincareChapterVI.ConnectorFactorAdmissibility.Final30
import PoincareChapterVI.ConnectorFactorAdmissibility.Final31

namespace PoincareChapterVI.ChapterVIDConnectorFactorBulkReference

open ChapterVILeanCompCertBatch
open LeanCompCert.Ports.SignedProductClaims

/-- Every 32-cell connector-factor artifact remains inside LeanCompCert's 64-bit fragment. -/
theorem shard_admissible (side : ChapterVIDOuterArcSide) (shard : Fin shardCount) :
    Admissible (batchClaims (referenceShardOperations side shard)) := by
  cases side with
  | initial =>
    fin_cases shard
    · exact shard_admissible_initial_0
    · exact shard_admissible_initial_1
    · exact shard_admissible_initial_2
    · exact shard_admissible_initial_3
    · exact shard_admissible_initial_4
    · exact shard_admissible_initial_5
    · exact shard_admissible_initial_6
    · exact shard_admissible_initial_7
    · exact shard_admissible_initial_8
    · exact shard_admissible_initial_9
    · exact shard_admissible_initial_10
    · exact shard_admissible_initial_11
    · exact shard_admissible_initial_12
    · exact shard_admissible_initial_13
    · exact shard_admissible_initial_14
    · exact shard_admissible_initial_15
    · exact shard_admissible_initial_16
    · exact shard_admissible_initial_17
    · exact shard_admissible_initial_18
    · exact shard_admissible_initial_19
    · exact shard_admissible_initial_20
    · exact shard_admissible_initial_21
    · exact shard_admissible_initial_22
    · exact shard_admissible_initial_23
    · exact shard_admissible_initial_24
    · exact shard_admissible_initial_25
    · exact shard_admissible_initial_26
    · exact shard_admissible_initial_27
    · exact shard_admissible_initial_28
    · exact shard_admissible_initial_29
    · exact shard_admissible_initial_30
    · exact shard_admissible_initial_31
  | final =>
    fin_cases shard
    · exact shard_admissible_final_0
    · exact shard_admissible_final_1
    · exact shard_admissible_final_2
    · exact shard_admissible_final_3
    · exact shard_admissible_final_4
    · exact shard_admissible_final_5
    · exact shard_admissible_final_6
    · exact shard_admissible_final_7
    · exact shard_admissible_final_8
    · exact shard_admissible_final_9
    · exact shard_admissible_final_10
    · exact shard_admissible_final_11
    · exact shard_admissible_final_12
    · exact shard_admissible_final_13
    · exact shard_admissible_final_14
    · exact shard_admissible_final_15
    · exact shard_admissible_final_16
    · exact shard_admissible_final_17
    · exact shard_admissible_final_18
    · exact shard_admissible_final_19
    · exact shard_admissible_final_20
    · exact shard_admissible_final_21
    · exact shard_admissible_final_22
    · exact shard_admissible_final_23
    · exact shard_admissible_final_24
    · exact shard_admissible_final_25
    · exact shard_admissible_final_26
    · exact shard_admissible_final_27
    · exact shard_admissible_final_28
    · exact shard_admissible_final_29
    · exact shard_admissible_final_30
    · exact shard_admissible_final_31

/-- Every signed comparison in every connector-factor shard is proved by kernel reduction. -/
theorem shard_allHold (side : ChapterVIDOuterArcSide) (shard : Fin shardCount) :
    ∀ claim ∈ batchClaims (referenceShardOperations side shard), claim.Holds := by
  cases side with
  | initial =>
    fin_cases shard
    · exact shard_allHold_initial_0
    · exact shard_allHold_initial_1
    · exact shard_allHold_initial_2
    · exact shard_allHold_initial_3
    · exact shard_allHold_initial_4
    · exact shard_allHold_initial_5
    · exact shard_allHold_initial_6
    · exact shard_allHold_initial_7
    · exact shard_allHold_initial_8
    · exact shard_allHold_initial_9
    · exact shard_allHold_initial_10
    · exact shard_allHold_initial_11
    · exact shard_allHold_initial_12
    · exact shard_allHold_initial_13
    · exact shard_allHold_initial_14
    · exact shard_allHold_initial_15
    · exact shard_allHold_initial_16
    · exact shard_allHold_initial_17
    · exact shard_allHold_initial_18
    · exact shard_allHold_initial_19
    · exact shard_allHold_initial_20
    · exact shard_allHold_initial_21
    · exact shard_allHold_initial_22
    · exact shard_allHold_initial_23
    · exact shard_allHold_initial_24
    · exact shard_allHold_initial_25
    · exact shard_allHold_initial_26
    · exact shard_allHold_initial_27
    · exact shard_allHold_initial_28
    · exact shard_allHold_initial_29
    · exact shard_allHold_initial_30
    · exact shard_allHold_initial_31
  | final =>
    fin_cases shard
    · exact shard_allHold_final_0
    · exact shard_allHold_final_1
    · exact shard_allHold_final_2
    · exact shard_allHold_final_3
    · exact shard_allHold_final_4
    · exact shard_allHold_final_5
    · exact shard_allHold_final_6
    · exact shard_allHold_final_7
    · exact shard_allHold_final_8
    · exact shard_allHold_final_9
    · exact shard_allHold_final_10
    · exact shard_allHold_final_11
    · exact shard_allHold_final_12
    · exact shard_allHold_final_13
    · exact shard_allHold_final_14
    · exact shard_allHold_final_15
    · exact shard_allHold_final_16
    · exact shard_allHold_final_17
    · exact shard_allHold_final_18
    · exact shard_allHold_final_19
    · exact shard_allHold_final_20
    · exact shard_allHold_final_21
    · exact shard_allHold_final_22
    · exact shard_allHold_final_23
    · exact shard_allHold_final_24
    · exact shard_allHold_final_25
    · exact shard_allHold_final_26
    · exact shard_allHold_final_27
    · exact shard_allHold_final_28
    · exact shard_allHold_final_29
    · exact shard_allHold_final_30
    · exact shard_allHold_final_31

end PoincareChapterVI.ChapterVIDConnectorFactorBulkReference
