/- This file is generated by research/generate_chapter_vi_radial_grid.py. -/
import PoincareChapterVI.ChapterVIDRadialTrace
import PoincareChapterVI.ChapterVIUnitSquareGrid

namespace PoincareChapterVI

open ChapterVILeanCompCertBatch
open LeanCompCert.Ports.SignedProductClaims
open scoped unitInterval

namespace ChapterVIDRadialCompiledGrid

abbrev Interval := ChapterVIDRadialTrace.Interval 20

def qD : Interval := ⟨786, 1154⟩
def qDSixthRoot : Interval := ⟨316033, 336928⟩
def xAbs : Interval := ⟨27262, 28312⟩
def collisionRadius : Interval := ⟨310636, 314575⟩
def qDSixthInv : Interval := ⟨3263342, 3479104⟩
def correction : Interval := ⟨966750, 1043739⟩

def endpoint : ChapterVIDRadialTrace.EndpointTrace (precision := 20) where
  qD := qD
  qDSixthRoot := qDSixthRoot
  qDSixthTrace := {
    lowerPower := { square := ⟨95249, 95250⟩, cube := ⟨28707, 28708⟩, sixth := ⟨785, 786⟩ }
    upperPower := { square := ⟨108261, 108262⟩, cube := ⟨34786, 34787⟩, sixth := ⟨1154, 1155⟩ } }
  xAbs := xAbs
  collisionRadius := collisionRadius
  collisionTrace := {
    lowerPower := { square := ⟨92024, 92025⟩, cube := ⟨27261, 27262⟩ }
    upperPower := { square := ⟨94373, 94374⟩, cube := ⟨28312, 28313⟩ } }
  qDSixthInv := qDSixthInv
  correction := correction

def input (i : Fin 17) : Interval :=
  ⟨(i.val * 65536 : ℕ), (min (i.val + 1) 16 * 65536 : ℕ)⟩

def qDeltaProduct : Fin 17 → Interval := ![
  ⟨-65487, 0⟩,
  ⟨-130974, -65463⟩,
  ⟨-196461, -130927⟩,
  ⟨-261948, -196391⟩,
  ⟨-327435, -261855⟩,
  ⟨-392922, -327319⟩,
  ⟨-458409, -392783⟩,
  ⟨-523895, -458247⟩,
  ⟨-589382, -523711⟩,
  ⟨-654869, -589174⟩,
  ⟨-720356, -654638⟩,
  ⟨-785843, -720102⟩,
  ⟨-851330, -785566⟩,
  ⟨-916817, -851030⟩,
  ⟨-982304, -916494⟩,
  ⟨-1047790, -981958⟩,
  ⟨-1047790, -1047422⟩]

def qCubeRoot : Fin 17 → Interval := ![
  ⟨1026275, 1048576⟩,
  ⟨1002962, 1026285⟩,
  ⟨978511, 1002980⟩,
  ⟨952773, 978539⟩,
  ⟨925564, 952812⟩,
  ⟨896653, 925615⟩,
  ⟨865748, 896718⟩,
  ⟨832462, 865828⟩,
  ⟨796279, 832561⟩,
  ⟨756468, 796400⟩,
  ⟨711958, 756617⟩,
  ⟨661055, 712143⟩,
  ⟨600807, 661289⟩,
  ⟨525202, 601114⟩,
  ⟨417679, 525632⟩,
  ⟨95248, 418406⟩,
  ⟨95248, 108264⟩]

def qCubeLowerSquare : Fin 17 → Interval := ![
  ⟨1004448, 1004449⟩,
  ⟨959332, 959333⟩,
  ⟨913127, 913128⟩,
  ⟨865723, 865724⟩,
  ⟨816982, 816983⟩,
  ⟨766741, 766742⟩,
  ⟨714797, 714798⟩,
  ⟨660889, 660890⟩,
  ⟨604686, 604687⟩,
  ⟨545734, 545735⟩,
  ⟨483402, 483403⟩,
  ⟨416749, 416750⟩,
  ⟨344246, 344247⟩,
  ⟨263058, 263059⟩,
  ⟨166373, 166374⟩,
  ⟨8651, 8652⟩,
  ⟨8651, 8652⟩]

def qCubeLowerCube : Fin 17 → Interval := ![
  ⟨983085, 983087⟩,
  ⟨917600, 917602⟩,
  ⟨852112, 852114⟩,
  ⟨786626, 786628⟩,
  ⟨721139, 721140⟩,
  ⟨655651, 655653⟩,
  ⟨590166, 590167⟩,
  ⟨524678, 524680⟩,
  ⟨459193, 459194⟩,
  ⟨393705, 393707⟩,
  ⟨328218, 328220⟩,
  ⟨262731, 262733⟩,
  ⟨197244, 197245⟩,
  ⟨131758, 131759⟩,
  ⟨66271, 66272⟩,
  ⟨785, 786⟩,
  ⟨785, 786⟩]

def qCubeUpperSquare : Fin 17 → Interval := ![
  ⟨1048576, 1048576⟩,
  ⟨1004467, 1004468⟩,
  ⟨959366, 959367⟩,
  ⟨913179, 913180⟩,
  ⟨865793, 865794⟩,
  ⟨817072, 817073⟩,
  ⟨766852, 766853⟩,
  ⟨714929, 714930⟩,
  ⟨661046, 661047⟩,
  ⟨604870, 604871⟩,
  ⟨545949, 545950⟩,
  ⟨483653, 483654⟩,
  ⟨417044, 417045⟩,
  ⟨344598, 344599⟩,
  ⟨263489, 263490⟩,
  ⟨166953, 166954⟩,
  ⟨11178, 11179⟩]

def qCubeUpperCube : Fin 17 → Interval := ![
  ⟨1048576, 1048576⟩,
  ⟨983113, 983115⟩,
  ⟨917649, 917651⟩,
  ⟨852185, 852187⟩,
  ⟨786722, 786724⟩,
  ⟨721258, 721260⟩,
  ⟨655794, 655795⟩,
  ⟨590329, 590331⟩,
  ⟨524865, 524867⟩,
  ⟨459402, 459404⟩,
  ⟨393938, 393940⟩,
  ⟨328474, 328475⟩,
  ⟨263010, 263012⟩,
  ⟨197546, 197548⟩,
  ⟨132082, 132083⟩,
  ⟨66618, 66619⟩,
  ⟨1154, 1155⟩]

def qSixthRoot : Fin 17 → Interval := ![
  ⟨1037365, 1048576⟩,
  ⟨1025515, 1037371⟩,
  ⟨1012937, 1025525⟩,
  ⟨999527, 1012953⟩,
  ⟨985151, 999548⟩,
  ⟨969644, 985179⟩,
  ⟨952786, 969679⟩,
  ⟨934291, 952831⟩,
  ⟨913760, 934347⟩,
  ⟨890625, 913831⟩,
  ⟨864026, 890714⟩,
  ⟨832566, 864139⟩,
  ⟨793720, 832714⟩,
  ⟨742100, 793923⟩,
  ⟨661790, 742405⟩,
  ⟨316033, 662368⟩,
  ⟨316033, 336928⟩]

def qSixthLowerSquare : Fin 17 → Interval := ![
  ⟨1026273, 1026274⟩,
  ⟨1002961, 1002962⟩,
  ⟨978509, 978510⟩,
  ⟨952772, 952773⟩,
  ⟨925562, 925563⟩,
  ⟨896653, 896654⟩,
  ⟨865746, 865747⟩,
  ⟨832461, 832462⟩,
  ⟨796277, 796278⟩,
  ⟨756466, 756467⟩,
  ⟨711956, 711957⟩,
  ⟨661054, 661055⟩,
  ⟨600806, 600807⟩,
  ⟨525200, 525201⟩,
  ⟨417676, 417677⟩,
  ⟨95249, 95250⟩,
  ⟨95249, 95250⟩]

def qSixthLowerCube : Fin 17 → Interval := ![
  ⟨1015300, 1015302⟩,
  ⟨980903, 980905⟩,
  ⟨945251, 945253⟩,
  ⟨908204, 908206⟩,
  ⟨869577, 869579⟩,
  ⟨829157, 829158⟩,
  ⟨786657, 786659⟩,
  ⟨741730, 741732⟩,
  ⟨693899, 693901⟩,
  ⟨642516, 642518⟩,
  ⟨586651, 586653⟩,
  ⟨524874, 524876⟩,
  ⟨454780, 454782⟩,
  ⟨371695, 371697⟩,
  ⟨263608, 263610⟩,
  ⟨28707, 28708⟩,
  ⟨28707, 28708⟩]

def qSixthLowerSixth : Fin 17 → Interval := ![
  ⟨983079, 983084⟩,
  ⟨917597, 917602⟩,
  ⟨852107, 852112⟩,
  ⟨786623, 786627⟩,
  ⟨721134, 721138⟩,
  ⟨655652, 655654⟩,
  ⟨590161, 590165⟩,
  ⟨524676, 524680⟩,
  ⟨459190, 459193⟩,
  ⟨393702, 393705⟩,
  ⟨328215, 328219⟩,
  ⟨262730, 262733⟩,
  ⟨197243, 197246⟩,
  ⟨131756, 131759⟩,
  ⟨66270, 66272⟩,
  ⟨785, 786⟩,
  ⟨785, 786⟩]

def qSixthUpperSquare : Fin 17 → Interval := ![
  ⟨1048576, 1048576⟩,
  ⟨1026285, 1026286⟩,
  ⟨1002980, 1002981⟩,
  ⟨978540, 978541⟩,
  ⟨952812, 952813⟩,
  ⟨925614, 925615⟩,
  ⟨896718, 896719⟩,
  ⟨865828, 865829⟩,
  ⟨832561, 832562⟩,
  ⟨796401, 796402⟩,
  ⟨756617, 756618⟩,
  ⟨712143, 712144⟩,
  ⟨661289, 661290⟩,
  ⟨601114, 601115⟩,
  ⟨525632, 525633⟩,
  ⟨418406, 418407⟩,
  ⟨108261, 108262⟩]

def qSixthUpperCube : Fin 17 → Interval := ![
  ⟨1048576, 1048576⟩,
  ⟨1015318, 1015320⟩,
  ⟨980931, 980933⟩,
  ⟨945296, 945298⟩,
  ⟨908261, 908263⟩,
  ⟨869651, 869653⟩,
  ⟨829247, 829249⟩,
  ⟨786769, 786771⟩,
  ⟨741864, 741865⟩,
  ⟨694061, 694063⟩,
  ⟨642709, 642710⟩,
  ⟨586882, 586883⟩,
  ⟨525154, 525156⟩,
  ⟨455129, 455131⟩,
  ⟨372154, 372155⟩,
  ⟨264300, 264301⟩,
  ⟨34786, 34787⟩]

def qSixthUpperSixth : Fin 17 → Interval := ![
  ⟨1048576, 1048576⟩,
  ⟨983114, 983119⟩,
  ⟨917649, 917654⟩,
  ⟨852188, 852193⟩,
  ⟨786722, 786726⟩,
  ⟨721257, 721261⟩,
  ⟨655794, 655798⟩,
  ⟨590329, 590333⟩,
  ⟨524866, 524868⟩,
  ⟨459404, 459408⟩,
  ⟨393938, 393941⟩,
  ⟨328474, 328476⟩,
  ⟨263010, 263013⟩,
  ⟨197546, 197549⟩,
  ⟨132082, 132084⟩,
  ⟨66618, 66619⟩,
  ⟨1154, 1155⟩]

def correctionDeltaProduct : Fin 17 → Interval := ![
  ⟨-5115, 0⟩,
  ⟨-10229, -302⟩,
  ⟨-15343, -604⟩,
  ⟨-20457, -906⟩,
  ⟨-25571, -1209⟩,
  ⟨-30685, -1511⟩,
  ⟨-35799, -1813⟩,
  ⟨-40913, -2116⟩,
  ⟨-46028, -2418⟩,
  ⟨-51142, -2720⟩,
  ⟨-56256, -3023⟩,
  ⟨-61370, -3325⟩,
  ⟨-66484, -3627⟩,
  ⟨-71598, -3930⟩,
  ⟨-76712, -4232⟩,
  ⟨-81826, -4534⟩,
  ⟨-81826, -4837⟩]

def radius : Fin 17 → Interval := ![
  ⟨1032304, 1048576⟩,
  ⟨1015510, 1037073⟩,
  ⟨998115, 1024935⟩,
  ⟨980026, 1012078⟩,
  ⟨961126, 998396⟩,
  ⟨941268, 983760⟩,
  ⟨920257, 968003⟩,
  ⟨897837, 950909⟩,
  ⟨873649, 932193⟩,
  ⟨847186, 911461⟩,
  ⟨817671, 888147⟩,
  ⟨783838, 861399⟩,
  ⟨743394, 829834⟩,
  ⟨691428, 790948⟩,
  ⟨613374, 739409⟩,
  ⟨291371, 659504⟩,
  ⟨291371, 335374⟩]


def trace (i : Fin 17) : ChapterVIDRadialTrace.Trace endpoint (input i) where
  qDeltaProduct := qDeltaProduct i
  qCubeRoot := qCubeRoot i
  qCubeTrace := {
    lowerPower := { square := qCubeLowerSquare i, cube := qCubeLowerCube i }
    upperPower := { square := qCubeUpperSquare i, cube := qCubeUpperCube i } }
  qSixthRoot := qSixthRoot i
  qSixthTrace := {
    lowerPower := { square := qSixthLowerSquare i, cube := qSixthLowerCube i, sixth := qSixthLowerSixth i }
    upperPower := { square := qSixthUpperSquare i, cube := qSixthUpperCube i, sixth := qSixthUpperSixth i } }
  correctionDeltaProduct := correctionDeltaProduct i
  radius := radius i

def operations : List (DyadicOperation 20) :=
  endpoint.operations ++ (List.ofFn fun i : Fin 17 => (trace i).operations).flatten

theorem endpoint_operations_mem (operation : DyadicOperation 20)
    (hoperation : operation ∈ endpoint.operations) : operation ∈ operations := by
  simp [operations, hoperation]

theorem trace_operations_mem (i : Fin 17) (operation : DyadicOperation 20)
    (hoperation : operation ∈ (trace i).operations) : operation ∈ operations := by
  rw [operations, List.mem_append, List.mem_flatten]
  exact Or.inr ⟨(trace i).operations, List.mem_ofFn.mpr ⟨i, rfl⟩, hoperation⟩

theorem endpoint_valid : endpoint.Valid := by
  unfold ChapterVIDRadialTrace.EndpointTrace.Valid
    ChapterVILeanCompCertRoots.CubicRootTrace.Valid
    ChapterVILeanCompCertRoots.SixthRootTrace.Valid
  decide +kernel

theorem trace_valid (i : Fin 17) : (trace i).Valid := by
  unfold ChapterVIDRadialTrace.Trace.Valid
    ChapterVILeanCompCertRoots.CubicRootTrace.Valid
    ChapterVILeanCompCertRoots.SixthRootTrace.Valid
  fin_cases i <;> decide +kernel

theorem operations_admissible : Admissible (batchClaims operations) := by
  refine ⟨?_, ?_, ?_⟩
  · decide +kernel
  · decide +kernel
  · decide +kernel

set_option maxRecDepth 100000 in
theorem operations_returns_zero :
    (batchComputation "chapter-vi-d-radial-grid-20" operations).Returns
      ((0 : Nat) : Int) := by
  decide +kernel

theorem qD_contains : qD.Contains chapterVIDCriticalParameterModulus := by
  obtain ⟨hlower, hupper⟩ := chapterVIDCriticalParameterModulus_bounds
  constructor
  · exact (by norm_num [qD, ChapterVISignedDyadicInterval.toRealInterval,
      ChapterVISignedDyadicInterval.scale] :
        ((qD.lower : ℝ) / ChapterVISignedDyadicInterval.scale 20) ≤ 3 / 4000).trans hlower
  · exact hupper.trans (by norm_num [qD, ChapterVISignedDyadicInterval.toRealInterval,
      ChapterVISignedDyadicInterval.scale] :
        (11 / 10000 : ℝ) ≤ (qD.upper : ℝ) / ChapterVISignedDyadicInterval.scale 20)

theorem xAbs_contains : xAbs.Contains (-chapterVIDRoot) := by
  constructor
  · change (xAbs.lower : ℝ) / ChapterVISignedDyadicInterval.scale 20 ≤ -chapterVIDRoot
    exact (by norm_num [xAbs, ChapterVISignedDyadicInterval.scale] :
      (xAbs.lower : ℝ) / ChapterVISignedDyadicInterval.scale 20 ≤ 26 / 1000).trans
        (by linarith [chapterVIDRoot_mem.2])
  · change -chapterVIDRoot ≤ (xAbs.upper : ℝ) / ChapterVISignedDyadicInterval.scale 20
    exact (by linarith [chapterVIDRoot_mem.1] : -chapterVIDRoot ≤ 27 / 1000).trans
      (by norm_num [xAbs, ChapterVISignedDyadicInterval.scale])

theorem correction_contains :
    endpoint.correction.Contains chapterVIDCertificateContourCorrection := by
  apply endpoint.correction_contains_of_allSound endpoint_valid
  · intro operation hoperation
    exact allSound_of_returns_zero "chapter-vi-d-radial-grid-20"
      operations operations_admissible operations_returns_zero operation
      (endpoint_operations_mem operation hoperation)
  · exact qD_contains
  · exact xAbs_contains

theorem input_contains_of_mem_cell (i : Fin 17) {parameter : I}
    (hparameter : parameter ∈ chapterVIUnitGridCell 15 i) :
    (input i).Contains (parameter : ℝ) := by
  have hbounds := hparameter
  simp only [chapterVIUnitGridCell, Set.mem_ofPred_eq] at hbounds
  constructor
  · change (((i.val * 65536 : ℕ) : ℤ) : ℝ) / (2 : ℝ) ^ 20 ≤ (parameter : ℝ)
    convert hbounds.1 using 1 <;> norm_num <;> ring
  · change (parameter : ℝ) ≤
      (((min (i.val + 1) 16 * 65536 : ℕ) : ℤ) : ℝ) / (2 : ℝ) ^ 20
    convert hbounds.2 using 1 <;> norm_num <;> ring

theorem outputs_contain_cell (i : Fin 17) {parameter : I}
    (hparameter : parameter ∈ chapterVIUnitGridCell 15 i) :
    (trace i).qCubeRoot.Contains
        (chapterVIDCertificateParameter parameter ^ ((3 : ℝ)⁻¹)) ∧
      (trace i).radius.Contains (chapterVIDCertificateContourRadius parameter) := by
  apply (trace i).outputs_contain_of_allSound (trace_valid i)
  · intro operation hoperation
    exact allSound_of_returns_zero "chapter-vi-d-radial-grid-20"
      operations operations_admissible operations_returns_zero operation
      (trace_operations_mem i operation hoperation)
  · exact input_contains_of_mem_cell i hparameter
  · exact qD_contains
  · exact correction_contains

/-- Every radial parameter belongs to a cell whose one compiled verdict encloses both source
coordinates needed by the outer-arc formula. -/
theorem exists_outputs_contain (parameter : I) :
    ∃ i : Fin 17,
      (trace i).qCubeRoot.Contains
          (chapterVIDCertificateParameter parameter ^ ((3 : ℝ)⁻¹)) ∧
        (trace i).radius.Contains (chapterVIDCertificateContourRadius parameter) := by
  let i := chapterVIUnitGridIndex 15 parameter
  exact ⟨i, outputs_contain_cell i (chapterVIUnitGridIndex_mem_cell 15 parameter)⟩

end ChapterVIDRadialCompiledGrid

end PoincareChapterVI

