/- This file is generated by research/generate_chapter_vi_connector_factor_derivative_admissibility.py. -/
import PoincareChapterVI.ConnectorFactorDerivativeAdmissibility.Initial0
import PoincareChapterVI.ConnectorFactorDerivativeAdmissibility.Initial1
import PoincareChapterVI.ConnectorFactorDerivativeAdmissibility.Initial2
import PoincareChapterVI.ConnectorFactorDerivativeAdmissibility.Initial3
import PoincareChapterVI.ConnectorFactorDerivativeAdmissibility.Initial4
import PoincareChapterVI.ConnectorFactorDerivativeAdmissibility.Initial5
import PoincareChapterVI.ConnectorFactorDerivativeAdmissibility.Initial6
import PoincareChapterVI.ConnectorFactorDerivativeAdmissibility.Initial7
import PoincareChapterVI.ConnectorFactorDerivativeAdmissibility.Initial8
import PoincareChapterVI.ConnectorFactorDerivativeAdmissibility.Initial9
import PoincareChapterVI.ConnectorFactorDerivativeAdmissibility.Initial10
import PoincareChapterVI.ConnectorFactorDerivativeAdmissibility.Initial11
import PoincareChapterVI.ConnectorFactorDerivativeAdmissibility.Initial12
import PoincareChapterVI.ConnectorFactorDerivativeAdmissibility.Initial13
import PoincareChapterVI.ConnectorFactorDerivativeAdmissibility.Initial14
import PoincareChapterVI.ConnectorFactorDerivativeAdmissibility.Initial15
import PoincareChapterVI.ConnectorFactorDerivativeAdmissibility.Initial16
import PoincareChapterVI.ConnectorFactorDerivativeAdmissibility.Initial17
import PoincareChapterVI.ConnectorFactorDerivativeAdmissibility.Initial18
import PoincareChapterVI.ConnectorFactorDerivativeAdmissibility.Initial19
import PoincareChapterVI.ConnectorFactorDerivativeAdmissibility.Final0
import PoincareChapterVI.ConnectorFactorDerivativeAdmissibility.Final1
import PoincareChapterVI.ConnectorFactorDerivativeAdmissibility.Final2
import PoincareChapterVI.ConnectorFactorDerivativeAdmissibility.Final3
import PoincareChapterVI.ConnectorFactorDerivativeAdmissibility.Final4
import PoincareChapterVI.ConnectorFactorDerivativeAdmissibility.Final5
import PoincareChapterVI.ConnectorFactorDerivativeAdmissibility.Final6
import PoincareChapterVI.ConnectorFactorDerivativeAdmissibility.Final7
import PoincareChapterVI.ConnectorFactorDerivativeAdmissibility.Final8
import PoincareChapterVI.ConnectorFactorDerivativeAdmissibility.Final9
import PoincareChapterVI.ConnectorFactorDerivativeAdmissibility.Final10
import PoincareChapterVI.ConnectorFactorDerivativeAdmissibility.Final11
import PoincareChapterVI.ConnectorFactorDerivativeAdmissibility.Final12
import PoincareChapterVI.ConnectorFactorDerivativeAdmissibility.Final13
import PoincareChapterVI.ConnectorFactorDerivativeAdmissibility.Final14
import PoincareChapterVI.ConnectorFactorDerivativeAdmissibility.Final15
import PoincareChapterVI.ConnectorFactorDerivativeAdmissibility.Final16
import PoincareChapterVI.ConnectorFactorDerivativeAdmissibility.Final17
import PoincareChapterVI.ConnectorFactorDerivativeAdmissibility.Final18
import PoincareChapterVI.ConnectorFactorDerivativeAdmissibility.Final19
import PoincareChapterVI.ConnectorFactorDerivativeAdmissibility.Final20

namespace PoincareChapterVI.ChapterVIDConnectorFactorDerivativeReference

open ChapterVILeanCompCertBatch
open LeanCompCert.Ports.SignedProductClaims

/-- Every 12-cell derivative artifact remains inside LeanCompCert's 64-bit fragment. -/
theorem shard_admissible (side : ChapterVIDOuterArcSide)
    (shard : Fin (shardCount side)) :
    Admissible (batchClaims (shardOperations side shard)) := by
  cases side with
  | initial =>
    fin_cases shard
    · exact shard_admissible_initial_0
    · exact shard_admissible_initial_1
    · exact shard_admissible_initial_2
    · exact shard_admissible_initial_3
    · exact shard_admissible_initial_4
    · exact shard_admissible_initial_5
    · exact shard_admissible_initial_6
    · exact shard_admissible_initial_7
    · exact shard_admissible_initial_8
    · exact shard_admissible_initial_9
    · exact shard_admissible_initial_10
    · exact shard_admissible_initial_11
    · exact shard_admissible_initial_12
    · exact shard_admissible_initial_13
    · exact shard_admissible_initial_14
    · exact shard_admissible_initial_15
    · exact shard_admissible_initial_16
    · exact shard_admissible_initial_17
    · exact shard_admissible_initial_18
    · exact shard_admissible_initial_19
  | final =>
    fin_cases shard
    · exact shard_admissible_final_0
    · exact shard_admissible_final_1
    · exact shard_admissible_final_2
    · exact shard_admissible_final_3
    · exact shard_admissible_final_4
    · exact shard_admissible_final_5
    · exact shard_admissible_final_6
    · exact shard_admissible_final_7
    · exact shard_admissible_final_8
    · exact shard_admissible_final_9
    · exact shard_admissible_final_10
    · exact shard_admissible_final_11
    · exact shard_admissible_final_12
    · exact shard_admissible_final_13
    · exact shard_admissible_final_14
    · exact shard_admissible_final_15
    · exact shard_admissible_final_16
    · exact shard_admissible_final_17
    · exact shard_admissible_final_18
    · exact shard_admissible_final_19
    · exact shard_admissible_final_20

end PoincareChapterVI.ChapterVIDConnectorFactorDerivativeReference
