/- This file is generated by research/generate_radial_tail_kernel_shards.py. -/
import PoincareChapterVI.RadialTailEndpointKernel.DirectUpper0
import PoincareChapterVI.RadialTailEndpointKernel.DirectUpper1
import PoincareChapterVI.RadialTailEndpointKernel.DirectUpper2
import PoincareChapterVI.RadialTailEndpointKernel.DirectUpper3
import PoincareChapterVI.RadialTailEndpointKernel.DirectUpper4
import PoincareChapterVI.RadialTailEndpointKernel.DirectUpper5
import PoincareChapterVI.RadialTailEndpointKernel.DirectUpper6
import PoincareChapterVI.RadialTailEndpointKernel.DirectUpper7
import PoincareChapterVI.RadialTailEndpointKernel.DirectUpper8
import PoincareChapterVI.RadialTailEndpointKernel.DirectUpper9
import PoincareChapterVI.RadialTailEndpointKernel.DirectUpper10
import PoincareChapterVI.RadialTailEndpointKernel.DirectUpper11
import PoincareChapterVI.RadialTailEndpointKernel.DirectUpper12
import PoincareChapterVI.RadialTailEndpointKernel.DirectUpper13
import PoincareChapterVI.RadialTailEndpointKernel.DirectUpper14
import PoincareChapterVI.RadialTailEndpointKernel.DirectUpper15
import PoincareChapterVI.RadialTailEndpointKernel.DirectUpper16
import PoincareChapterVI.RadialTailEndpointKernel.DirectUpper17
import PoincareChapterVI.RadialTailEndpointKernel.DirectUpper18
import PoincareChapterVI.RadialTailEndpointKernel.DirectUpper19
import PoincareChapterVI.RadialTailEndpointKernel.DirectUpper20
import PoincareChapterVI.RadialTailEndpointKernel.DirectUpper21
import PoincareChapterVI.RadialTailEndpointKernel.DirectUpper22
import PoincareChapterVI.RadialTailEndpointKernel.DirectUpper23
import PoincareChapterVI.RadialTailEndpointKernel.DirectUpper24
import PoincareChapterVI.RadialTailEndpointKernel.DirectUpper25
import PoincareChapterVI.RadialTailEndpointKernel.DirectUpper26
import PoincareChapterVI.RadialTailEndpointKernel.DirectUpper27
import PoincareChapterVI.RadialTailEndpointKernel.DirectUpper28
import PoincareChapterVI.RadialTailEndpointKernel.DirectUpper29
import PoincareChapterVI.RadialTailEndpointKernel.DirectUpper30
import PoincareChapterVI.RadialTailEndpointKernel.DirectUpper31
import PoincareChapterVI.RadialTailEndpointKernel.DirectUpper32
import PoincareChapterVI.RadialTailEndpointKernel.DirectUpper33
import PoincareChapterVI.RadialTailEndpointKernel.DirectUpper34
import PoincareChapterVI.RadialTailEndpointKernel.DirectUpper35
import PoincareChapterVI.RadialTailEndpointKernel.DirectUpper36
import PoincareChapterVI.RadialTailEndpointKernel.DirectUpper37
import PoincareChapterVI.RadialTailEndpointKernel.DirectUpper38
import PoincareChapterVI.RadialTailEndpointKernel.DirectUpper39
import PoincareChapterVI.RadialTailEndpointKernel.DirectUpper40
import PoincareChapterVI.RadialTailEndpointKernel.DirectUpper41
import PoincareChapterVI.RadialTailEndpointKernel.DirectUpper42
import PoincareChapterVI.RadialTailEndpointKernel.DirectUpper43
import PoincareChapterVI.RadialTailEndpointKernel.DirectUpper44
import PoincareChapterVI.RadialTailEndpointKernel.DirectUpper45
import PoincareChapterVI.RadialTailEndpointKernel.DirectUpper46
import PoincareChapterVI.RadialTailEndpointKernel.DirectUpper47
import PoincareChapterVI.RadialTailEndpointKernel.DirectUpper48
import PoincareChapterVI.RadialTailEndpointKernel.DirectUpper49
import PoincareChapterVI.RadialTailEndpointKernel.DirectUpper50
import PoincareChapterVI.RadialTailEndpointKernel.DirectUpper51
import PoincareChapterVI.RadialTailEndpointKernel.DirectUpper52
import PoincareChapterVI.RadialTailEndpointKernel.DirectUpper53
import PoincareChapterVI.RadialTailEndpointKernel.DirectUpper54
import PoincareChapterVI.RadialTailEndpointKernel.DirectUpper55
import PoincareChapterVI.RadialTailEndpointKernel.DirectUpper56
import PoincareChapterVI.RadialTailEndpointKernel.DirectUpper57
import PoincareChapterVI.RadialTailEndpointKernel.DirectUpper58
import PoincareChapterVI.RadialTailEndpointKernel.DirectUpper59
import PoincareChapterVI.RadialTailEndpointKernel.DirectUpper60
import PoincareChapterVI.RadialTailEndpointKernel.DirectUpper61
import PoincareChapterVI.RadialTailEndpointKernel.DirectUpper62
import PoincareChapterVI.RadialTailEndpointKernel.DirectUpper63
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower0
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower1
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower2
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower3
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower4
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower5
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower6
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower7
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower8
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower9
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower10
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower11
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower12
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower13
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower14
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower15
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower16
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower17
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower18
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower19
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower20
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower21
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower22
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower23
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower24
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower25
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower26
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower27
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower28
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower29
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower30
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower31
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower32
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower33
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower34
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower35
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower36
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower37
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower38
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower39
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower40
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower41
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower42
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower43
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower44
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower45
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower46
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower47
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower48
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower49
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower50
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower51
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower52
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower53
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower54
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower55
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower56
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower57
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower58
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower59
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower60
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower61
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower62
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower63
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower64
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower65
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower66
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower67
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower68
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower69
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower70
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower71
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower72
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower73
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower74
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower75
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower76
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower77
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower78
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower79
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower80
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower81
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower82
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower83
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower84
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower85
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower86
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower87
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower88
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower89
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower90
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower91
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower92
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower93
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower94
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower95
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower96
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower97
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower98
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower99
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower100
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower101
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower102
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower103
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower104
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower105
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower106
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower107
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower108
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower109
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower110
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower111
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower112
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower113
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower114
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower115
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower116
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower117
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower118
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower119
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower120
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower121
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower122
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower123
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower124
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower125
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower126
import PoincareChapterVI.RadialTailEndpointKernel.DirectLower127
import PoincareChapterVI.RadialTailEndpointKernel.UpperLocal0
import PoincareChapterVI.RadialTailEndpointKernel.UpperLocal1
import PoincareChapterVI.RadialTailEndpointKernel.UpperLocal2
import PoincareChapterVI.RadialTailEndpointKernel.UpperLocal3
import PoincareChapterVI.RadialTailEndpointKernel.UpperLocal4
import PoincareChapterVI.RadialTailEndpointKernel.UpperLocal5
import PoincareChapterVI.RadialTailEndpointKernel.UpperLocal6
import PoincareChapterVI.RadialTailEndpointKernel.UpperLocal7
import PoincareChapterVI.RadialTailEndpointKernel.UpperLocal8
import PoincareChapterVI.RadialTailEndpointKernel.UpperLocal9
import PoincareChapterVI.RadialTailEndpointKernel.UpperLocal10
import PoincareChapterVI.RadialTailEndpointKernel.UpperLocal11
import PoincareChapterVI.RadialTailEndpointKernel.UpperLocal12
import PoincareChapterVI.RadialTailEndpointKernel.UpperLocal13
import PoincareChapterVI.RadialTailEndpointKernel.UpperLocal14
import PoincareChapterVI.RadialTailEndpointKernel.UpperLocal15
import PoincareChapterVI.RadialTailEndpointKernel.UpperLocal16
import PoincareChapterVI.RadialTailEndpointKernel.UpperLocal17
import PoincareChapterVI.RadialTailEndpointKernel.UpperLocal18
import PoincareChapterVI.RadialTailEndpointKernel.UpperLocal19
import PoincareChapterVI.RadialTailEndpointKernel.UpperLocal20
import PoincareChapterVI.RadialTailEndpointKernel.UpperLocal21
import PoincareChapterVI.RadialTailEndpointKernel.UpperLocal22
import PoincareChapterVI.RadialTailEndpointKernel.UpperLocal23
import PoincareChapterVI.RadialTailEndpointKernel.UpperLocal24
import PoincareChapterVI.RadialTailEndpointKernel.UpperLocal25
import PoincareChapterVI.RadialTailEndpointKernel.UpperLocal26
import PoincareChapterVI.RadialTailEndpointKernel.UpperLocal27
import PoincareChapterVI.RadialTailEndpointKernel.UpperLocal28
import PoincareChapterVI.RadialTailEndpointKernel.UpperLocal29
import PoincareChapterVI.RadialTailEndpointKernel.UpperLocal30
import PoincareChapterVI.RadialTailEndpointKernel.UpperLocal31
import PoincareChapterVI.RadialTailEndpointKernel.UpperLocal32
import PoincareChapterVI.RadialTailEndpointKernel.UpperLocal33
import PoincareChapterVI.RadialTailEndpointKernel.UpperLocal34
import PoincareChapterVI.RadialTailEndpointKernel.UpperLocal35
import PoincareChapterVI.RadialTailEndpointKernel.UpperLocal36
import PoincareChapterVI.RadialTailEndpointKernel.UpperLocal37
import PoincareChapterVI.RadialTailEndpointKernel.UpperLocal38
import PoincareChapterVI.RadialTailEndpointKernel.UpperLocal39
import PoincareChapterVI.RadialTailEndpointKernel.UpperLocal40
import PoincareChapterVI.RadialTailEndpointKernel.UpperLocal41
import PoincareChapterVI.RadialTailEndpointKernel.UpperLocal42
import PoincareChapterVI.RadialTailEndpointKernel.UpperLocal43
import PoincareChapterVI.RadialTailEndpointKernel.UpperLocal44
import PoincareChapterVI.RadialTailEndpointKernel.UpperLocal45
import PoincareChapterVI.RadialTailEndpointKernel.UpperLocal46
import PoincareChapterVI.RadialTailEndpointKernel.UpperLocal47
import PoincareChapterVI.RadialTailEndpointKernel.UpperLocal48
import PoincareChapterVI.RadialTailEndpointKernel.UpperLocal49
import PoincareChapterVI.RadialTailEndpointKernel.UpperLocal50
import PoincareChapterVI.RadialTailEndpointKernel.UpperLocal51
import PoincareChapterVI.RadialTailEndpointKernel.UpperLocal52
import PoincareChapterVI.RadialTailEndpointKernel.UpperLocal53
import PoincareChapterVI.RadialTailEndpointKernel.UpperLocal54
import PoincareChapterVI.RadialTailEndpointKernel.UpperLocal55
import PoincareChapterVI.RadialTailEndpointKernel.UpperLocal56
import PoincareChapterVI.RadialTailEndpointKernel.UpperLocal57
import PoincareChapterVI.RadialTailEndpointKernel.UpperLocal58
import PoincareChapterVI.RadialTailEndpointKernel.UpperLocal59
import PoincareChapterVI.RadialTailEndpointKernel.UpperLocal60
import PoincareChapterVI.RadialTailEndpointKernel.UpperLocal61
import PoincareChapterVI.RadialTailEndpointKernel.UpperLocal62
import PoincareChapterVI.RadialTailEndpointKernel.LowerLocal

/-! Kernel-reduced aggregate of the endpoint direct and curvature shards. -/

namespace PoincareChapterVI
namespace ChapterVIDRadialTailEndpointCompiledGrid

open ChapterVIFieldExpression Expr
open ChapterVILeanCompCertAffineTrace
open ChapterVIDRadialTailBaseCenteredAffineTrace
open ChapterVIDRadialTailCellInputTrace
open ChapterVIDRadialTailEndpointTrace

set_option maxRecDepth 1000000
set_option maxHeartbeats 0

theorem direct_program_valid : ∀ side angular,
    ProgramValid (directInputs side angular)
      (ChapterVIDRadialTailBaseCenteredProgram.program side) = true := by
  intro side angular
  cases side with
  | upper =>
      fin_cases angular
      · exact direct_program_valid_upper_0
      · exact direct_program_valid_upper_1
      · exact direct_program_valid_upper_2
      · exact direct_program_valid_upper_3
      · exact direct_program_valid_upper_4
      · exact direct_program_valid_upper_5
      · exact direct_program_valid_upper_6
      · exact direct_program_valid_upper_7
      · exact direct_program_valid_upper_8
      · exact direct_program_valid_upper_9
      · exact direct_program_valid_upper_10
      · exact direct_program_valid_upper_11
      · exact direct_program_valid_upper_12
      · exact direct_program_valid_upper_13
      · exact direct_program_valid_upper_14
      · exact direct_program_valid_upper_15
      · exact direct_program_valid_upper_16
      · exact direct_program_valid_upper_17
      · exact direct_program_valid_upper_18
      · exact direct_program_valid_upper_19
      · exact direct_program_valid_upper_20
      · exact direct_program_valid_upper_21
      · exact direct_program_valid_upper_22
      · exact direct_program_valid_upper_23
      · exact direct_program_valid_upper_24
      · exact direct_program_valid_upper_25
      · exact direct_program_valid_upper_26
      · exact direct_program_valid_upper_27
      · exact direct_program_valid_upper_28
      · exact direct_program_valid_upper_29
      · exact direct_program_valid_upper_30
      · exact direct_program_valid_upper_31
      · exact direct_program_valid_upper_32
      · exact direct_program_valid_upper_33
      · exact direct_program_valid_upper_34
      · exact direct_program_valid_upper_35
      · exact direct_program_valid_upper_36
      · exact direct_program_valid_upper_37
      · exact direct_program_valid_upper_38
      · exact direct_program_valid_upper_39
      · exact direct_program_valid_upper_40
      · exact direct_program_valid_upper_41
      · exact direct_program_valid_upper_42
      · exact direct_program_valid_upper_43
      · exact direct_program_valid_upper_44
      · exact direct_program_valid_upper_45
      · exact direct_program_valid_upper_46
      · exact direct_program_valid_upper_47
      · exact direct_program_valid_upper_48
      · exact direct_program_valid_upper_49
      · exact direct_program_valid_upper_50
      · exact direct_program_valid_upper_51
      · exact direct_program_valid_upper_52
      · exact direct_program_valid_upper_53
      · exact direct_program_valid_upper_54
      · exact direct_program_valid_upper_55
      · exact direct_program_valid_upper_56
      · exact direct_program_valid_upper_57
      · exact direct_program_valid_upper_58
      · exact direct_program_valid_upper_59
      · exact direct_program_valid_upper_60
      · exact direct_program_valid_upper_61
      · exact direct_program_valid_upper_62
      · exact direct_program_valid_upper_63
  | lower =>
      fin_cases angular
      · exact direct_program_valid_lower_0
      · exact direct_program_valid_lower_1
      · exact direct_program_valid_lower_2
      · exact direct_program_valid_lower_3
      · exact direct_program_valid_lower_4
      · exact direct_program_valid_lower_5
      · exact direct_program_valid_lower_6
      · exact direct_program_valid_lower_7
      · exact direct_program_valid_lower_8
      · exact direct_program_valid_lower_9
      · exact direct_program_valid_lower_10
      · exact direct_program_valid_lower_11
      · exact direct_program_valid_lower_12
      · exact direct_program_valid_lower_13
      · exact direct_program_valid_lower_14
      · exact direct_program_valid_lower_15
      · exact direct_program_valid_lower_16
      · exact direct_program_valid_lower_17
      · exact direct_program_valid_lower_18
      · exact direct_program_valid_lower_19
      · exact direct_program_valid_lower_20
      · exact direct_program_valid_lower_21
      · exact direct_program_valid_lower_22
      · exact direct_program_valid_lower_23
      · exact direct_program_valid_lower_24
      · exact direct_program_valid_lower_25
      · exact direct_program_valid_lower_26
      · exact direct_program_valid_lower_27
      · exact direct_program_valid_lower_28
      · exact direct_program_valid_lower_29
      · exact direct_program_valid_lower_30
      · exact direct_program_valid_lower_31
      · exact direct_program_valid_lower_32
      · exact direct_program_valid_lower_33
      · exact direct_program_valid_lower_34
      · exact direct_program_valid_lower_35
      · exact direct_program_valid_lower_36
      · exact direct_program_valid_lower_37
      · exact direct_program_valid_lower_38
      · exact direct_program_valid_lower_39
      · exact direct_program_valid_lower_40
      · exact direct_program_valid_lower_41
      · exact direct_program_valid_lower_42
      · exact direct_program_valid_lower_43
      · exact direct_program_valid_lower_44
      · exact direct_program_valid_lower_45
      · exact direct_program_valid_lower_46
      · exact direct_program_valid_lower_47
      · exact direct_program_valid_lower_48
      · exact direct_program_valid_lower_49
      · exact direct_program_valid_lower_50
      · exact direct_program_valid_lower_51
      · exact direct_program_valid_lower_52
      · exact direct_program_valid_lower_53
      · exact direct_program_valid_lower_54
      · exact direct_program_valid_lower_55
      · exact direct_program_valid_lower_56
      · exact direct_program_valid_lower_57
      · exact direct_program_valid_lower_58
      · exact direct_program_valid_lower_59
      · exact direct_program_valid_lower_60
      · exact direct_program_valid_lower_61
      · exact direct_program_valid_lower_62
      · exact direct_program_valid_lower_63
      · exact direct_program_valid_lower_64
      · exact direct_program_valid_lower_65
      · exact direct_program_valid_lower_66
      · exact direct_program_valid_lower_67
      · exact direct_program_valid_lower_68
      · exact direct_program_valid_lower_69
      · exact direct_program_valid_lower_70
      · exact direct_program_valid_lower_71
      · exact direct_program_valid_lower_72
      · exact direct_program_valid_lower_73
      · exact direct_program_valid_lower_74
      · exact direct_program_valid_lower_75
      · exact direct_program_valid_lower_76
      · exact direct_program_valid_lower_77
      · exact direct_program_valid_lower_78
      · exact direct_program_valid_lower_79
      · exact direct_program_valid_lower_80
      · exact direct_program_valid_lower_81
      · exact direct_program_valid_lower_82
      · exact direct_program_valid_lower_83
      · exact direct_program_valid_lower_84
      · exact direct_program_valid_lower_85
      · exact direct_program_valid_lower_86
      · exact direct_program_valid_lower_87
      · exact direct_program_valid_lower_88
      · exact direct_program_valid_lower_89
      · exact direct_program_valid_lower_90
      · exact direct_program_valid_lower_91
      · exact direct_program_valid_lower_92
      · exact direct_program_valid_lower_93
      · exact direct_program_valid_lower_94
      · exact direct_program_valid_lower_95
      · exact direct_program_valid_lower_96
      · exact direct_program_valid_lower_97
      · exact direct_program_valid_lower_98
      · exact direct_program_valid_lower_99
      · exact direct_program_valid_lower_100
      · exact direct_program_valid_lower_101
      · exact direct_program_valid_lower_102
      · exact direct_program_valid_lower_103
      · exact direct_program_valid_lower_104
      · exact direct_program_valid_lower_105
      · exact direct_program_valid_lower_106
      · exact direct_program_valid_lower_107
      · exact direct_program_valid_lower_108
      · exact direct_program_valid_lower_109
      · exact direct_program_valid_lower_110
      · exact direct_program_valid_lower_111
      · exact direct_program_valid_lower_112
      · exact direct_program_valid_lower_113
      · exact direct_program_valid_lower_114
      · exact direct_program_valid_lower_115
      · exact direct_program_valid_lower_116
      · exact direct_program_valid_lower_117
      · exact direct_program_valid_lower_118
      · exact direct_program_valid_lower_119
      · exact direct_program_valid_lower_120
      · exact direct_program_valid_lower_121
      · exact direct_program_valid_lower_122
      · exact direct_program_valid_lower_123
      · exact direct_program_valid_lower_124
      · exact direct_program_valid_lower_125
      · exact direct_program_valid_lower_126
      · exact direct_program_valid_lower_127

theorem direct_program_operations_sound : ∀ side angular operation,
    operation ∈ (ChapterVIDRadialTailBaseCenteredAffineTrace.trace side
      (directInputs side angular)).operations → operation.Sound := by
  intro side angular
  exact proposeProgram_operations_sound _ _ (direct_program_valid side angular)

theorem direct_product_operations_sound : ∀ side angular operation,
    operation ∈ (directProductTrace side angular).operations → operation.Sound := by
  intro side angular
  exact proposeMul_operations_sound _ _

theorem upper_direct_positive : ∀ i : Fin 62,
    0 < (directOutput .upper ⟨i, by simp [angularCells]; omega⟩).real.lower := by
  intro i
  fin_cases i
  · exact direct_positive_upper_0
  · exact direct_positive_upper_1
  · exact direct_positive_upper_2
  · exact direct_positive_upper_3
  · exact direct_positive_upper_4
  · exact direct_positive_upper_5
  · exact direct_positive_upper_6
  · exact direct_positive_upper_7
  · exact direct_positive_upper_8
  · exact direct_positive_upper_9
  · exact direct_positive_upper_10
  · exact direct_positive_upper_11
  · exact direct_positive_upper_12
  · exact direct_positive_upper_13
  · exact direct_positive_upper_14
  · exact direct_positive_upper_15
  · exact direct_positive_upper_16
  · exact direct_positive_upper_17
  · exact direct_positive_upper_18
  · exact direct_positive_upper_19
  · exact direct_positive_upper_20
  · exact direct_positive_upper_21
  · exact direct_positive_upper_22
  · exact direct_positive_upper_23
  · exact direct_positive_upper_24
  · exact direct_positive_upper_25
  · exact direct_positive_upper_26
  · exact direct_positive_upper_27
  · exact direct_positive_upper_28
  · exact direct_positive_upper_29
  · exact direct_positive_upper_30
  · exact direct_positive_upper_31
  · exact direct_positive_upper_32
  · exact direct_positive_upper_33
  · exact direct_positive_upper_34
  · exact direct_positive_upper_35
  · exact direct_positive_upper_36
  · exact direct_positive_upper_37
  · exact direct_positive_upper_38
  · exact direct_positive_upper_39
  · exact direct_positive_upper_40
  · exact direct_positive_upper_41
  · exact direct_positive_upper_42
  · exact direct_positive_upper_43
  · exact direct_positive_upper_44
  · exact direct_positive_upper_45
  · exact direct_positive_upper_46
  · exact direct_positive_upper_47
  · exact direct_positive_upper_48
  · exact direct_positive_upper_49
  · exact direct_positive_upper_50
  · exact direct_positive_upper_51
  · exact direct_positive_upper_52
  · exact direct_positive_upper_53
  · exact direct_positive_upper_54
  · exact direct_positive_upper_55
  · exact direct_positive_upper_56
  · exact direct_positive_upper_57
  · exact direct_positive_upper_58
  · exact direct_positive_upper_59
  · exact direct_positive_upper_60
  · exact direct_positive_upper_61

theorem lower_direct_positive : ∀ i : Fin 124,
    0 < (directOutput .lower ⟨i + 4, by simp [angularCells]; omega⟩).real.lower := by
  intro i
  fin_cases i
  · exact direct_positive_lower_4
  · exact direct_positive_lower_5
  · exact direct_positive_lower_6
  · exact direct_positive_lower_7
  · exact direct_positive_lower_8
  · exact direct_positive_lower_9
  · exact direct_positive_lower_10
  · exact direct_positive_lower_11
  · exact direct_positive_lower_12
  · exact direct_positive_lower_13
  · exact direct_positive_lower_14
  · exact direct_positive_lower_15
  · exact direct_positive_lower_16
  · exact direct_positive_lower_17
  · exact direct_positive_lower_18
  · exact direct_positive_lower_19
  · exact direct_positive_lower_20
  · exact direct_positive_lower_21
  · exact direct_positive_lower_22
  · exact direct_positive_lower_23
  · exact direct_positive_lower_24
  · exact direct_positive_lower_25
  · exact direct_positive_lower_26
  · exact direct_positive_lower_27
  · exact direct_positive_lower_28
  · exact direct_positive_lower_29
  · exact direct_positive_lower_30
  · exact direct_positive_lower_31
  · exact direct_positive_lower_32
  · exact direct_positive_lower_33
  · exact direct_positive_lower_34
  · exact direct_positive_lower_35
  · exact direct_positive_lower_36
  · exact direct_positive_lower_37
  · exact direct_positive_lower_38
  · exact direct_positive_lower_39
  · exact direct_positive_lower_40
  · exact direct_positive_lower_41
  · exact direct_positive_lower_42
  · exact direct_positive_lower_43
  · exact direct_positive_lower_44
  · exact direct_positive_lower_45
  · exact direct_positive_lower_46
  · exact direct_positive_lower_47
  · exact direct_positive_lower_48
  · exact direct_positive_lower_49
  · exact direct_positive_lower_50
  · exact direct_positive_lower_51
  · exact direct_positive_lower_52
  · exact direct_positive_lower_53
  · exact direct_positive_lower_54
  · exact direct_positive_lower_55
  · exact direct_positive_lower_56
  · exact direct_positive_lower_57
  · exact direct_positive_lower_58
  · exact direct_positive_lower_59
  · exact direct_positive_lower_60
  · exact direct_positive_lower_61
  · exact direct_positive_lower_62
  · exact direct_positive_lower_63
  · exact direct_positive_lower_64
  · exact direct_positive_lower_65
  · exact direct_positive_lower_66
  · exact direct_positive_lower_67
  · exact direct_positive_lower_68
  · exact direct_positive_lower_69
  · exact direct_positive_lower_70
  · exact direct_positive_lower_71
  · exact direct_positive_lower_72
  · exact direct_positive_lower_73
  · exact direct_positive_lower_74
  · exact direct_positive_lower_75
  · exact direct_positive_lower_76
  · exact direct_positive_lower_77
  · exact direct_positive_lower_78
  · exact direct_positive_lower_79
  · exact direct_positive_lower_80
  · exact direct_positive_lower_81
  · exact direct_positive_lower_82
  · exact direct_positive_lower_83
  · exact direct_positive_lower_84
  · exact direct_positive_lower_85
  · exact direct_positive_lower_86
  · exact direct_positive_lower_87
  · exact direct_positive_lower_88
  · exact direct_positive_lower_89
  · exact direct_positive_lower_90
  · exact direct_positive_lower_91
  · exact direct_positive_lower_92
  · exact direct_positive_lower_93
  · exact direct_positive_lower_94
  · exact direct_positive_lower_95
  · exact direct_positive_lower_96
  · exact direct_positive_lower_97
  · exact direct_positive_lower_98
  · exact direct_positive_lower_99
  · exact direct_positive_lower_100
  · exact direct_positive_lower_101
  · exact direct_positive_lower_102
  · exact direct_positive_lower_103
  · exact direct_positive_lower_104
  · exact direct_positive_lower_105
  · exact direct_positive_lower_106
  · exact direct_positive_lower_107
  · exact direct_positive_lower_108
  · exact direct_positive_lower_109
  · exact direct_positive_lower_110
  · exact direct_positive_lower_111
  · exact direct_positive_lower_112
  · exact direct_positive_lower_113
  · exact direct_positive_lower_114
  · exact direct_positive_lower_115
  · exact direct_positive_lower_116
  · exact direct_positive_lower_117
  · exact direct_positive_lower_118
  · exact direct_positive_lower_119
  · exact direct_positive_lower_120
  · exact direct_positive_lower_121
  · exact direct_positive_lower_122
  · exact direct_positive_lower_123
  · exact direct_positive_lower_124
  · exact direct_positive_lower_125
  · exact direct_positive_lower_126
  · exact direct_positive_lower_127

theorem upper_base_program_valid : ∀ k : Fin 63,
    ProgramValid (endpointInputsFromT .upper
      (rationalTModel (upperLocalStart k) (upperLocalEnd k)))
      (ChapterVIDRadialTailBaseCenteredProgram.program .upper) = true := by
  intro k
  fin_cases k
  · exact upper_base_program_valid_0
  · exact upper_base_program_valid_1
  · exact upper_base_program_valid_2
  · exact upper_base_program_valid_3
  · exact upper_base_program_valid_4
  · exact upper_base_program_valid_5
  · exact upper_base_program_valid_6
  · exact upper_base_program_valid_7
  · exact upper_base_program_valid_8
  · exact upper_base_program_valid_9
  · exact upper_base_program_valid_10
  · exact upper_base_program_valid_11
  · exact upper_base_program_valid_12
  · exact upper_base_program_valid_13
  · exact upper_base_program_valid_14
  · exact upper_base_program_valid_15
  · exact upper_base_program_valid_16
  · exact upper_base_program_valid_17
  · exact upper_base_program_valid_18
  · exact upper_base_program_valid_19
  · exact upper_base_program_valid_20
  · exact upper_base_program_valid_21
  · exact upper_base_program_valid_22
  · exact upper_base_program_valid_23
  · exact upper_base_program_valid_24
  · exact upper_base_program_valid_25
  · exact upper_base_program_valid_26
  · exact upper_base_program_valid_27
  · exact upper_base_program_valid_28
  · exact upper_base_program_valid_29
  · exact upper_base_program_valid_30
  · exact upper_base_program_valid_31
  · exact upper_base_program_valid_32
  · exact upper_base_program_valid_33
  · exact upper_base_program_valid_34
  · exact upper_base_program_valid_35
  · exact upper_base_program_valid_36
  · exact upper_base_program_valid_37
  · exact upper_base_program_valid_38
  · exact upper_base_program_valid_39
  · exact upper_base_program_valid_40
  · exact upper_base_program_valid_41
  · exact upper_base_program_valid_42
  · exact upper_base_program_valid_43
  · exact upper_base_program_valid_44
  · exact upper_base_program_valid_45
  · exact upper_base_program_valid_46
  · exact upper_base_program_valid_47
  · exact upper_base_program_valid_48
  · exact upper_base_program_valid_49
  · exact upper_base_program_valid_50
  · exact upper_base_program_valid_51
  · exact upper_base_program_valid_52
  · exact upper_base_program_valid_53
  · exact upper_base_program_valid_54
  · exact upper_base_program_valid_55
  · exact upper_base_program_valid_56
  · exact upper_base_program_valid_57
  · exact upper_base_program_valid_58
  · exact upper_base_program_valid_59
  · exact upper_base_program_valid_60
  · exact upper_base_program_valid_61
  · exact upper_base_program_valid_62

theorem upper_velocity_trace_valid : ∀ k : Fin 63, ∀ i,
    TraceValid (boxesFromT .upper
      (rationalTModel (upperLocalStart k) (upperLocalEnd k)))
      (velocity .upper i) = true := by
  intro k
  fin_cases k
  · exact upper_velocity_trace_valid_0
  · exact upper_velocity_trace_valid_1
  · exact upper_velocity_trace_valid_2
  · exact upper_velocity_trace_valid_3
  · exact upper_velocity_trace_valid_4
  · exact upper_velocity_trace_valid_5
  · exact upper_velocity_trace_valid_6
  · exact upper_velocity_trace_valid_7
  · exact upper_velocity_trace_valid_8
  · exact upper_velocity_trace_valid_9
  · exact upper_velocity_trace_valid_10
  · exact upper_velocity_trace_valid_11
  · exact upper_velocity_trace_valid_12
  · exact upper_velocity_trace_valid_13
  · exact upper_velocity_trace_valid_14
  · exact upper_velocity_trace_valid_15
  · exact upper_velocity_trace_valid_16
  · exact upper_velocity_trace_valid_17
  · exact upper_velocity_trace_valid_18
  · exact upper_velocity_trace_valid_19
  · exact upper_velocity_trace_valid_20
  · exact upper_velocity_trace_valid_21
  · exact upper_velocity_trace_valid_22
  · exact upper_velocity_trace_valid_23
  · exact upper_velocity_trace_valid_24
  · exact upper_velocity_trace_valid_25
  · exact upper_velocity_trace_valid_26
  · exact upper_velocity_trace_valid_27
  · exact upper_velocity_trace_valid_28
  · exact upper_velocity_trace_valid_29
  · exact upper_velocity_trace_valid_30
  · exact upper_velocity_trace_valid_31
  · exact upper_velocity_trace_valid_32
  · exact upper_velocity_trace_valid_33
  · exact upper_velocity_trace_valid_34
  · exact upper_velocity_trace_valid_35
  · exact upper_velocity_trace_valid_36
  · exact upper_velocity_trace_valid_37
  · exact upper_velocity_trace_valid_38
  · exact upper_velocity_trace_valid_39
  · exact upper_velocity_trace_valid_40
  · exact upper_velocity_trace_valid_41
  · exact upper_velocity_trace_valid_42
  · exact upper_velocity_trace_valid_43
  · exact upper_velocity_trace_valid_44
  · exact upper_velocity_trace_valid_45
  · exact upper_velocity_trace_valid_46
  · exact upper_velocity_trace_valid_47
  · exact upper_velocity_trace_valid_48
  · exact upper_velocity_trace_valid_49
  · exact upper_velocity_trace_valid_50
  · exact upper_velocity_trace_valid_51
  · exact upper_velocity_trace_valid_52
  · exact upper_velocity_trace_valid_53
  · exact upper_velocity_trace_valid_54
  · exact upper_velocity_trace_valid_55
  · exact upper_velocity_trace_valid_56
  · exact upper_velocity_trace_valid_57
  · exact upper_velocity_trace_valid_58
  · exact upper_velocity_trace_valid_59
  · exact upper_velocity_trace_valid_60
  · exact upper_velocity_trace_valid_61
  · exact upper_velocity_trace_valid_62

theorem upper_curvature_jet_valid : ∀ k : Fin 63,
    JetTraceValid (boxesFromT .upper
      (rationalTModel (upperLocalStart k) (upperLocalEnd k)))
      (velocityBoxesFromT .upper
        (rationalTModel (upperLocalStart k) (upperLocalEnd k)))
      (firstDerivative .upper) = true := by
  intro k
  fin_cases k
  · exact upper_curvature_jet_valid_0
  · exact upper_curvature_jet_valid_1
  · exact upper_curvature_jet_valid_2
  · exact upper_curvature_jet_valid_3
  · exact upper_curvature_jet_valid_4
  · exact upper_curvature_jet_valid_5
  · exact upper_curvature_jet_valid_6
  · exact upper_curvature_jet_valid_7
  · exact upper_curvature_jet_valid_8
  · exact upper_curvature_jet_valid_9
  · exact upper_curvature_jet_valid_10
  · exact upper_curvature_jet_valid_11
  · exact upper_curvature_jet_valid_12
  · exact upper_curvature_jet_valid_13
  · exact upper_curvature_jet_valid_14
  · exact upper_curvature_jet_valid_15
  · exact upper_curvature_jet_valid_16
  · exact upper_curvature_jet_valid_17
  · exact upper_curvature_jet_valid_18
  · exact upper_curvature_jet_valid_19
  · exact upper_curvature_jet_valid_20
  · exact upper_curvature_jet_valid_21
  · exact upper_curvature_jet_valid_22
  · exact upper_curvature_jet_valid_23
  · exact upper_curvature_jet_valid_24
  · exact upper_curvature_jet_valid_25
  · exact upper_curvature_jet_valid_26
  · exact upper_curvature_jet_valid_27
  · exact upper_curvature_jet_valid_28
  · exact upper_curvature_jet_valid_29
  · exact upper_curvature_jet_valid_30
  · exact upper_curvature_jet_valid_31
  · exact upper_curvature_jet_valid_32
  · exact upper_curvature_jet_valid_33
  · exact upper_curvature_jet_valid_34
  · exact upper_curvature_jet_valid_35
  · exact upper_curvature_jet_valid_36
  · exact upper_curvature_jet_valid_37
  · exact upper_curvature_jet_valid_38
  · exact upper_curvature_jet_valid_39
  · exact upper_curvature_jet_valid_40
  · exact upper_curvature_jet_valid_41
  · exact upper_curvature_jet_valid_42
  · exact upper_curvature_jet_valid_43
  · exact upper_curvature_jet_valid_44
  · exact upper_curvature_jet_valid_45
  · exact upper_curvature_jet_valid_46
  · exact upper_curvature_jet_valid_47
  · exact upper_curvature_jet_valid_48
  · exact upper_curvature_jet_valid_49
  · exact upper_curvature_jet_valid_50
  · exact upper_curvature_jet_valid_51
  · exact upper_curvature_jet_valid_52
  · exact upper_curvature_jet_valid_53
  · exact upper_curvature_jet_valid_54
  · exact upper_curvature_jet_valid_55
  · exact upper_curvature_jet_valid_56
  · exact upper_curvature_jet_valid_57
  · exact upper_curvature_jet_valid_58
  · exact upper_curvature_jet_valid_59
  · exact upper_curvature_jet_valid_60
  · exact upper_curvature_jet_valid_61
  · exact upper_curvature_jet_valid_62

theorem upper_base_operations_sound (k : Fin 63) (operation) :
    operation ∈ (ChapterVIDRadialTailBaseCenteredAffineTrace.trace .upper
      (endpointInputsFromT .upper
        (rationalTModel (upperLocalStart k) (upperLocalEnd k)))).operations →
      operation.Sound :=
  proposeProgram_operations_sound _ _ (upper_base_program_valid k) operation

theorem lower_base_operations_sound (operation) :
    operation ∈ (ChapterVIDRadialTailBaseCenteredAffineTrace.trace .lower
      (endpointInputsFromT .lower (rationalTModel 0 (1 / 1024)))).operations →
      operation.Sound :=
  proposeProgram_operations_sound _ _ lower_base_program_valid operation

theorem upper_velocity_operations_sound (k : Fin 63) (i) (operation) :
    operation ∈ (proposeTrace (boxesFromT .upper
      (rationalTModel (upperLocalStart k) (upperLocalEnd k)))
      (velocity .upper i)).operations → operation.Sound :=
  proposeTrace_operations_sound _ _ (upper_velocity_trace_valid k i) operation

theorem lower_velocity_operations_sound (i) (operation) :
    operation ∈ (proposeTrace (boxesFromT .lower (rationalTModel 0 (1 / 1024)))
      (velocity .lower i)).operations → operation.Sound :=
  proposeTrace_operations_sound _ _ (lower_velocity_trace_valid i) operation

theorem upper_curvature_operations_sound (k : Fin 63) (operation) :
    operation ∈ (secondJetFromT .upper
      (upperLocalStart k) (upperLocalEnd k)).operations → operation.Sound := by
  simpa [secondJetFromT] using
    proposeJetTrace_operations_sound _ _ _ (upper_curvature_jet_valid k) operation

theorem lower_curvature_operations_sound (operation) :
    operation ∈ (secondJetFromT .lower 0 (1 / 1024)).operations → operation.Sound := by
  simpa [secondJetFromT] using
    proposeJetTrace_operations_sound _ _ _ lower_curvature_jet_valid operation

theorem upper_curvature_positive : ∀ i : Fin 63,
    0 < (secondJetFromT .upper (upperLocalStart i) (upperLocalEnd i)).derivative.real.lower := by
  intro k
  fin_cases k
  · exact upper_curvature_positive_0
  · exact upper_curvature_positive_1
  · exact upper_curvature_positive_2
  · exact upper_curvature_positive_3
  · exact upper_curvature_positive_4
  · exact upper_curvature_positive_5
  · exact upper_curvature_positive_6
  · exact upper_curvature_positive_7
  · exact upper_curvature_positive_8
  · exact upper_curvature_positive_9
  · exact upper_curvature_positive_10
  · exact upper_curvature_positive_11
  · exact upper_curvature_positive_12
  · exact upper_curvature_positive_13
  · exact upper_curvature_positive_14
  · exact upper_curvature_positive_15
  · exact upper_curvature_positive_16
  · exact upper_curvature_positive_17
  · exact upper_curvature_positive_18
  · exact upper_curvature_positive_19
  · exact upper_curvature_positive_20
  · exact upper_curvature_positive_21
  · exact upper_curvature_positive_22
  · exact upper_curvature_positive_23
  · exact upper_curvature_positive_24
  · exact upper_curvature_positive_25
  · exact upper_curvature_positive_26
  · exact upper_curvature_positive_27
  · exact upper_curvature_positive_28
  · exact upper_curvature_positive_29
  · exact upper_curvature_positive_30
  · exact upper_curvature_positive_31
  · exact upper_curvature_positive_32
  · exact upper_curvature_positive_33
  · exact upper_curvature_positive_34
  · exact upper_curvature_positive_35
  · exact upper_curvature_positive_36
  · exact upper_curvature_positive_37
  · exact upper_curvature_positive_38
  · exact upper_curvature_positive_39
  · exact upper_curvature_positive_40
  · exact upper_curvature_positive_41
  · exact upper_curvature_positive_42
  · exact upper_curvature_positive_43
  · exact upper_curvature_positive_44
  · exact upper_curvature_positive_45
  · exact upper_curvature_positive_46
  · exact upper_curvature_positive_47
  · exact upper_curvature_positive_48
  · exact upper_curvature_positive_49
  · exact upper_curvature_positive_50
  · exact upper_curvature_positive_51
  · exact upper_curvature_positive_52
  · exact upper_curvature_positive_53
  · exact upper_curvature_positive_54
  · exact upper_curvature_positive_55
  · exact upper_curvature_positive_56
  · exact upper_curvature_positive_57
  · exact upper_curvature_positive_58
  · exact upper_curvature_positive_59
  · exact upper_curvature_positive_60
  · exact upper_curvature_positive_61
  · exact upper_curvature_positive_62

end ChapterVIDRadialTailEndpointCompiledGrid
end PoincareChapterVI
