/- This file is generated by research/generate_chapter_vi_homogeneous_admissibility.py. -/
import PoincareChapterVI.ChapterVIDHomogeneousCompiledTable

namespace PoincareChapterVI.ChapterVIDHomogeneousCompiledTable

open ChapterVILeanCompCertBatch
open LeanCompCert.Ports.SignedProductClaims

set_option maxRecDepth 1000000 in
theorem shard_admissible_final_1 :
    Admissible (batchClaims (shardOperations .final ⟨1, by decide⟩)) := by
  refine ⟨?_, ?_, ?_⟩
  · decide +kernel
  · decide +kernel
  · decide +kernel

set_option maxRecDepth 1000000 in
theorem shard_allHold_final_1 :
    ∀ claim ∈ batchClaims (shardOperations .final ⟨1, by decide⟩), claim.Holds := by
  decide +kernel

end PoincareChapterVI.ChapterVIDHomogeneousCompiledTable
