/- This file is generated by research/generate_chapter_vi_connector_factor_admissibility.py. -/
import PoincareChapterVI.ChapterVIDConnectorFactorBulkReference

namespace PoincareChapterVI.ChapterVIDConnectorFactorBulkReference

open ChapterVILeanCompCertBatch
open LeanCompCert.Ports.SignedProductClaims

set_option maxRecDepth 1000000 in
theorem shard_admissible_final_13 :
    Admissible (batchClaims (referenceShardOperations .final ⟨13, by decide⟩)) := by
  refine ⟨?_, ?_, ?_⟩
  · decide +kernel
  · decide +kernel
  · decide +kernel

end PoincareChapterVI.ChapterVIDConnectorFactorBulkReference
