/-
Copyright (c) 2026 Gershon Bialer. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Gershon Bialer
-/

import LeanCompCert.Verified.Decide
import PoincareChapterVI.Section103.InfinityNormalFormData
import Std.Data.TreeMap

/-!
# Finite certificate checker for the Section 103 infinity normal forms

The exact data was generated by finite linear algebra over `ℚ[i]`.  The definitions below form
the independent Lean checker.  A balanced map keyed by paired exponents gives every sparse
polynomial a canonical normal form without expanding a dense coefficient rectangle.
-/

namespace PoincareChapterVI.InfinityNormalFormCertificate

open InfinityNormalFormData

def neg (p : Sparse) : Sparse := p.map fun term => ⟨term.exp, -term.coeff⟩
def add (p q : Sparse) : Sparse := p ++ q

def mulExp (left right : Exp) : Exp :=
  ⟨left.y + right.y, left.z + right.z⟩

def mul (p q : Sparse) : Sparse :=
  p.flatMap fun left => q.map fun right =>
    ⟨mulExp left.exp right.exp, left.coeff * right.coeff⟩

def coefficient : Sparse → Exp → QI
  | [], _ => 0
  | term :: terms, exponent =>
      (if term.exp = exponent then term.coeff else 0) + coefficient terms exponent

def linearCombination (q1 q2 q3 h1 h2 h3 : Sparse) : Sparse :=
  add (mul q1 h1) (add (mul q2 h2) (mul q3 h3))

def expKey (exponent : Exp) : ℕ := Nat.pair exponent.y exponent.z

def insertTerm (terms : Std.TreeMap ℕ QI) (term : Term) : Std.TreeMap ℕ QI :=
  terms.alter (expKey term.exp) fun previous =>
    let value := previous.getD 0 + term.coeff
    if value = 0 then none else some value

def accumulate : Sparse → Std.TreeMap ℕ QI → Std.TreeMap ℕ QI
  | [], terms => terms
  | term :: rest, terms => accumulate rest (insertTerm terms term)

/-- Canonical sparse normalization used by the finite checker.  Zero coefficients are deleted,
so extensional equality is independent of the order in which terms were generated. -/
def normalMap (p : Sparse) : Std.TreeMap ℕ QI := accumulate p {}

def xLocalizedFirstLeft : Sparse :=
  add (mul xLocalizedLeft1 xF) (mul xLocalizedRight1 xG)
def xLocalizedFirstRight : Sparse := mul xCofactor xH1
def xLocalizedSecondLeft : Sparse :=
  add (mul xLocalizedLeft2 xF) (mul xLocalizedRight2 xG)
def xLocalizedSecondRight : Sparse := mul xCofactor xH2
def xLocalizedThirdLeft : Sparse :=
  add (mul xLocalizedLeft3 xF) (mul xLocalizedRight3 xG)
def xLocalizedThirdRight : Sparse := mul xCofactor xH3

def yLocalizedFirstLeft : Sparse :=
  add (mul yLocalizedLeft1 yF) (mul yLocalizedRight1 yG)
def yLocalizedFirstRight : Sparse := mul yCofactor yH1
def yLocalizedSecondLeft : Sparse :=
  add (mul yLocalizedLeft2 yF) (mul yLocalizedRight2 yG)
def yLocalizedSecondRight : Sparse := mul yCofactor yH2
def yLocalizedThirdLeft : Sparse :=
  add (mul yLocalizedLeft3 yF) (mul yLocalizedRight3 yG)
def yLocalizedThirdRight : Sparse := mul yCofactor yH3

def xChartFirstLeft : Sparse :=
  linearCombination xFQuotient1 xFQuotient2 xFQuotient3 xH1 xH2 xH3
def xChartFirstRight : Sparse := xF
def xChartSecondLeft : Sparse :=
  linearCombination xGQuotient1 xGQuotient2 xGQuotient3 xH1 xH2 xH3
def xChartSecondRight : Sparse := xG

def yChartFirstLeft : Sparse :=
  linearCombination yFQuotient1 yFQuotient2 yFQuotient3 yH1 yH2 yH3
def yChartFirstRight : Sparse := yF
def yChartSecondLeft : Sparse :=
  linearCombination yGQuotient1 yGQuotient2 yGQuotient3 yH1 yH2 yH3
def yChartSecondRight : Sparse := yG

end PoincareChapterVI.InfinityNormalFormCertificate
