/- This file is generated by
research/generate_chapter_vi_pinching_prefix_admissibility.py. -/
import PoincareChapterVI.ChapterVIDPinchingArcPrefixCompiledGrid

namespace PoincareChapterVI.ChapterVIDPinchingArcPrefixCompiledGrid

open ChapterVILeanCompCertBatch
open LeanCompCert.Ports.SignedProductClaims

set_option maxRecDepth 1000000 in
theorem shard_admissible_lower_10 :
    Admissible (batchClaims (shardOperations .lower 10)) := by
  refine ⟨?_, ?_, ?_⟩
  · decide +kernel
  · decide +kernel
  · decide +kernel

set_option maxRecDepth 1000000 in
theorem shard_allHold_lower_10 :
    ∀ claim ∈ batchClaims (shardOperations .lower 10), claim.Holds := by
  decide +kernel

end PoincareChapterVI.ChapterVIDPinchingArcPrefixCompiledGrid
