/- This file is generated by research/generate_radial_tail_kernel_shards.py. -/
import PoincareChapterVI.ChapterVIDRadialTailEndpointCompiledGrid

namespace PoincareChapterVI.ChapterVIDRadialTailEndpointCompiledGrid

open ChapterVIFieldExpression Expr
open ChapterVILeanCompCertAffineTrace

set_option maxRecDepth 1000000
set_option maxHeartbeats 0

theorem direct_program_valid_lower_124 :
    ProgramValid (directInputs .lower (⟨124, by decide⟩ : Fin 128))
      (ChapterVIDRadialTailBaseCenteredProgram.program .lower) = true := by
  decide +kernel

theorem direct_positive_lower_124 :
    0 < (directOutput .lower (⟨124, by decide⟩ : Fin 128)).real.lower := by
  decide +kernel

end PoincareChapterVI.ChapterVIDRadialTailEndpointCompiledGrid
