/- This file is generated by research/generate_radial_tail_kernel_shards.py. -/
import PoincareChapterVI.ChapterVIDRadialTailEndpointCompiledGrid

namespace PoincareChapterVI.ChapterVIDRadialTailEndpointCompiledGrid

open ChapterVIFieldExpression Expr
open ChapterVILeanCompCertAffineTrace

set_option maxRecDepth 1000000
set_option maxHeartbeats 0

theorem direct_program_valid_upper_5 :
    ProgramValid (directInputs .upper (⟨5, by decide⟩ : Fin 64))
      (ChapterVIDRadialTailBaseCenteredProgram.program .upper) = true := by
  decide +kernel

theorem direct_positive_upper_5 :
    0 < (directOutput .upper (⟨5, by decide⟩ : Fin 64)).real.lower := by
  decide +kernel

end PoincareChapterVI.ChapterVIDRadialTailEndpointCompiledGrid
