/- This file is generated by research/generate_radial_tail_kernel_shards.py. -/
import PoincareChapterVI.ChapterVIDRadialTailEndpointCompiledGrid

namespace PoincareChapterVI.ChapterVIDRadialTailEndpointCompiledGrid

open ChapterVIFieldExpression Expr
open ChapterVILeanCompCertAffineTrace
open ChapterVIDRadialTailEndpointTrace

set_option maxRecDepth 1000000
set_option maxHeartbeats 0

theorem lower_base_program_valid :
    ProgramValid (endpointInputsFromT .lower (rationalTModel 0 (1 / 1024)))
      (ChapterVIDRadialTailBaseCenteredProgram.program .lower) = true := by
  decide +kernel

theorem lower_velocity_trace_valid : ∀ i,
    TraceValid (boxesFromT .lower (rationalTModel 0 (1 / 1024)))
      (velocity .lower i) = true := by
  intro i
  fin_cases i <;> decide +kernel

theorem lower_curvature_jet_valid :
    JetTraceValid (boxesFromT .lower (rationalTModel 0 (1 / 1024)))
      (velocityBoxesFromT .lower (rationalTModel 0 (1 / 1024)))
      (firstDerivative .lower) = true := by
  decide +kernel

theorem lower_curvature_positive :
    0 < (secondJetFromT .lower 0 (1 / 1024)).derivative.real.lower := by
  decide +kernel

end PoincareChapterVI.ChapterVIDRadialTailEndpointCompiledGrid
