/- This file is generated by research/generate_radial_tail_kernel_shards.py. -/
import PoincareChapterVI.ChapterVIDRadialTailEndpointCompiledGrid

namespace PoincareChapterVI.ChapterVIDRadialTailEndpointCompiledGrid

open ChapterVIFieldExpression Expr
open ChapterVILeanCompCertAffineTrace
open ChapterVIDRadialTailEndpointTrace

set_option maxRecDepth 1000000
set_option maxHeartbeats 0

theorem upper_base_program_valid_24 :
    ProgramValid (endpointInputsFromT .upper
      (rationalTModel (upperLocalStart (⟨24, by decide⟩ : Fin 63)) (upperLocalEnd (⟨24, by decide⟩ : Fin 63))))
      (ChapterVIDRadialTailBaseCenteredProgram.program .upper) = true := by
  decide +kernel

theorem upper_velocity_trace_valid_24 : ∀ i,
    TraceValid (boxesFromT .upper
      (rationalTModel (upperLocalStart (⟨24, by decide⟩ : Fin 63)) (upperLocalEnd (⟨24, by decide⟩ : Fin 63))))
      (velocity .upper i) = true := by
  intro i
  fin_cases i <;> decide +kernel

theorem upper_curvature_jet_valid_24 :
    JetTraceValid (boxesFromT .upper
      (rationalTModel (upperLocalStart (⟨24, by decide⟩ : Fin 63)) (upperLocalEnd (⟨24, by decide⟩ : Fin 63))))
      (velocityBoxesFromT .upper
        (rationalTModel (upperLocalStart (⟨24, by decide⟩ : Fin 63)) (upperLocalEnd (⟨24, by decide⟩ : Fin 63))))
      (firstDerivative .upper) = true := by
  decide +kernel

theorem upper_curvature_positive_24 :
    0 < (secondJetFromT .upper (upperLocalStart (⟨24, by decide⟩ : Fin 63))
      (upperLocalEnd (⟨24, by decide⟩ : Fin 63))).derivative.real.lower := by
  decide +kernel

end PoincareChapterVI.ChapterVIDRadialTailEndpointCompiledGrid
