/- This file is generated by research/generate_chapter_vi_polar_admissibility.py. -/
import PoincareChapterVI.ChapterVIDOuterArcPolarCompiledGrid

namespace PoincareChapterVI.ChapterVIDOuterArcPolarCompiledGrid

open ChapterVILeanCompCertBatch
open LeanCompCert.Ports.SignedProductClaims
open scoped unitInterval

set_option maxRecDepth 1000000 in
theorem shard_admissible_final_8 :
    Admissible (batchClaims (shardOperations .final 8)) := by
  refine ⟨?_, ?_, ?_⟩
  · decide +kernel
  · decide +kernel
  · decide +kernel

set_option maxRecDepth 1000000 in
theorem shard_allHold_final_8 :
    ∀ claim ∈ batchClaims (shardOperations .final 8), claim.Holds := by
  decide +kernel

end PoincareChapterVI.ChapterVIDOuterArcPolarCompiledGrid
