/- This file is generated by research/generate_chapter_vi_polar_admissibility.py. -/
import PoincareChapterVI.ChapterVIDOuterArcPolarCompiledGrid

namespace PoincareChapterVI.ChapterVIDOuterArcPolarCompiledGrid

open ChapterVILeanCompCertBatch
open LeanCompCert.Ports.SignedProductClaims
open scoped unitInterval

set_option maxRecDepth 1000000 in
theorem shard_admissible_initial_18 :
    Admissible (batchClaims (shardOperations .initial 18)) := by
  refine ⟨?_, ?_, ?_⟩
  · decide +kernel
  · decide +kernel
  · decide +kernel

end PoincareChapterVI.ChapterVIDOuterArcPolarCompiledGrid
